apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: merchant
resources:
  - namespace.yaml
  - configmap.yaml
  - migration.yaml
  - api.yaml
  - workers.yaml
  - network-policies.yaml
  - ui.yaml
  - ops-ui.yaml
  - ingress.yaml
