import { HTTP_OPERATION_POLICIES } from './http-authz.js'
import { MCP_METHODS, type McpMethod } from './mcp.js'
import {
  assertCommercialOperationRegistryTotality,
  defineCommercialOperationRegistry,
  type CommercialOperationPolicy,
  type CommercialOperationRef,
} from './commercial-access.js'

/**
 * Every group below is an exact reviewed inventory. Runtime classification
 * never uses prefixes or HTTP verbs. A new MCP method or HTTP operation is
 * therefore absent from the manifest parity set and fails the E1 totality gate.
 */
export const MCP_OPS_CONTROL_METHODS = [
  'ops.commercial.access.summary',
  'ops.commercial.access-blocks.list',
  'ops.commercial.entitlements.list',
  'ops.commercial.points-ledger.list',
  'ops.commercial.points.adjust.propose',
  'ops.commercial.points.adjust.decide',
  'ops.commercial.catalog-v2.list',
  'ops.commercial.orders-v2.list',
  'ops.commercial.rate-cards.list',
  'ops.commercial.service-fulfillment.list',
  'ops.commercial.service-allocation.create',
  'ops.commercial.service-fulfillment.schedule',
  'ops.commercial.service-fulfillment.start',
  'ops.commercial.service-fulfillment.complete',
  'ops.commercial.service-fulfillment.adjust',
  'ops.canonical.backfill.create',
  'ops.canonical.backfill.get',
  'ops.canonical.backfill.pause',
  'ops.canonical.backfill.resume',
  'ops.canonical.backfill.run',
  'ops.canonical.backfill.conflicts.list',
  'ops.canonical.backfill.conflict.claim',
  'ops.canonical.backfill.conflict.resolve',
  'ops.rules.workspace.audit',
  'ops.audit.list',
  'ops.audit.platform.list',
  'ops.audit.detail',
  'ops.audit.export',
  'ops.data.delete.list',
  'ops.data.delete.cancel',
  'ops.data.delete.approve',
  'ops.members.list',
  'ops.session',
  'ops.authorization.matrix.get',
  'ops.authorization.roles.list',
  'ops.authorization.role.assign',
  'ops.authorization.role.revoke',
  'ops.authorization.grants.list',
  'ops.authorization.grant.issue',
  'ops.authorization.grant.revoke',
  'ops.workspaces.list',
  'ops.stores.list',
  'ops.brand-units.summary',
  'ops.tasks.summary',
  'ops.model-usage.summary',
  'ops.storage.reconciliation.list',
  'ops.support.tickets.list',
  'ops.support.ticket.get',
  'ops.support.ticket.create',
  'ops.support.ticket.assign',
  'ops.support.ticket.transition',
  'ops.support.ticket.comment',
  'ops.support.sla.report',
  'ops.support.sla.correction.create',
  'ops.support.sla.correction.decide',
  'ops.support.crm.export',
  'ops.incidents.list',
  'ops.incident.get',
  'ops.incident.timeline',
  'ops.incident.create',
  'ops.incident.transition',
  'ops.incident.comment',
  'ops.incident.commander.assign',
  'ops.incident.scope.update',
  'ops.feature-flags.list',
  'ops.feature-flag.upsert',
  'ops.feature-flag.emergency.set',
  'ops.feature-flag.events',
  'ops.feature-flag.evaluate',
  'ops.finance.search',
  'ops.finance.detail',
  'ops.finance.export',
  'ops.users.list',
  'ops.users.export',
  'ops.user.detail',
  'ops.user.suspend',
  'ops.user.activate',
  'ops.user.risk.transition',
  'ops.user.session.revoke',
  'ops.growth.funnel',
  'ops.alerts.list',
  'ops.alert.ack',
  'ops.marketing.queue',
  'ops.marketing.summary',
  'ops.marketing.queue.assign',
  'ops.marketing.image.reconcile',
  'ops.marketing.image.evidence.export',
  'ops.marketing.image.archive.audit',
  'ops.marketing.image.billing.audit',
  'ops.member.upsert',
  'ops.member.suspend',
  'platform.settings.get',
  'platform.settings.update',
  'platform.media.spec.list',
  'platform.media.spec.get',
  'platform.media.spec.create',
  'platform.media.spec.update',
  'platform.media.spec.approve',
  'platform.media.spec.expire',
  'rule.audit',
  'rule.publish',
  'rule.status',
] as const satisfies readonly McpMethod[]

export const MCP_LEGACY_OPS_COMMERCIAL_DISABLED_METHODS = [
  'ops.commercial.offers.list',
  'ops.commercial.offer.upsert',
  'ops.commercial.addons.list',
  'ops.commercial.addon.upsert',
  'ops.commercial.coupons.list',
  'ops.commercial.export',
  'ops.commercial.coupon.upsert',
  'ops.commercial.rollouts.list',
  'ops.commercial.rollout.upsert',
  'ops.commercial.model-markup.get',
  'ops.commercial.model-markup.update',
] as const satisfies readonly McpMethod[]

export const MCP_RECOVERY_ENABLED_METHODS = [
  'workspace.bootstrap',
  'commercial.access.get',
  'commercial.catalog.get',
  'commercial.order.create',
  'commercial.order.payment.get',
  'creative-points.balance.get',
  'creative-points.statement.list',
  'subscription.get',
  'subscription.orders.list',
  'billing.export',
  'billing.status',
  'billing.recharge.get',
  'billing.recharge.list',
  'billing.transactions',
  'workspace.data.export.request',
  'workspace.data.export.get',
  'workspace.data.delete.request',
] as const satisfies readonly McpMethod[]

export const MCP_RECOVERY_DISABLED_METHODS = [
  'subscription.order.create',
  'subscription.change',
  'billing.recharge.create',
] as const satisfies readonly McpMethod[]

export const MCP_POINT_CHARGED_ENABLED_METHODS = [
] as const satisfies readonly McpMethod[]

export const MCP_POINT_CHARGED_DISABLED_METHODS = [
  'catalog.image.generate',
  'multimodal.image.edit',
  'ops.marketing.generation.retry',
  'merchant.first_value',
  'campaign.batch.generate',
  'campaign.batch.retry_failed',
  'catalog.title.optimize',
  'catalog.image.retry',
  'brand.extract',
  'brand.tone.preview',
  'task.understand',
  'creative.directions',
  'creative.brief',
  'creative.preview',
  'content.generate',
  'content.codex.prepare',
  'content.codex.commit',
  'content.review',
  'content.modify',
  'automation.scan',
  'automation.tick',
  'multimodal.generate',
  'multimodal.video.request',
] as const satisfies readonly McpMethod[]

export const MCP_POINT_REQUIRED_NO_CHARGE_ENABLED_METHODS = [
  'ops.marketing.asset_scan.retry',
  'ops.marketing.visual.review',
  'ops.marketing.publish.acknowledge',
  'ops.marketing.revision.create',
  'merchant.start',
  'brand-unit.list',
  'brand-unit.create',
  'brand-unit.bind-store',
  'brand-unit.product.create',
  'brand-unit.listing.create',
  'brand-unit.listing.list',
  'brand-unit.access.grant',
  'canonical.product.consistency',
  'campaign.batch.create',
  'campaign.batch.list',
  'campaign.batch.get',
  'campaign.batch.pause',
  'campaign.batch.resume',
  'workspace.health',
  'workspace.interactive.confirm',
  'workspace.metrics',
  'billing.reconciliation',
  'billing.model-usage.statement',
  'billing.reconciliation.run',
  'billing.model-usage.reconciliation.run',
  'billing.model-usage.resolve',
  'platform.mapping.preflight',
  'platform.model.status',
  'workspace.deactivate',
  'workspace.activate',
  'platform.store.list',
  'platform.connect',
  'platform.store.alias.set',
  'catalog.search',
  'catalog.categories',
  'catalog.title.accept',
  'catalog.import',
  'catalog.import.batch',
  'catalog.sku.update',
  'catalog.product.update',
  'catalog.facts.confirm',
  'catalog.product.disable',
  'catalog.product.enable',
  'catalog.image.get',
  'catalog.image.select',
  'catalog.image.review',
  'sync.retry_failed',
  'rule.list',
  'rule.sync.status',
  'rule.history',
  'asset.list',
  'asset.parse',
  'asset.facts.confirm',
  'asset.preference.update',
  'brand.get',
  'brand.upsert',
  'asset.upload',
  'asset.upload.batch',
  'asset.scan',
  'asset.generation.confirm',
  'asset.rights.update',
  'catalog.sync',
  'catalog.sync.start',
  'catalog.sync.get',
  'deliverable.list',
  'task.history',
  'task.resume',
  'task.clone',
  'task.timeline',
  'feedback.list',
  'feedback.submit',
  'platform.revoke',
  'task.create',
  'task.answer',
  'task.request.create',
  'task.sku.split',
  'task.group.create',
  'creative.directions.update',
  'task.select_direction',
  'task.plan.confirm',
  'generation.get',
  'content.review.decide',
  'content.visual.select',
  'content.versions',
  'content.diff',
  'content.export',
  'content.approve',
  'content.restore',
  'publish.prepare',
  'publish.batch.prepare',
  'publish.batch.confirm',
  'publish.batch.get',
  'publish.batch.pause',
  'publish.batch.resume',
  'publish.batch.retry_failed',
  'automation.policy.get',
  'automation.policy.list',
  'automation.policy.update',
  'automation.pause',
  'publish.confirm',
  'publish.get',
  'knowledge.rule.create',
  'knowledge.rule.list',
  'knowledge.asset.create',
  'knowledge.asset.update',
  'knowledge.asset.list',
  'knowledge.feedback.record',
  'knowledge.learning.list',
  'knowledge.learning.confirm',
  'knowledge.learning.dismiss',
  'knowledge.competitor.create',
  'knowledge.competitor.list',
  'knowledge.competitor.reference',
  'delivery.bundle.verify',
  'multimodal.video.get',
] as const satisfies readonly McpMethod[]

export const MCP_POINT_REQUIRED_NO_CHARGE_DISABLED_METHODS = [
  'workspace.commercial.get',
  'workspace.commercial.update',
  'workspace.usage.get',
  'billing.usage.consume',
  'billing.usage.refund',
  'billing.refund',
] as const satisfies readonly McpMethod[]

export const HTTP_IDENTITY_LINKED_OPERATIONS = [
  'http:GET:/v1/platform-capabilities',
  'http:GET:/v1/delivery-readiness',
  'http:GET:/v1/commercial/access',
  'http:GET:/v1/commercial/catalog',
  'http:POST:/v1/commercial/orders',
  'http:GET:/v1/commercial/orders/{orderId}/payment',
  'http:GET:/v1/creative-points/balance',
  'http:GET:/v1/creative-points/statement',
  'http:GET:/v1/catalog/categories',
  'http:GET:/v1/rules',
  'http:GET:/v1/rules/audit',
  'http:POST:/v1/rules/{packId}/versions',
  'http:POST:/v1/rules/{packId}/versions/{version}/status',
  'http:GET:/v1/brand-profile',
  'http:PUT:/v1/brand-profile',
  'http:POST:/v1/brand-profile/extract',
  'http:GET:/v1/image-generation-jobs',
  'http:GET:/v1/image-generation-jobs/{jobId}',
  'http:GET:/v1/assets',
  'http:POST:/v1/assets',
  'http:GET:/v1/assets/{assetId}/products',
  'http:GET:/v1/products/{productId}/assets',
  'http:GET:/v1/products/{productId}',
  'http:POST:/v1/products/{productId}/assets',
  'http:DELETE:/v1/products/{productId}/assets',
  'http:PUT:/v1/assets/{assetId}/preference',
  'http:PUT:/v1/assets/{assetId}/rights',
  'http:POST:/v1/assets/{assetId}/facts',
  'http:POST:/v1/assets/upload',
  'http:POST:/v1/assets/{assetId}/parse',
  'http:GET:/v1/assets/{assetId}/download',
  'http:GET:/v1/platform-accounts',
  'http:POST:/v1/platform-accounts/{platform}/authorize',
  'http:DELETE:/v1/platform-accounts/{platform}',
  'http:POST:/v1/platform-accounts/{platform}/sync',
  'http:GET:/v1/sync-jobs',
  'http:POST:/v1/sync-jobs',
  'http:GET:/v1/sync-jobs/{jobId}',
  'http:POST:/v1/sync-jobs/{jobId}/retry-failed',
  'http:GET:/v1/products',
  'http:GET:/v1/products/{productId}/image-review',
  'http:POST:/v1/products/{productId}/confirm',
  'http:POST:/v1/products/import/batch',
  'http:POST:/v1/products/import',
  'http:GET:/v1/tasks',
  'http:POST:/v1/tasks',
  'http:POST:/v1/task-groups',
  'http:POST:/v1/tasks/understand',
  'http:POST:/v1/task-requests',
  'http:GET:/v1/tasks/{taskId}/directions',
  'http:POST:/v1/tasks/{taskId}/directions',
  'http:POST:/v1/tasks/{taskId}/sku-split',
  'http:POST:/v1/tasks/{taskId}/answers',
  'http:GET:/v1/tasks/{taskId}',
  'http:POST:/v1/tasks/{taskId}/plan/confirm',
  'http:POST:/v1/tasks/{taskId}/content-jobs',
  'http:POST:/v1/tasks/{taskId}/content',
  'http:GET:/v1/tasks/{taskId}/content-versions',
  'http:GET:/v1/tasks/{taskId}/timeline',
  'http:GET:/v1/tasks/{taskId}/feedback',
  'http:POST:/v1/tasks/{taskId}/feedback',
  'http:POST:/v1/tasks/{taskId}/approve',
  'http:GET:/v1/content-versions/{contentVersionId}/diff',
  'http:GET:/v1/content-versions/{contentVersionId}/review',
  'http:POST:/v1/content-versions/{contentVersionId}/review-decisions',
  'http:POST:/v1/content-versions/{contentVersionId}/modify',
  'http:POST:/v1/content-versions/{contentVersionId}/restore',
  'http:GET:/v1/content-versions/{contentVersionId}/export',
  'http:POST:/v1/tasks/{taskId}/publish-preview',
  'http:GET:/v1/publish-jobs',
  'http:POST:/v1/publish-jobs',
  'http:GET:/v1/publish-jobs/{jobId}',
  'http:POST:/v1/canonical-backfill/conflicts/scan',
] as const satisfies readonly string[]

export const HTTP_RECOVERY_CALLBACK_OPERATIONS = [
  'http:POST:/v1/billing/callback/{channel}',
  'http:POST:/v1/subscriptions/callback/{channel}',
] as const satisfies readonly string[]

export const HTTP_MACHINE_INFRASTRUCTURE_OPERATIONS = [
  'http:GET:/v1/public/assets/{assetId}/display',
  'http:POST:/v1/assets/{assetId}/scan',
  'http:GET:/v1/internal/assets/{assetId}/scan-content',
  'http:POST:/v1/internal/assets/{assetId}/scan-result',
  'http:POST:/v1/sync-jobs/{jobId}/progress',
  'http:GET:/v1/sync-jobs/{jobId}/execution-context',
  'http:POST:/v1/sync-jobs/{jobId}/result',
  'http:GET:/v1/generation-jobs/{jobId}',
  'http:POST:/v1/generation-jobs/{jobId}/defer',
  'http:POST:/v1/generation-jobs/{jobId}/result',
  'http:GET:/v1/worker-events/{eventId}/execution-check',
  'http:GET:/v1/publish-jobs/{jobId}/execution-check',
  'http:GET:/v1/publish-jobs/{jobId}/media',
  'http:POST:/v1/publish-jobs/{jobId}/observation',
  'http:POST:/v1/internal/automation/tick',
  'http:POST:/v1/internal/model-usage',
  'http:POST:/v1/internal/model-usage/reconciliation',
  'http:POST:/v1/internal/storage/reconciliation',
  'http:POST:/v1/internal/support/sla-scan',
  'http:POST:/v1/internal/support/sla-report',
  'http:POST:/v1/internal/storage/orphans/cleanup',
  'http:POST:/v1/internal/image-generation-jobs/reconciliation',
  'http:POST:/v1/internal/image-generation-jobs/{jobId}/result',
  'http:POST:/v1/internal/image-generation-jobs/{jobId}/execution',
  'http:POST:/v1/internal/image-generation-jobs/{jobId}/reconciliation-evidence',
  'http:POST:/v1/internal/image-generation-continuations/{jobId}/execute',
  'http:POST:/v1/ops/data-deletion/complete',
  'http:GET:/v1/oauth/callback/{platform}',
  'http:GET:/healthz',
  'http:GET:/readyz',
  'http:GET:/livez',
  'http:GET:/releasez',
  'http:GET:/metrics',
  'http:POST:/mcp',
] as const satisfies readonly string[]


function mcpPolicies(
  methods: readonly McpMethod[],
  policy: Omit<Extract<CommercialOperationPolicy, { readonly domain: 'COMMERCIAL' }>, 'surface' | 'operation' | 'rate_action'>,
  rateAction: (method: McpMethod) => string | null = () => null,
): CommercialOperationPolicy[] {
  return methods.map(method => ({
    surface: 'MCP',
    operation: method,
    authorization_policy_ref: method,
    ...policy,
    rate_action: rateAction(method),
  } as CommercialOperationPolicy))
}

const mcpRegistry = defineCommercialOperationRegistry([
  ...MCP_OPS_CONTROL_METHODS.map(method => ({
    surface: 'MCP' as const,
    operation: method,
    domain: 'OPS_CONTROL' as const,
    enabled: true,
    classification: null,
    rate_action: null,
    authorization_policy_ref: method,
  })),
  ...mcpPolicies(MCP_LEGACY_OPS_COMMERCIAL_DISABLED_METHODS, { domain: 'COMMERCIAL', enabled: false, classification: 'RECOVERY_CONTROL' }),
  ...mcpPolicies(MCP_RECOVERY_ENABLED_METHODS, { domain: 'COMMERCIAL', enabled: true, classification: 'RECOVERY_CONTROL' }),
  ...mcpPolicies(MCP_RECOVERY_DISABLED_METHODS, { domain: 'COMMERCIAL', enabled: false, classification: 'RECOVERY_CONTROL' }),
  ...mcpPolicies(MCP_POINT_CHARGED_ENABLED_METHODS, { domain: 'COMMERCIAL', enabled: true, classification: 'POINT_CHARGED' }, method => method),
  ...mcpPolicies(MCP_POINT_CHARGED_DISABLED_METHODS, { domain: 'COMMERCIAL', enabled: false, classification: 'POINT_CHARGED' }, method => method),
  ...mcpPolicies(MCP_POINT_REQUIRED_NO_CHARGE_ENABLED_METHODS, { domain: 'COMMERCIAL', enabled: true, classification: 'POINT_REQUIRED_NO_CHARGE' }),
  ...mcpPolicies(MCP_POINT_REQUIRED_NO_CHARGE_DISABLED_METHODS, { domain: 'COMMERCIAL', enabled: false, classification: 'POINT_REQUIRED_NO_CHARGE' }),
])

const mcpByMethod = new Map(mcpRegistry.map(policy => [policy.operation, policy]))
const httpPolicyByOperation = new Map(HTTP_OPERATION_POLICIES.map(policy => [policy.operation, policy]))

function linkedHttpPolicies(): CommercialOperationPolicy[] {
  return HTTP_IDENTITY_LINKED_OPERATIONS.map(operation => {
    const httpPolicy = httpPolicyByOperation.get(operation)
    if (!httpPolicy?.mcpMethod) throw new Error(`HTTP commercial operation lacks an exact MCP authorization reference: ${operation}`)
    const mcpPolicy = mcpByMethod.get(httpPolicy.mcpMethod)
    if (!mcpPolicy) throw new Error(`HTTP commercial operation references an unclassified MCP method: ${operation} -> ${httpPolicy.mcpMethod}`)
    return {
      ...mcpPolicy,
      surface: 'HTTP',
      operation,
      authorization_policy_ref: httpPolicy.mcpMethod,
    }
  })
}

const httpRegistry = defineCommercialOperationRegistry([
  ...linkedHttpPolicies(),
  ...HTTP_RECOVERY_CALLBACK_OPERATIONS.map(operation => ({
    surface: 'HTTP' as const,
    operation,
    domain: 'COMMERCIAL' as const,
    enabled: true,
    classification: 'RECOVERY_CONTROL' as const,
    rate_action: null,
    authorization_policy_ref: null,
  })),
  ...HTTP_MACHINE_INFRASTRUCTURE_OPERATIONS.map(operation => ({
    surface: 'HTTP' as const,
    operation,
    domain: 'MACHINE_INFRASTRUCTURE' as const,
    enabled: true,
    classification: null,
    rate_action: null,
    authorization_policy_ref: null,
  })),
])

export const COMMERCIAL_OPERATION_REGISTRY_VERSION = 'commercial-operation-registry.v1' as const
export const COMMERCIAL_OPERATION_REGISTRY = defineCommercialOperationRegistry([
  ...mcpRegistry,
  ...httpRegistry,
])

export const COMMERCIAL_OPERATION_RUNTIME_MANIFEST = [
  ...MCP_METHODS.map(operation => ({ surface: 'MCP' as const, operation })),
  ...HTTP_OPERATION_POLICIES.map(({ operation }) => ({ surface: 'HTTP' as const, operation })),
] satisfies readonly CommercialOperationRef[]

export const COMMERCIAL_OPERATION_REGISTRY_COVERAGE = assertCommercialOperationRegistryTotality(
  COMMERCIAL_OPERATION_RUNTIME_MANIFEST,
  COMMERCIAL_OPERATION_REGISTRY,
)

function registryCanonicalJson(registry: readonly CommercialOperationPolicy[]): string {
  return JSON.stringify(
    [...registry]
      .sort((left, right) => left.surface.localeCompare(right.surface) || left.operation.localeCompare(right.operation))
      .map(policy => ({
        surface: policy.surface,
        operation: policy.operation,
        domain: policy.domain,
        enabled: policy.enabled,
        classification: policy.classification,
        rate_action: policy.rate_action,
        authorization_policy_ref: policy.authorization_policy_ref ?? null,
      })),
  )
}

function fnv1a32(value: string): string {
  let hash = 0x811c9dc5
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index)
    hash = Math.imul(hash, 0x01000193) >>> 0
  }
  return hash.toString(16).padStart(8, '0')
}

export const COMMERCIAL_OPERATION_REGISTRY_CHECKSUM = `fnv1a32:${fnv1a32(registryCanonicalJson(COMMERCIAL_OPERATION_REGISTRY))}`
