export const ERROR_CODES = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  INVALID_JSON_BODY: 'INVALID_JSON_BODY',
  REQUEST_BODY_TOO_LARGE: 'REQUEST_BODY_TOO_LARGE',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  TENANT_SCOPE_DENIED: 'TENANT_SCOPE_DENIED',
  WORKSPACE_SCOPE_REQUIRED: 'WORKSPACE_SCOPE_REQUIRED',
  WORKSPACE_SCOPE_MISMATCH: 'WORKSPACE_SCOPE_MISMATCH',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  CONTENT_VERSION_NOT_FOUND: 'CONTENT_VERSION_NOT_FOUND',
  CONTENT_VERSION_SCOPE_MISMATCH: 'CONTENT_VERSION_SCOPE_MISMATCH',
  PLATFORM_NOT_SUPPORTED: 'PLATFORM_NOT_SUPPORTED',
  PLATFORM_ACCOUNT_NOT_FOUND: 'PLATFORM_ACCOUNT_NOT_FOUND',
  PLATFORM_AUTH_REQUIRED: 'PLATFORM_AUTH_REQUIRED',
  OAUTH_STATE_INVALID: 'OAUTH_STATE_INVALID',
  OAUTH_STATE_EXPIRED: 'OAUTH_STATE_EXPIRED',
  OAUTH_STATE_REPLAYED: 'OAUTH_STATE_REPLAYED',
  OAUTH_STATE_SCOPE_MISMATCH: 'OAUTH_STATE_SCOPE_MISMATCH',
  CONNECTOR_NOT_READY: 'CONNECTOR_NOT_READY',
  PLATFORM_RATE_LIMITED: 'PLATFORM_RATE_LIMITED',
  PLATFORM_VALIDATION_FAILED: 'PLATFORM_VALIDATION_FAILED',
  PLATFORM_REQUEST_FAILED: 'PLATFORM_REQUEST_FAILED',
  PLATFORM_WRITE_UNKNOWN: 'PLATFORM_WRITE_UNKNOWN',
  INVALID_TASK_TRANSITION: 'INVALID_TASK_TRANSITION',
  INVALID_PUBLISH_TRANSITION: 'INVALID_PUBLISH_TRANSITION',
  FACT_CONFLICT: 'FACT_CONFLICT',
  FACT_CONFIRMATION_REQUIRED: 'FACT_CONFIRMATION_REQUIRED',
  CONTENT_NOT_APPROVED: 'CONTENT_NOT_APPROVED',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
  REVIEW_BLOCKED: 'REVIEW_BLOCKED',
  GENERATION_FAILED: 'GENERATION_FAILED',
  CONFIRMATION_REQUIRED: 'CONFIRMATION_REQUIRED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  STALE_PUBLISH_CONFIRMATION: 'STALE_PUBLISH_CONFIRMATION',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_RETRY_EXHAUSTED: 'JOB_RETRY_EXHAUSTED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  MCP_METHOD_NOT_FOUND: 'MCP_METHOD_NOT_FOUND',
  OAUTH_CODE_REQUIRED: 'OAUTH_CODE_REQUIRED',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  WORKSPACE_JOB_QUOTA_EXCEEDED: 'WORKSPACE_JOB_QUOTA_EXCEEDED',
  CREATIVE_POINTS_EXHAUSTED: 'CREATIVE_POINTS_EXHAUSTED',
  CREATIVE_POINTS_INSUFFICIENT: 'CREATIVE_POINTS_INSUFFICIENT',
  CREATIVE_POINTS_UNAVAILABLE: 'CREATIVE_POINTS_UNAVAILABLE',
  RATE_CARD_UNAVAILABLE: 'RATE_CARD_UNAVAILABLE',
  COMMERCIAL_ACCESS_STALE: 'COMMERCIAL_ACCESS_STALE',
  COMMERCIAL_ENTITLEMENT_UNAVAILABLE: 'COMMERCIAL_ENTITLEMENT_UNAVAILABLE',
  COMMERCIAL_ENTITLEMENT_REQUIRED: 'COMMERCIAL_ENTITLEMENT_REQUIRED',
  COMMERCIAL_ENTITLEMENT_AMBIGUOUS: 'COMMERCIAL_ENTITLEMENT_AMBIGUOUS',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

export interface StableError {
  readonly code: ErrorCode
  readonly message: string
  readonly retryable: boolean
  readonly status: number
  readonly details?: Readonly<Record<string, unknown>>
}

export function isErrorCode(value: string): value is ErrorCode {
  return Object.values(ERROR_CODES).includes(value as ErrorCode)
}

export function createStableError(
  code: ErrorCode,
  message: string,
  options: { readonly retryable?: boolean; readonly status?: number; readonly details?: Readonly<Record<string, unknown>> } = {},
): StableError {
  return {
    code,
    message,
    retryable: options.retryable ?? false,
    status: options.status ?? defaultStatus(code),
    ...(options.details ? { details: options.details } : {}),
  }
}

function defaultStatus(code: ErrorCode): number {
  if (code === ERROR_CODES.UNAUTHENTICATED || code === ERROR_CODES.OAUTH_STATE_EXPIRED) return 401
  if (code === ERROR_CODES.FORBIDDEN || code === ERROR_CODES.TENANT_SCOPE_DENIED || code === ERROR_CODES.WORKSPACE_SCOPE_MISMATCH) return 403
  if (code === ERROR_CODES.CREATIVE_POINTS_EXHAUSTED || code === ERROR_CODES.CREATIVE_POINTS_INSUFFICIENT || code === ERROR_CODES.COMMERCIAL_ENTITLEMENT_REQUIRED) return 402
  if (code === ERROR_CODES.CREATIVE_POINTS_UNAVAILABLE || code === ERROR_CODES.RATE_CARD_UNAVAILABLE || code === ERROR_CODES.COMMERCIAL_ENTITLEMENT_UNAVAILABLE || code === ERROR_CODES.DATABASE_UNAVAILABLE) return 503
  if (code.endsWith('_NOT_FOUND') || code === ERROR_CODES.RESOURCE_NOT_FOUND || code === ERROR_CODES.JOB_NOT_FOUND) return 404
  if (code === ERROR_CODES.INTERNAL_ERROR) return 500
  if (code === ERROR_CODES.RATE_LIMITED || code === ERROR_CODES.PLATFORM_RATE_LIMITED || code === ERROR_CODES.WORKSPACE_JOB_QUOTA_EXCEEDED) return 429
  return 409
}
