DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'merchant_app') THEN
    CREATE ROLE merchant_app LOGIN PASSWORD 'merchant_app_local_only'
      NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  ELSE
    ALTER ROLE merchant_app LOGIN PASSWORD 'merchant_app_local_only'
      NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
END
$$;

GRANT CONNECT ON DATABASE merchant TO merchant_app;
GRANT USAGE ON SCHEMA public TO merchant_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO merchant_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO merchant_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO merchant_app;

ALTER DEFAULT PRIVILEGES FOR ROLE merchant IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO merchant_app;
ALTER DEFAULT PRIVILEGES FOR ROLE merchant IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO merchant_app;
ALTER DEFAULT PRIVILEGES FOR ROLE merchant IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO merchant_app;
