import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const app = readFileSync(new URL('./App.tsx', import.meta.url), 'utf8')
const api = readFileSync(new URL('./api.ts', import.meta.url), 'utf8')
const css = readFileSync(new URL('./styles.css', import.meta.url), 'utf8')

describe('merchant task conversation visual contract', () => {
  it('exposes progress, confirmation, result, and recovery surfaces', () => {
    expect(app).toContain('data-testid="task-conversation"')
    expect(app).toContain('data-testid="task-confirmation-card"')
    expect(app).toContain('data-testid="task-result-card"')
    expect(app).toContain('<ContextRecoveryCard')
    expect(app).toContain('data-testid="task-create-recovery"')
    expect(app).toContain('创建失败 · 未确认落库')
    expect(app).toContain('用同一请求重试')
    expect(app).toContain('避免重复创建')
    expect(app).toContain('taskCreationUnconfirmed')
    expect(app).toContain('taskContextBlocked')
    expect(app).toContain('{!taskContextBlocked && (')
    expect(app).toContain('<>\n          <section')
    expect(app).toContain('onBackToProducts={() =>')
    expect(app).toContain("navigateTo('products', { clearContext: true })")
    expect(app).toContain('onConnectStores={() =>')
    expect(app).toContain("navigateTo('overview', { clearContext: true })")
    expect(app).toContain("const showAssetLibrary = initialEntry !== 'products'")
    expect(app).toContain('{showAssetLibrary && (')
    expect(app).toContain('<AssetLibrary')
    expect(app).not.toContain("initialEntry={initialEntry === 'products' ? 'assets' : initialEntry}")
    expect(app).toContain('店铺账号已确认')
    expect(app).toContain('平台商品已确认')
    expect(app).not.toContain('远端商品 ${target.remoteId}')
    expect(app).toContain('先连接一个可读取的店铺，再回来同步商品。')
    expect(app).toContain('{task && (')
    expect(app).toContain('data-testid="route-recovery-error"')
    expect(app).toContain('回到商品与素材')
    expect(app).toContain('商品事实已读取')
    expect(app).not.toContain('下方工作区；请只在那里处理当前问题')
    expect(app).not.toContain('· 账号 ${product.accountId}')
    expect(app).toContain('ImageGenerationJobPanel')
    expect(app).toContain('image_job')
    expect(app).toContain('aria-live="polite"')
    expect(app).toContain('刷新任务状态')
    expect(app).toContain('图片候选')
    expect(app).toContain('selectVisualCandidates')
    expect(api).toContain("'content.visual.select'")
    expect(app).toContain('提交选择')
    expect(app).toContain('visual-selection-reason')
    expect(app).toContain('selectedVisualRefs')
    expect(app).toContain('ImageGenerationJobDiscovery')
    expect(app).toContain('图片任务')
    expect(app).toContain('fetchImageGenerationJobs')
    expect(app).toContain('不会自动创建演示任务')
    expect(app).toContain('image-generation-dialog')
    expect(app).toContain('生成图片')
    expect(app).toContain('submitImageGeneration')
    expect(app).toContain('不等于可发布')
    expect(api).toContain("'catalog.image.generate'")
    expect(app).toContain('A terminal read must clear the busy state too')
    expect(app).toContain('aria-busy={loading}')
    expect(app).toContain('const currentJobId = job?.jobId ?? jobId')
    expect(app).toContain('fetchImageGenerationJob(baseUrl, currentJobId)')
  })

  it('keeps the conversation readable in the desktop task layout', () => {
    expect(css).toContain('.task-conversation')
    expect(css).toContain('.conversation-confirm-card')
    expect(css).toContain('.conversation-result-card')
    expect(css).toContain('@media (prefers-reduced-motion: reduce)')
  })

  it('keeps the first-screen conversation to one current question and one primary action', () => {
    expect(app).toContain('understanding.questions.slice(0, 1)')
    expect(app).toContain("understanding ? 'text-button' : 'secondary'")
    expect(app).toContain('className="conversation-message assistant conversation-status-note"')
    expect(app).toContain("question.id === 'confirm_facts' ? (")
    expect(app).toContain("task ? '确认商品事实准确' : '先创建任务再确认事实'")
    expect(app).toContain("task ? '回答并继续' : '先创建任务'")
    expect(app).toContain('先点击下方“确认需求并创建任务”，创建任务后才能回答。')
    expect(app).not.toContain('conversation-confirm-card" data-testid')
    expect(app).not.toContain('conversation-result-card" data-testid')
  })

  it('keeps ambiguous product choices explicit and selectable', () => {
    expect(api).toContain('candidates?: string[]')
    expect(app).toContain('task-product-candidate-')
    expect(app).toContain('setQuestionAnswers')
    expect(app).toContain('不会复用其他平台商品')
  })
})
