import { beforeEach,describe,expect,it,vi } from "vitest";
const rpc=vi.hoisted(()=>vi.fn());
vi.mock("./opsClient.js",()=>({rpc}));
import {platformSupportClient,matchesPlatformReply,supportBodyHash} from "./platformSupportClient.js";
const ticket={id:"ticket-1",workspaceId:"ws-real",ticketNumber:"SUP-001",subject:"购买前入口问题",description:"还没有订单和任务",status:"open",priority:"normal",customerId:"immutable-customer",customerName:"真实客户",tags:[],revision:1,createdBy:"merchant",createdAt:"2026-10-05T02:00:00Z",updatedAt:"2026-10-05T02:00:00Z"};
const event={id:"event-1",workspaceId:"ws-real",ticketId:ticket.id,sequence:2,eventType:"commented" as const,actorId:"support-actor",idempotencyKey:"original-reply-key",payload:{body:"已核实购买入口",visibility:"customer",expectedRevision:1},createdAt:"2026-10-05T03:00:00Z"};
describe("explicit platform support boundary",()=>{
 beforeEach(()=>rpc.mockReset());
 it("lists real first-order handoff with explicit target and bounded pagination",async()=>{rpc.mockResolvedValue({items:[ticket],nextCursor:{id:"ticket-last",createdAt:ticket.createdAt}});const cursor={id:"prior",createdAt:ticket.createdAt};const result=await platformSupportClient.list("ws-real",cursor);expect(result.items[0]?.relatedOrderId).toBeUndefined();expect(rpc.mock.calls[0]?.slice(0,2)).toEqual(["ops.support.platform.tickets.list",{target_workspace_id:"ws-real",limit:"20",cursor_json:JSON.stringify(cursor)}]);});
 it("rejects aggregate, mixed workspace and foreign detail/event projections",async()=>{rpc.mockResolvedValue({items:[{...ticket,workspaceId:"foreign"}]});await expect(platformSupportClient.list("ws-real")).rejects.toThrow("不一致");rpc.mockResolvedValue({items:[{...ticket,aggregate:true,count:2}]});await expect(platformSupportClient.list("ws-real")).rejects.toThrow("不一致");rpc.mockResolvedValue({ticket,events:[{...event,ticketId:"foreign"}]});await expect(platformSupportClient.get("ws-real",ticket.id)).rejects.toThrow("不一致");});
 it("uses platform get without spoofing tenant headers and preserves unavailable detail",async()=>{rpc.mockResolvedValueOnce({ticket,events:[event]}).mockResolvedValueOnce(null);expect((await platformSupportClient.get("ws-real",ticket.id))?.ticket.customerId).toBe("immutable-customer");expect(rpc.mock.calls[0]?.slice(0,2)).toEqual(["ops.support.platform.ticket.get",{target_workspace_id:"ws-real",ticket_id:ticket.id}]);expect(await platformSupportClient.get("ws-real",ticket.id)).toBeUndefined();});
 it("reuses the exact reply key/revision/visibility, never caller-provided actor/workspace headers",async()=>{rpc.mockResolvedValue({ticket:{...ticket,revision:2},event,replayed:true});const input={workspaceId:"ws-real",ticketId:ticket.id,body:event.payload.body,visibility:"customer" as const,expectedRevision:1,idempotencyKey:event.idempotencyKey};expect((await platformSupportClient.comment(input)).replayed).toBe(true);await platformSupportClient.comment(input);expect(rpc.mock.calls[0]?.slice(0,2)).toEqual(["ops.support.platform.ticket.comment",{target_workspace_id:"ws-real",ticket_id:ticket.id,body:event.payload.body,visibility:"customer",expected_revision:"1",idempotency_key:event.idempotencyKey}]);expect(rpc.mock.calls[1]?.[1]).toEqual(rpc.mock.calls[0]?.[1]);});
 it("recovers only the original actor, event key, scope, body digest and visibility",async()=>{const intent={workspaceId:"ws-real",ticketId:ticket.id,actorId:"support-actor",idempotencyKey:event.idempotencyKey,visibility:"customer" as const,expectedRevision:1,bodyHash:await supportBodyHash(event.payload.body)};expect(await matchesPlatformReply(event,intent)).toBe(true);for(const wrong of [{...event,actorId:"other"},{...event,idempotencyKey:"another"},{...event,workspaceId:"other"},{...event,payload:{...event.payload,visibility:"internal"}},{...event,payload:{...event.payload,body:"changed"}},{...event,payload:{...event.payload,expectedRevision:2}}])expect(await matchesPlatformReply(wrong,intent)).toBe(false);});
});
