import type { ThemeConfig } from "antd";

export const opsTheme: ThemeConfig = {
  token: {
    colorPrimary: "#1E40AF",
    colorInfo: "#2563EB",
    colorSuccess: "#15803D",
    colorWarning: "#B45309",
    colorError: "#B91C1C",
    colorText: "#0F172A",
    colorTextSecondary: "#475569",
    colorBgLayout: "#F3F6FB",
    colorBgContainer: "#FFFFFF",
    colorBorder: "#D7E0EE",
    colorBorderSecondary: "#E2E8F0",
    borderRadius: 8,
    borderRadiusLG: 12,
    controlHeight: 36,
    controlHeightSM: 30,
    fontSize: 14,
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    wireframe: false,
  },
  components: {
    Layout: { siderBg: "#132858", headerBg: "#FFFFFF" },
    Button: { controlHeight: 44, controlHeightSM: 36, borderRadius: 8, fontWeight: 600 },
    Input: { controlHeight: 44, activeBorderColor: "#1D4ED8", hoverBorderColor: "#2563EB" },
    Menu: { itemHeight: 42, itemBorderRadius: 8, itemMarginInline: 8 },
    Table: { headerBg: "#F7F9FC", headerColor: "#334155", rowHoverBg: "#EFF6FF", cellPaddingBlockSM: 11 },
    Card: { borderRadiusLG: 12, headerFontSize: 15 },
    Tabs: { itemSelectedColor: "#1E40AF", inkBarColor: "#1E40AF", titleFontSize: 14 },
    Tag: { borderRadiusSM: 999 },
    Drawer: { paddingLG: 24 },
    Modal: { borderRadiusLG: 12 },
  },
};
