#!/bin/sh
set -eu
: "${ECS_ROLLBACK_ENTRYPOINT:?ECS_ROLLBACK_ENTRYPOINT is required}"
: "${ECS_ROLLBACK_PLAN_PATH:?ECS_ROLLBACK_PLAN_PATH is required}"
: "${ECS_ROLLBACK_COMPOSE_PATH:?ECS_ROLLBACK_COMPOSE_PATH is required}"
: "${ECS_ROLLBACK_ENV_FILE:?ECS_ROLLBACK_ENV_FILE is required}"
: "${ECS_ROLLBACK_IMAGE_DIGESTS_JSON:?ECS_ROLLBACK_IMAGE_DIGESTS_JSON is required}"
: "${ECS_ROLLBACK_STATE_PATH:?ECS_ROLLBACK_STATE_PATH is required}"
: "${ECS_DEPLOY_LOCK_PATH:?ECS_DEPLOY_LOCK_PATH is required}"
: "${ECS_COMPOSE_PROJECT:?ECS_COMPOSE_PROJECT is required}"
: "${PRODUCTION_API_BASE_URL:?PRODUCTION_API_BASE_URL is required}"
: "${DATABASE_URL:?DATABASE_URL is required}"
: "${ECS_FAILED_RELEASE_ID:?ECS_FAILED_RELEASE_ID is required}"
exec env CONFIRM_ECS_ROLLBACK=YES \
  ECS_FAILED_RELEASE_ID="$ECS_FAILED_RELEASE_ID" ECS_COMPOSE_PROJECT="$ECS_COMPOSE_PROJECT" ECS_DEPLOY_LOCK_PATH="$ECS_DEPLOY_LOCK_PATH" \
  ECS_ROLLBACK_PLAN_PATH="$ECS_ROLLBACK_PLAN_PATH" ECS_ROLLBACK_COMPOSE_PATH="$ECS_ROLLBACK_COMPOSE_PATH" \
  ECS_ROLLBACK_ENV_FILE="$ECS_ROLLBACK_ENV_FILE" ECS_ROLLBACK_IMAGE_DIGESTS_JSON="$ECS_ROLLBACK_IMAGE_DIGESTS_JSON" \
  ECS_ROLLBACK_STATE_PATH="$ECS_ROLLBACK_STATE_PATH" PRODUCTION_API_BASE_URL="$PRODUCTION_API_BASE_URL" DATABASE_URL="$DATABASE_URL" \
  "$ECS_ROLLBACK_ENTRYPOINT"
