import {expect,test} from '@playwright/test'
import {readFile,mkdir,writeFile} from 'node:fs/promises'
import {join} from 'node:path'
import {randomUUID} from 'node:crypto'
import {openPlatformConsole} from './ops-auth.js'
import {loginCommercialMerchant,readCurrentContract,assertSaleNotice,assertCurrentPlan,assertMerchantPointPack,prepareMerchantPurchase,prepareMerchantFirstCheckoutWithRecovery,confirmMerchantFrozenPayment,closeMerchantCheckout,merchantRpcAction,openMerchantProduct,assertFuturePlans,readMerchantPointStatement} from './commercial-sales-merchant.js'

const required=name=>{const value=process.env[name]?.trim();if(!value)throw new Error(`OWNED_COMMERCIAL_SALES_REQUIRES_${name}`);return value}
if(required('OPS_E2E_COMMERCIAL_SALES')!=='true')throw new Error('OWNED_COMMERCIAL_LEASE_REQUIRED')
for(const field of ['OPS_E2E_COMMERCIAL_CANDIDATE_SHA256','OPS_E2E_COMMERCIAL_SCHEMA_SHA256','OPS_E2E_COMMERCIAL_SOURCE_SHA256'])if(!/^[a-f0-9]{64}$/u.test(required(field)))throw new Error('OWNED_COMMERCIAL_IDENTITY_MISSING')
test.use({channel:'chrome',viewport:{width:1440,height:900},timezoneId:'Asia/Shanghai'})
test.setTimeout(1200000)
const methodOf=request=>{try{return request.postDataJSON()?.method}catch{return null}}
const paramsOf=request=>request.postDataJSON().params
async function rpcBody(response){expect(response.status()).toBe(200);const envelope=await response.json();const body=envelope.data??envelope;expect(body.error,JSON.stringify(body.error)).toBeFalsy();expect(body).toHaveProperty('result');return body.result}
async function rpc(page,method,action){if(method==='ops.commercial.order.preview'||method==='ops.commercial.checkout.preview')await expect(assistant(page).getByRole('button',{name:'读取服务端代购预览',exact:true})).toBeEnabled({timeout:30000});return merchantRpcAction(page,method,action)}
async function openDetails(details){if(await details.getAttribute('open')===null)await details.locator('summary').evaluate(summary=>summary.click())}
async function select(page,control,text,contains=false){await control.scrollIntoViewIfNeeded();await control.click({timeout:10000});await expect(control).toHaveAttribute('aria-expanded','true');let selected=false;const visited=new Set();for(let index=0;index<40;index++){const activeId=await control.getAttribute('aria-activedescendant');if(activeId){if(visited.has(activeId))break;visited.add(activeId);const active=page.locator(`[id=${JSON.stringify(activeId)}]`);const label=await active.getAttribute('aria-label');if(label===text||(contains&&label?.includes(text))){await control.press('Enter');selected=true;break}}await control.press('ArrowDown')}expect(selected,`keyboard navigation must reach registered option ${text}`).toBe(true);await expect(control.locator('xpath=..')).toContainText(text)}
const catalog=page=>page.getByRole('region',{name:'商品目录',exact:true})
const assistant=page=>page.getByRole('region',{name:'指定客户代购',exact:true})
const cash=page=>page.getByRole('region',{name:'指定企业收款与分配',exact:true})
const reason='owned-test isolation: no production approval or external bank transaction'
const money=fen=>`¥${(fen/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`
async function catalogRow(page,code,tab){const region=catalog(page);await region.getByRole('tab',{name:tab,exact:true}).click();await region.getByLabel('搜索商品目录',{exact:true}).fill(code);const row=region.locator('tbody tr').filter({hasText:code});await expect(row).toHaveCount(1);return row}
async function lifecycle(page,code,tab,label){const row=await catalogRow(page,code,tab);await expect(row.getByRole('button',{name:label,exact:true})).toBeEnabled();await row.getByRole('button',{name:label,exact:true}).click();const modal=page.getByRole('dialog',{name:'确认商品变更',exact:true});await modal.getByLabel('操作原因',{exact:true}).fill(reason);const confirm=label==='上架此版本'?'确认上架':`确认${label}`;const result=await rpc(page,'ops.commercial.catalog-v2.mutate',()=>modal.getByRole('button',{name:confirm,exact:true}).click());await expect(modal).toBeHidden();return result}
async function publishDraft(page,code,tab){await lifecycle(page,code,tab,'提交审批');await lifecycle(page,code,tab,'审批通过');return lifecycle(page,code,tab,'上架此版本')}
async function addBenefit(page,modal,label,value){await modal.getByRole('button',{name:'添加已注册权益',exact:true}).click();const row=modal.locator('.commercial-catalog-benefit-row').last();const selector=row.getByRole('combobox');await select(page,selector,label);await expect(row).toContainText(label);await row.getByLabel('数量或功能授权',{exact:true}).fill(String(value));await row.getByLabel('批准政策引用',{exact:true}).fill('owned-test:registered-consumer-policy')}
async function createProduct(page,{code,name,kind,price,rank,family,benefits,windowSeconds=3600}){const tab=kind==='onboarding'?'开通费':kind==='point_pack'?'权益包管理':'套餐管理';await catalog(page).getByRole('tab',{name:tab,exact:true}).click();await catalog(page).getByRole('button',{name:kind==='onboarding'?'新增开通费草稿':kind==='point_pack'?'新增权益包草稿':'新增套餐草稿',exact:true}).click();const modal=page.getByRole('dialog',{name:'新增商品草稿',exact:true});await modal.getByLabel('商品编码（创建后固定）',{exact:true}).fill(code);await modal.getByLabel('商品名称',{exact:true}).fill(name);await modal.getByLabel('人民币价格（元）',{exact:true}).fill(String(price));await modal.getByLabel('已核实政策版本引用',{exact:true}).fill('owned-test:purchase-window-v1');await modal.getByLabel('成功到账窗口（秒）',{exact:true}).fill(String(windowSeconds));if(kind==='monthly'){await modal.getByLabel('套餐系列（创建后身份固定）',{exact:true}).fill(family);await modal.getByLabel('系列内等级（基础1、成长2、尊享3）',{exact:true}).fill(String(rank));await modal.getByLabel('该版本已核实升级政策，支持按剩余有效期补差',{exact:true}).check();await modal.getByLabel('升级政策版本引用',{exact:true}).fill('owned-test:remaining-period-upgrade-v1');expect(benefits,'every tier needs its own declared owned-test-approved configuration').toMatchObject({points:expect.any(Number),brands:expect.any(Number),stores:expect.any(Number)});await addBenefit(page,modal,'每月创意点',benefits.points);await addBenefit(page,modal,'品牌数',benefits.brands);await addBenefit(page,modal,'店铺数',benefits.stores)}else{if(kind==='point_pack')await modal.getByLabel('点数包权益有效期（天，独立于购买周期）',{exact:true}).fill('30');await addBenefit(page,modal,'创意点',kind==='onboarding'?500:1000)}await modal.getByLabel('变更原因',{exact:true}).fill(reason);await rpc(page,'ops.commercial.catalog-v2.mutate',()=>modal.getByRole('button',{name:'保存草稿',exact:true}).click());await expect(modal).toBeHidden();await expect(catalog(page).getByRole('button',{name:'刷新目录',exact:true})).toBeEnabled({timeout:45000});await rpc(page,'ops.commercial.catalog-v2.list',()=>catalog(page).getByRole('button',{name:'刷新目录',exact:true}).click());await expect(await catalogRow(page,code,tab)).toContainText('草稿');return tab}
async function chooseCustomer(page,login){const region=assistant(page);await region.getByLabel('查找代购客户',{exact:true}).fill(login);const rows=await rpc(page,'ops.users.list',()=>region.getByRole('button',{name:'查询真实客户',exact:true}).click());expect(rows).toBeTruthy();const rowSummary=(rows.items??[]).map(row=>({external_subject:row.external_subject??row.externalSubject,workspace_id:row.workspace_id??row.workspaceId,status:row.status,workspace_status:row.workspace_status??row.workspaceStatus}));expect(rowSummary,`ops.users.list must find the fixture merchant; total=${rows.total}; rows=${JSON.stringify(rowSummary)}`).toHaveLength(1);const workspaceId=rows.items[0].workspace_id??rows.items[0].workspaceId;expect(workspaceId).toBeTruthy();const customer=region.getByRole('combobox',{name:'指定客户和企业',exact:true});await customer.click();const dropdown=page.locator('.ant-select-dropdown').filter({visible:true});const options=dropdown.locator('.ant-select-item-option');await expect(options).toHaveCount(1);await expect(options.first()).not.toHaveClass(/ant-select-item-option-disabled/u);await expect(options.first()).toContainText('账号 active / 企业 active');await options.first().click();const scope=page.getByRole('combobox',{name:'代购与收款目标企业主体',exact:true});if(await scope.inputValue().catch(()=>'' )!==workspaceId){await scope.click();await page.getByText(workspaceId,{exact:false}).last().click();}await expect(region).toContainText(`目标企业：${workspaceId}`);await rpc(page,'ops.commercial.catalog-v2.list',()=>region.getByRole('button',{name:'读取当前目录和合同',exact:true}).click())}
async function choosePurchase(page,kind,name,openingName){const region=assistant(page);await select(page,region.getByRole('combobox',{name:'代购购买意图',exact:true}),kind);await select(page,region.getByRole('combobox',{name:'当前上架代购商品',exact:true}),name,true);if(openingName)await select(page,region.getByRole('combobox',{name:'当前上架开通费用',exact:true}),openingName,true);await region.getByLabel('代购操作原因',{exact:true}).fill(reason)}
async function confirmOpsOrder(page,first=false){const region=assistant(page);await region.getByRole('button',{name:first?'确认开通费加首期联合代购':/^确认代购 /u,exact:first}).click();const modal=page.getByRole('dialog',{name:'确认指定客户代购',exact:true});return rpc(page,first?'ops.commercial.checkout.create':'ops.commercial.order.create',()=>modal.getByRole('button',{name:'确认执行',exact:true}).click())}
/** Network fault: forward unchanged real request, validate committed real response, then drop reception. No fulfill/mock result. */
async function loseRealResponse(page,method,action){let captured,requestParams,count=0;const handler=async route=>{if(methodOf(route.request())!==method)return route.continue();count++;requestParams=paramsOf(route.request());const response=await route.fetch();captured=await rpcBody(response);await route.abort('failed')};await page.route('**/api/mcp',handler);try{await action();await expect.poll(()=>count).toBe(1);await expect.poll(()=>Boolean(captured)).toBe(true);return {result:captured,params:requestParams}}finally{await page.unroute('**/api/mcp',handler)}}
async function recordCash(page,fen,sourceOrders){expect(sourceOrders).not.toHaveLength(0);const earliest=Math.max(...sourceOrders.map(order=>Date.parse(order.created_at)));expect(Number.isFinite(earliest)).toBe(true);await expect.poll(()=>Date.now(),{timeout:3000}).toBeGreaterThanOrEqual(earliest);const region=cash(page),trade=`owned-test-bank-${randomUUID()}`;await region.getByRole('button',{name:'读取收款、订单与返款',exact:true}).click();await region.getByLabel('核实收款账户引用',{exact:true}).fill(required('OPS_E2E_COMMERCIAL_RECEIVER'));await region.getByLabel('真实银行流水号',{exact:true}).fill(trade);await region.getByLabel('付款方',{exact:true}).fill('owned-test payer; no external money');await region.getByLabel('实际到账金额（元）',{exact:true}).fill((fen/100).toFixed(2));const latestLegal=Math.floor(Date.now()/60000)*60000;const date=new Date(Math.max(latestLegal,Math.ceil(earliest/60000)*60000));await expect.poll(()=>Date.now(),{timeout:70000}).toBeGreaterThanOrEqual(date.getTime());const local=new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);await region.getByLabel('真实到账时间',{exact:true}).fill(local);await region.getByLabel('核实证据引用',{exact:true}).fill(`owned-test-controlled-bank-fact:${trade}`);await region.getByLabel('收款操作原因',{exact:true}).fill(reason);await region.getByRole('button',{name:'预览到账事实',exact:true}).click();const result=await rpc(page,'ops.commercial.receipt.record',()=>page.getByRole('dialog',{name:'确认核实到账',exact:true}).getByRole('button',{name:'确认核实并记录',exact:true}).click());expect(result.receipt.amountFen).toBe(fen);await select(page,region.getByRole('combobox',{name:'选择真实收款',exact:true}),trade,true);return result.receipt}
async function allocateSingle(page,order){const region=cash(page);await select(page,region.getByRole('combobox',{name:'选择原订单',exact:true}),order.order_id,true);await region.getByLabel('本次分配或返还金额（元）',{exact:true}).fill((order.amount_fen/100).toFixed(2));const preview=await rpc(page,'ops.commercial.receipt.allocation.preview',()=>region.getByRole('button',{name:'读取服务端分配预览',exact:true}).click());expect(preview.amount_fen).toBe(order.amount_fen);await region.getByRole('button',{name:/^确认核验 .*分配以下明细$/u}).click();return rpc(page,'ops.commercial.receipt.allocation.confirm',()=>page.getByRole('dialog',{name:'确认核验并分配',exact:true}).getByRole('button',{name:'确认核实并记录',exact:true}).click())}
async function assertCatalogAbsent(studio,code){const panel=studio.getByRole('region',{name:'套餐与权益包',exact:true});const refresh=panel.getByRole('button',{name:/刷新已购与商品/u});try{await expect(panel).toBeVisible({timeout:15000});await expect(refresh).toBeVisible({timeout:15000});await expect(refresh).toBeEnabled({timeout:15000})}catch(error){const diagnostic=join(required('OPS_E2E_OUTPUT_DIR'),'commercial-sales','merchant-catalog-absence-diagnostic.png');await studio.screenshot({path:diagnostic,fullPage:true}).catch(()=>undefined);const snapshot=await studio.locator('body').ariaSnapshot().catch(()=>'<snapshot unavailable>');await writeFile(join(required('OPS_E2E_OUTPUT_DIR'),'commercial-sales','merchant-catalog-absence-aria.txt'),snapshot,{mode:0o600}).catch(()=>undefined);throw new Error(`MERCHANT_CATALOG_REFRESH_UNAVAILABLE:${code}; url=${studio.url()}; title=${await studio.title().catch(()=>'<closed>')}; ${error.message}`)}const result=await merchantRpcAction(studio,'commercial.catalog.get',()=>refresh.evaluate(button=>button.click()));expect(result.catalog.some(row=>row.code===code)).toBe(false)}


async function merchantCatalog(studio){const refresh=studio.getByRole('region',{name:'套餐与权益包',exact:true}).getByRole('button',{name:/刷新已购与商品/u});await expect(refresh).toBeEnabled();return merchantRpcAction(studio,'commercial.catalog.get',()=>refresh.evaluate(button=>button.click()))}
async function editPriceAndPublish(page,code,tab,priceYuan){const row=await catalogRow(page,code,tab);await row.getByRole('button',{name:'编辑新版本',exact:true}).click();const editor=page.getByRole('dialog',{name:'编辑新版本草稿',exact:true});await editor.getByLabel('人民币价格（元）',{exact:true}).fill(String(priceYuan));await editor.getByLabel('变更原因',{exact:true}).fill(reason);await rpc(page,'ops.commercial.catalog-v2.mutate',()=>editor.getByRole('button',{name:'保存草稿',exact:true}).click());await expect(editor).toBeHidden();return publishDraft(page,code,tab)}
async function assistedPurchase(page,kind,name){await choosePurchase(page,kind,name);const preview=await rpc(page,'ops.commercial.order.preview',()=>assistant(page).getByRole('button',{name:'读取服务端代购预览',exact:true}).click());const order=await confirmOpsOrder(page);expect(order.amount_fen).toBe(preview.amount_fen);expect(order.sku_version_id).toBe(preview.snapshot.version_id);return {order,preview}}
const frozenPeriod=period=>({id:period.id,code:period.skuCode,sourceOrderId:period.sourceOrderId,version:period.catalogVersionId,start:period.periodStart,end:period.periodEnd,benefits:period.resolvedBenefits})
async function assertGiftPlans(studio,openingOrder){const portfolio=await readCurrentContract(studio);expect(portfolio.onboarding_gifts?.status).toBe('available');expect(portfolio.onboarding_gifts.plans).toHaveLength(1);const plan=portfolio.onboarding_gifts.plans[0];expect(plan).toMatchObject({source_order_id:openingOrder.order_id,sku_version_id:openingOrder.sku_version_id,grant_count:6,points_per_grant:500,total_points:3000});expect(plan.batches).toHaveLength(6);expect(plan.batches.map(row=>row.sequence)).toEqual([1,2,3,4,5,6]);expect(plan.batches.filter(row=>row.schedule_status==='granted')).toHaveLength(1);expect(plan.batches.filter(row=>row.schedule_status==='scheduled')).toHaveLength(5);const region=studio.getByRole('region',{name:'开通赠点计划',exact:true});await expect(region).toContainText('6 期 × 每期 500 点');const provenance=region.locator('article > details');await openDetails(provenance);await expect(provenance.locator('p').filter({hasText:openingOrder.sku_version_id})).toBeVisible();const table=region.locator(`[aria-label="开通赠点批次 ${openingOrder.order_id}"]`);const batchRows=table.locator('tbody tr').filter({hasText:/第 [1-6] 期 \/ 500 点/u});await expect(batchRows).toHaveCount(6);for(const batch of plan.batches){const row=table.locator('tbody tr').filter({hasText:batch.schedule_id});const record=row.locator('details');await openDetails(record);await expect(row).toContainText(`第 ${batch.sequence} 期 / 500 点`);await expect(row).toContainText(batch.sequence===1?'已发放':'待按约定发放');expect(Date.parse(batch.expires_at)).toBeGreaterThan(Date.parse(batch.due_at))}return plan}
async function assertFrozenOpeningExplanation(studio,openingOrder){const portfolio=await readCurrentContract(studio);const purchased=portfolio.orders.find(row=>(row.id??row.order_id)===openingOrder.order_id);expect(purchased,'workspace-scoped history must include the Ops-assisted opening order').toBeTruthy();expect(Number(purchased.amountFen??purchased.amount_fen)).toBe(500000);expect(purchased.skuVersionId??purchased.sku_version_id).toBe(openingOrder.sku_version_id);expect(purchased.status).toBe('paid');expect(portfolio.onboarding_gifts.plans[0]).toMatchObject({source_order_id:openingOrder.order_id,sku_version_id:openingOrder.sku_version_id,grant_count:6,points_per_grant:500,total_points:3000});return purchased}
async function assertPointOrigin(studio,entries,order,kind,label,points){const entry=entries.find(row=>row.commercial_origin?.status==='known'&&row.commercial_origin.kind===kind&&row.commercial_origin.source_order_id===order.order_id&&Number(row.pointsDelta)>0);expect(entry,`actual known ${kind} for ${order.order_id}`).toBeTruthy();expect(Number(entry.pointsDelta)).toBe(points);expect(entry.commercial_origin.sku_version_id).toBe(order.sku_version_id);const region=studio.getByRole('region',{name:'创意点来源账本',exact:true});const row=region.locator('tbody tr').filter({hasText:order.order_id});const provenance=row.locator('details');await openDetails(provenance);await expect(row).toContainText(label);await expect(provenance.locator('p').filter({hasText:order.sku_version_id})).toBeVisible();return entry}
const notificationLabels={active:'立即生效',scheduled:'未来待生效',awaiting_dependency:'待开通依赖',reconciliation_required:'待处置'}
async function notificationFor(studio,orderId,state){
  const region=studio.getByRole('region',{name:'套餐与权益包通知',exact:true});const refresh=region.getByRole('button',{name:/刷\s*新/u});if(!await region.isVisible())await studio.locator('.notification-trigger').evaluate(button=>button.click());try{await expect(region).toBeVisible({timeout:10000});await expect(refresh).toBeVisible({timeout:10000});await expect(refresh).toBeEnabled({timeout:30000})}catch(error){const base=join(required('OPS_E2E_OUTPUT_DIR'),'commercial-sales',`notification-open-${state}`);await studio.screenshot({path:`${base}.png`,fullPage:true}).catch(()=>undefined);const details=await studio.evaluate(()=>({url:location.href,title:document.title,body:document.body.innerText.slice(0,5000),trigger:document.querySelector('.notification-trigger')?.outerHTML,dropdowns:[...document.querySelectorAll('.ant-dropdown,.ant-popover,.merchant-all-notifications')].map(node=>({className:node.className,text:node.textContent?.slice(0,1000),display:getComputedStyle(node).display,visibility:getComputedStyle(node).visibility}))})).catch(cause=>({diagnosticError:String(cause)}));await writeFile(`${base}.json`,JSON.stringify({details,aria:await studio.locator('body').ariaSnapshot().catch(()=>'<unavailable>'),failure:error instanceof Error?error.message:String(error)},null,2),{mode:0o600}).catch(()=>undefined);throw error}
  let batch,index=-1;
  await expect.poll(async()=>{batch=await merchantRpcAction(studio,'commercial.notifications.list',()=>refresh.click());expect(batch.next_cursor,'owned scenario must fit the actually loaded page, never imply partial inventory complete').toBeNull();index=batch.items.findIndex(item=>item.notification_kind==='purchase_result'&&item.order_id===orderId&&item.result_state===state);return index},{timeout:30000}).toBeGreaterThanOrEqual(0);
  const item=batch.items[index],row=region.locator('li').nth(index);await expect(region.locator('li')).toHaveCount(batch.items.length);await expect(row).toContainText(item.title);await expect(row).toContainText(`购买结果：${notificationLabels[state]}`);
  return {region,row,item};
}
async function reopenMerchantOrderDetails(studio,orderId){
  const center=studio.getByRole('region',{name:'套餐与权益包',exact:true});
  // A purchase-result notification is only a navigation hint. Reread the
  // server portfolio before searching its order table so newly created sibling
  // checkout lines are present in the recovery view.
  const portfolio=await readCurrentContract(studio);
  expect(portfolio.orders.some(order=>String(order.id??order.order_id)===orderId),`fresh server portfolio should include recovery order ${orderId}`).toBe(true);
  await center.getByRole('tab',{name:'订单与恢复',exact:true}).click();
  const row=center.locator('tbody tr').filter({hasText:orderId});
  await expect(row).toHaveCount(1);
  await row.getByRole('button',{name:'选择查单',exact:true}).click();
  const recoverId=center.getByLabel('原订单 ID',{exact:true}),query=center.getByRole('button',{name:'查询原订单',exact:true});
  await expect(recoverId).toHaveValue(orderId);await expect(query).toBeEnabled();
  const lookup=merchantRpcAction(studio,'commercial.order.payment.get',()=>query.click());
  const detail=center.getByRole('button',{name:'查看原冻结明细与付款',exact:true});
  await expect(detail).toBeVisible();await lookup;
  await detail.click();
  const checkout=studio.getByRole('dialog',{name:'确认服务端订单与付款明细',exact:true});
  await expect(checkout).toBeVisible();
}
async function assertPurchaseNotification(studio,orderId,state){const found=await notificationFor(studio,orderId,state);await found.row.getByRole('button',{name:'查看已购与相关订单',exact:true}).click();const center=studio.getByRole('region',{name:'套餐与权益包',exact:true});await expect(center.getByLabel('原订单 ID',{exact:true})).toHaveValue(orderId);await expect(center.getByRole('tab',{name:'订单与恢复',exact:true})).toHaveAttribute('aria-selected','true');return found.item}
async function assertNotificationReadRecovery(studio,orderId,state){
  const {row,item}=await notificationFor(studio,orderId,state);expect(item.read_at).toBeNull();let committed,originalKey,count=0;
  const pattern=`**/commercial/notifications/${encodeURIComponent(item.id)}/read`;
  const drop=async route=>{count++;const body=route.request().postDataJSON();expect(Object.keys(body)).toEqual(['idempotency_key']);originalKey=body.idempotency_key;const response=await route.fetch();expect(response.status()).toBe(200);const envelope=await response.json();committed=envelope.data??envelope;expect(committed.notification_id).toBe(item.id);expect(Number.isFinite(Date.parse(committed.read_at))).toBe(true);await route.abort('failed')};
  await studio.route(pattern,drop);try{await row.getByRole('button',{name:'标记已读',exact:true}).click();await expect(row.getByRole('alert')).toContainText('已读结果待确认');await expect(row.getByRole('button',{name:'用原标识重试已读登记',exact:true})).toBeEnabled();expect(count).toBe(1)}finally{await studio.unroute(pattern,drop)}
  const responsePromise=studio.waitForResponse(response=>response.request().method()==='POST'&&response.url().endsWith(`/commercial/notifications/${encodeURIComponent(item.id)}/read`));await row.getByRole('button',{name:'用原标识重试已读登记',exact:true}).click();const response=await responsePromise;expect(response.request().postDataJSON()).toEqual({idempotency_key:originalKey});expect(response.status()).toBe(200);const envelope=await response.json(),replay=envelope.data??envelope;expect(replay).toMatchObject({notification_id:item.id,read_at:committed.read_at,replayed:true});await expect(row.getByRole('button',{name:'标记已读',exact:true})).toHaveCount(0);await expect(row).toContainText('已读');
  await studio.reload();await readCurrentContract(studio);const refreshed=await notificationFor(studio,orderId,state);expect(refreshed.item.read_at).toBe(committed.read_at);await expect(refreshed.row.getByRole('button',{name:/标记已读|用原标识重试已读登记/u})).toHaveCount(0);await expect(refreshed.row).toContainText('已读');
  return {notificationId:item.id,orderId,state,originalKey,readAt:committed.read_at,actualWrites:2,replayed:true,persistedAfterReload:true};
}

function giftIdentity(plan){return {order:plan.source_order_id,version:plan.sku_version_id,count:plan.grant_count,points:plan.points_per_grant,total:plan.total_points,batches:plan.batches.map(row=>({id:row.schedule_id,sequence:row.sequence,points:row.points,due:row.due_at,end:row.expires_at,grant:row.grant_id}))}}

test('owned real desktop three tiers, gifts, first checkout, frozen renewal lifecycle, point packs, half-period upgrade and recovery',async({page,browser})=>{
 const out=join(required('OPS_E2E_OUTPUT_DIR'),'commercial-sales');await mkdir(out,{recursive:true});const evidence={scope:'isolated-test-only',productionCandidateVerified:false,externalBankTransfer:false,sourceSha256:required('OPS_E2E_COMMERCIAL_SOURCE_SHA256'),candidateSha256:required('OPS_E2E_COMMERCIAL_CANDIDATE_SHA256'),schemaSha256:required('OPS_E2E_COMMERCIAL_SCHEMA_SHA256'),steps:[]};let studio,historyStudio,pendingStudio;const writes=[];page.on('request',request=>{const method=methodOf(request);if(method?.startsWith('ops.commercial.')&&/\.(create|confirm|record|mutate)$/u.test(method))writes.push({method,params:paramsOf(request)})});
 try{
  await openPlatformConsole(page,'/ops/finance');studio=await loginCommercialMerchant(browser);const fresh=await readCurrentContract(studio);expect(fresh.onboarding_qualified).toBe(false);expect(fresh.current).toBeNull();
  const suffix=randomUUID().replaceAll('-','').slice(0,12),family=`owned-sales-${suffix}`;const opening={code:`qa_open_${suffix}`,name:`QA开通-${suffix}`,kind:'onboarding',price:5000},basic={code:`qa_basic_${suffix}`,name:`QA基础-${suffix}`,kind:'monthly',price:2000,rank:1,family,benefits:{points:5000,brands:1,stores:5}},growth={code:`qa_growth_${suffix}`,name:`QA成长-${suffix}`,kind:'monthly',price:5000,rank:2,family,benefits:{points:12500,brands:2,stores:10}},premium={code:`qa_premium_${suffix}`,name:`QA尊享-${suffix}`,kind:'monthly',price:10000,rank:3,family,benefits:{points:30000,brands:3,stores:20}},pack={code:`qa_points_${suffix}`,name:`QA点数包-${suffix}`,kind:'point_pack',price:100};
  for(const product of [opening,basic,growth,premium,pack]){const tab=await createProduct(page,product);await assertCatalogAbsent(studio,product.code);await lifecycle(page,product.code,tab,'提交审批');await lifecycle(page,product.code,tab,'审批通过');await assertCatalogAbsent(studio,product.code);await lifecycle(page,product.code,tab,'上架此版本');evidence.steps.push({step:'publish',code:product.code,policyScope:'owned-test',priceFen:product.price*100,...(product.benefits?{independentTierBenefits:product.benefits}:{})})}
  // Real signed worker controller drains actual outbox every lease renewal. No manufactured notice.
  await expect.poll(async()=>{const path=join(required('OPS_E2E_OUTPUT_DIR'),'owned-commercial-lease','notification-worker-progress.jsonl');try{return (await readFile(path,'utf8')).split('\n').filter(Boolean).map(line=>JSON.parse(line)).reduce((sum,row)=>sum+row.delivered,0)}catch{return 0}},{timeout:30000}).toBeGreaterThan(0);
  const noticeRegion=studio.getByRole('region',{name:'套餐与权益包通知',exact:true});const publicationBatch=await merchantRpcAction(studio,'commercial.notifications.list',()=>studio.locator('.notification-trigger').click());await expect(noticeRegion,`merchant notification dropdown must open: ${(await studio.locator('body').innerText()).slice(0,1400)}`).toBeVisible({timeout:3000});expect(publicationBatch.items.some(row=>row.sku_code===basic.code)).toBe(true);await assertSaleNotice(studio,basic,publicationBatch);await page.screenshot({path:join(out,'01-published-ops.png'),fullPage:true});await studio.screenshot({path:join(out,'02-real-notice.png'),fullPage:true});
  await chooseCustomer(page,required('OPS_E2E_MERCHANT_USERNAME'));await choosePurchase(page,'首购：开通费加首期',basic.name,opening.name);const preview=await rpc(page,'ops.commercial.checkout.preview',()=>assistant(page).getByRole('button',{name:'读取服务端代购预览',exact:true}).click());expect(preview.amount_fen).toBe(700000);expect(preview.lines.map(line=>line.amount_fen)).toEqual([500000,200000]);expect(preview.onboarding_qualified).toBe(false);expect((await readCurrentContract(studio)).current).toBeNull();
  const lost=await loseRealResponse(page,'ops.commercial.checkout.create',()=>confirmOpsOrder(page,true).catch(()=>undefined));await expect(assistant(page).getByRole('button',{name:'查询原请求结果',exact:true})).toBeEnabled();const recoveryRequest=page.waitForRequest(request=>methodOf(request)==='ops.commercial.checkout.request.get');const recovered=await rpc(page,'ops.commercial.checkout.request.get',()=>assistant(page).getByRole('button',{name:'查询原请求结果',exact:true}).click());expect(paramsOf(await recoveryRequest).idempotency_key).toBe(lost.params.idempotency_key);expect(recovered.orders.map(row=>row.order_id)).toEqual(lost.result.orders.map(row=>row.order_id));expect(writes.filter(row=>row.method==='ops.commercial.checkout.create')).toHaveLength(1);const orders=recovered.orders;expect(orders).toHaveLength(2);expect(orders.map(row=>row.amount_fen)).toEqual([500000,200000]);expect((await readCurrentContract(studio)).onboarding_qualified).toBe(false);
  const receipt=await recordCash(page,700000,orders);const before=await readCurrentContract(studio);expect(before.onboarding_qualified).toBe(false);expect(before.current).toBeNull();for(const order of orders){await select(page,cash(page).getByRole('combobox',{name:'选择原订单',exact:true}),order.order_id,true);await cash(page).getByLabel('本次分配或返还金额（元）',{exact:true}).fill((order.amount_fen/100).toFixed(2));await cash(page).getByRole('button',{name:'加入联合分配明细',exact:true}).click()}
  const allocationPreview=await rpc(page,'ops.commercial.receipt.allocations.preview',()=>cash(page).getByRole('button',{name:'读取服务器联合分配预览',exact:true}).click());expect(allocationPreview.items).toHaveLength(2);await cash(page).getByRole('button',{name:'确认核实并联合分配全部明细',exact:true}).click();const allocated=await rpc(page,'ops.commercial.receipt.allocations.confirm',()=>page.getByRole('dialog',{name:'确认联合分配全部明细',exact:true}).getByRole('button',{name:'确认核实并记录',exact:true}).click());expect(allocated.allocations).toHaveLength(2);await assertCurrentPlan(studio,{code:basic.code,name:basic.name,priceFen:200000});const current=await readCurrentContract(studio);expect(current.onboarding_qualified).toBe(true);expect(current.future).toHaveLength(0);evidence.steps.push({step:'first-checkout-atomic-allocation',checkoutId:recovered.checkout_id,orderIds:orders.map(row=>row.order_id),receiptId:receipt.id,amountFen:700000,networkRecovery:{originalKey:lost.params.idempotency_key,writeCount:1}});await studio.screenshot({path:join(out,'03-current-first-plan.png'),fullPage:true});
  const openingOrder=orders.find(row=>row.purchase_kind==='onboarding_once'),firstPlanOrder=orders.find(row=>row.purchase_kind==='purchase');expect(openingOrder).toBeTruthy();expect(firstPlanOrder).toBeTruthy();const firstGift=await assertGiftPlans(studio,openingOrder);await assertFrozenOpeningExplanation(studio,openingOrder);const issued=await readMerchantPointStatement(studio);await assertPointOrigin(studio,issued,openingOrder,'onboarding_gift','开通赠点',500);await assertPointOrigin(studio,issued,firstPlanOrder,'subscription_points','套餐点数',5000);evidence.steps.push({step:'frozen-six-gift-plan-and-separate-origin-ui',giftIdentity:giftIdentity(firstGift),currentlyGrantedBatches:1,futureBatches:5});await studio.screenshot({path:join(out,'04-six-batch-gift-and-origins.png'),fullPage:true});
  // Merchant really creates its point-pack order and receives manual instructions; Ops verifies the declared fixture bank fact.
  const packPurchase=await prepareMerchantPurchase(studio,{code:pack.code,action:'购买权益包'});expect(packPurchase.orders[0].amount_fen).toBe(10000);await confirmMerchantFrozenPayment(studio,packPurchase.orders);await closeMerchantCheckout(studio);await recordCash(page,10000,packPurchase.orders);await allocateSingle(page,packPurchase.orders[0]);const packs=await assertMerchantPointPack(studio,{code:pack.code,name:pack.name});expect(packs).toHaveLength(1);evidence.steps.push({step:'merchant-point-pack',orderId:packPurchase.orders[0].order_id,pack:packs[0]});
  const packEntries=await readMerchantPointStatement(studio);await assertPointOrigin(studio,packEntries,packPurchase.orders[0],'point_pack','权益包点数',1000);
  // All three prices are versioned independently; prior gift/pack sources remain frozen.
  await editPriceAndPublish(page,opening.code,'开通费',5500);await editPriceAndPublish(page,pack.code,'权益包管理',120);const repriced=await merchantCatalog(studio);expect(repriced.catalog.find(row=>row.code===opening.code).priceFen).toBe(550000);expect(repriced.catalog.find(row=>row.code===pack.code).priceFen).toBe(12000);const premiumCatalog=repriced.catalog.find(row=>row.code===premium.code);expect(premiumCatalog).toMatchObject({priceFen:1000000,kind:'monthly',payload:{planFamily:family,tierRank:3}});for(const [code,quantity] of [['monthly_creative_points',30000],['max_brands',3],['max_stores',20]])expect(premiumCatalog.benefits.find(row=>row.code===code).quantity).toBe(quantity);expect(giftIdentity(await assertGiftPlans(studio,openingOrder))).toEqual(giftIdentity(firstGift));await assertFrozenOpeningExplanation(studio,openingOrder);
  await choosePurchase(page,'首购：开通费加首期',basic.name,opening.name);const repeatOpening=await rpc(page,'ops.commercial.checkout.preview',()=>assistant(page).getByRole('button',{name:'读取服务端代购预览',exact:true}).click());expect(repeatOpening.onboarding_qualified).toBe(true);expect(repeatOpening.amount_fen).toBe(750000);await expect(assistant(page).getByRole('button',{name:'确认开通费加首期联合代购',exact:true})).toBeDisabled();
  const secondPack=await prepareMerchantPurchase(studio,{code:pack.code,action:'购买权益包'});expect(secondPack.orders[0].amount_fen).toBe(12000);expect(secondPack.orders[0].sku_version_id).not.toBe(packPurchase.orders[0].sku_version_id);await confirmMerchantFrozenPayment(studio,secondPack.orders);await closeMerchantCheckout(studio);await recordCash(page,12000,secondPack.orders);await allocateSingle(page,secondPack.orders[0]);const bothPacks=await assertMerchantPointPack(studio,{code:pack.code,name:pack.name});expect(bothPacks).toHaveLength(2);expect(bothPacks.find(row=>row.orderId===packPurchase.orders[0].order_id).expiresAt).toBe(packs[0].expiresAt);evidence.steps.push({step:'independent-opening-and-pack-price-change',newOpeningFen:550000,newPackFen:12000,oldOpeningFen:500000,oldPackFen:10000,oldGiftPreserved:true,oldPackExpiry:packs[0].expiresAt});
  // Pending renewal locks 2000. Down-sale and later archive cannot cancel its valid payment window or move current/future contracts.
  const authority=await readCurrentContract(studio),originalCurrent=frozenPeriod(authority.current);const renew1=await assistedPurchase(page,'续购套餐',basic.name);expect(renew1.order.amount_fen).toBe(200000);expect(renew1.order.purchase_kind).toBe('renewal');await editPriceAndPublish(page,basic.code,'套餐管理',2200);await lifecycle(page,basic.code,'套餐管理','下架');await assertCatalogAbsent(studio,basic.code);expect(frozenPeriod((await readCurrentContract(studio)).current)).toEqual(originalCurrent);await recordCash(page,renew1.order.amount_fen,[renew1.order]);await allocateSingle(page,renew1.order);const afterRenew1=await readCurrentContract(studio);expect(frozenPeriod(afterRenew1.current)).toEqual(originalCurrent);const future1=await assertFuturePlans(studio,{expectedCount:1,codes:[basic.code]});expect(future1[0].sourceOrderId).toBe(renew1.order.order_id);expect(future1[0].catalogVersionId).toBe(renew1.order.sku_version_id);expect(future1[0].periodStart).toBe(originalCurrent.end);expect(Date.parse(future1[0].periodStart)).toBeGreaterThan(Date.now());const futureOne=frozenPeriod(future1[0]);
  await editPriceAndPublish(page,basic.code,'套餐管理',2200);const resold=await merchantCatalog(studio);expect(resold.catalog.find(row=>row.code===basic.code).priceFen).toBe(220000);const renew2=await assistedPurchase(page,'续购套餐',basic.name);expect(renew2.order.amount_fen).toBe(220000);expect(renew2.order.sku_version_id).not.toBe(renew1.order.sku_version_id);await lifecycle(page,basic.code,'套餐管理','下架');await lifecycle(page,basic.code,'套餐管理','归档');await assertCatalogAbsent(studio,basic.code);const archivedRow=await catalogRow(page,basic.code,'套餐管理');await expect(archivedRow).toContainText('已归档');await expect(archivedRow.getByRole('button',{name:'编辑新版本',exact:true})).toBeDisabled();await expect(archivedRow.getByRole('button',{name:'上架此版本',exact:true})).toHaveCount(0);await expect(archivedRow.getByRole('button',{name:'下架',exact:true})).toBeDisabled();const awaitingRenew2=await readCurrentContract(studio);expect(frozenPeriod(awaitingRenew2.current)).toEqual(originalCurrent);expect(awaitingRenew2.future.map(frozenPeriod)).toEqual([futureOne]);await recordCash(page,renew2.order.amount_fen,[renew2.order]);await allocateSingle(page,renew2.order);const twoFuture=await assertFuturePlans(studio,{expectedCount:2,codes:[basic.code]});const futureRows=studio.locator('[aria-label="未来待生效套餐"] tbody tr');await expect(futureRows).toHaveCount(3);await expect(futureRows.nth(1)).toContainText(renew1.order.order_id);await expect(futureRows.nth(2)).toContainText(renew2.order.order_id);expect(frozenPeriod(twoFuture[0])).toEqual(futureOne);expect(twoFuture[1].periodStart).toBe(twoFuture[0].periodEnd);expect(twoFuture[1].sourceOrderId).toBe(renew2.order.order_id);expect(twoFuture[1].catalogVersionId).toBe(renew2.order.sku_version_id);await studio.screenshot({path:join(out,'05-future-contracts-after-archive.png'),fullPage:true});await assertCurrentPlan(studio,{code:basic.code,periodEnd:originalCurrent.end,priceFen:200000});const noEarlyGrants=await readMerchantPointStatement(studio);expect(noEarlyGrants.filter(row=>([renew1.order.order_id,renew2.order.order_id].includes(row.commercial_origin?.source_order_id)||[renew1.order.order_id,renew2.order.order_id].includes(row.grantSourceId))&&Number(row.pointsDelta)>0)).toHaveLength(0);evidence.steps.push({step:'renewal-current-future-partitions-and-sale-lifecycle',current:originalCurrent,future:twoFuture.map(frozenPeriod),oldRenewFen:200000,newRenewFen:220000,offSaleOldOrderHonored:true,archivedOldOrderHonored:true,futurePositiveGrants:0});await studio.screenshot({path:join(out,'05-current-future-after-archive.png'),fullPage:true});
  // Independent owned-test premium approval is exercised by a real upgrade; paid future basic contracts retain original tier and dates.
  await choosePurchase(page,'按剩余有效期升级',premium.name);const premiumQuote=await rpc(page,'ops.commercial.upgrade.quote.create',()=>assistant(page).getByRole('button',{name:'读取服务器冻结升级报价',exact:true}).click());expect(premiumQuote.target_cycle_price_fen).toBe(1000000);expect(premiumQuote.period_end).toBe(originalCurrent.end);await rpc(page,'ops.commercial.order.preview',()=>assistant(page).getByRole('button',{name:'读取服务端代购预览',exact:true}).click());const premiumOrder=await confirmOpsOrder(page);expect(premiumOrder.amount_fen).toBe(premiumQuote.amount_fen);await recordCash(page,premiumOrder.amount_fen,[premiumOrder]);await allocateSingle(page,premiumOrder);await assertCurrentPlan(studio,{code:premium.code,periodEnd:originalCurrent.end});const premiumPortfolio=await readCurrentContract(studio);expect(premiumPortfolio.current.catalogVersionId).toBe(premiumOrder.sku_version_id);for(const [code,quantity] of [['monthly_creative_points',30000],['max_brands',3],['max_stores',20]])expect(premiumPortfolio.current.resolvedBenefits.find(row=>row.code===code).quantity).toBe(quantity);expect(premiumPortfolio.future.map(frozenPeriod)).toEqual(twoFuture.map(frozenPeriod));expect(giftIdentity(await assertGiftPlans(studio,openingOrder))).toEqual(giftIdentity(firstGift));evidence.steps.push({step:'independent-premium-approved-configuration-and-upgrade',scope:'owned-test-not-production-pricing-policy',targetPriceFen:1000000,approvedBenefits:premium.benefits,orderId:premiumOrder.order_id,quoteAmountFen:premiumQuote.amount_fen,periodEndUnchanged:originalCurrent.end,futureSourceOrdersUnchanged:twoFuture.map(row=>row.sourceOrderId)});
  const history=JSON.parse(await readFile(required('OPS_E2E_COMMERCIAL_HISTORY_FIXTURE'),'utf8'));expect(history.scope).toBe('owned-test-historical-seed');expect(history.immutableDatesUpdated).toBe(false);expect(history.remainingFraction).toBeGreaterThan(0.4);expect(history.remainingFraction).toBeLessThan(0.6);historyStudio=await loginCommercialMerchant(browser,{username:required('OPS_E2E_HISTORY_MERCHANT_USERNAME'),password:required('OPS_E2E_HISTORY_MERCHANT_PASSWORD')});const prior=await readCurrentContract(historyStudio);expect(prior.current.periodEnd).toBe(history.periodEnd);await chooseCustomer(page,required('OPS_E2E_HISTORY_MERCHANT_USERNAME'));await choosePurchase(page,'按剩余有效期升级',history.growthName);const quote=await rpc(page,'ops.commercial.upgrade.quote.create',()=>assistant(page).getByRole('button',{name:'读取服务器冻结升级报价',exact:true}).click());expect(quote.period_end).toBe(history.periodEnd);expect(quote.current_cycle_price_fen).toBe(200000);expect(quote.target_cycle_price_fen).toBe(500000);const numerator=BigInt(300000)*BigInt(quote.remaining_ms),denominator=BigInt(quote.total_ms);expect(quote.amount_fen).toBe(Number((2n*numerator+denominator)/(2n*denominator)));
  // Change directory price AFTER quote, through actual create/submit/approve/publish. Keep original quote in assistant.
  const historyRow=await catalogRow(page,history.growthCode,'套餐管理');await historyRow.getByRole('button',{name:'编辑新版本',exact:true}).click();const editor=page.getByRole('dialog',{name:'编辑新版本草稿',exact:true});await editor.getByLabel('人民币价格（元）',{exact:true}).fill('6000');await editor.getByLabel('变更原因',{exact:true}).fill(reason);await rpc(page,'ops.commercial.catalog-v2.mutate',()=>editor.getByRole('button',{name:'保存草稿',exact:true}).click());await publishDraft(page,history.growthCode,'套餐管理');const upgradePreview=await rpc(page,'ops.commercial.order.preview',()=>assistant(page).getByRole('button',{name:'读取服务端代购预览',exact:true}).click());expect(upgradePreview.amount_fen).toBe(quote.amount_fen);const upgrade=await confirmOpsOrder(page);expect(upgrade.amount_fen).toBe(quote.amount_fen);expect(upgrade.sku_version_id).toBe(upgradePreview.snapshot.version_id);
  // A fresh merchant quote observes 6000; the already quoted order remains at old frozen amount/version.
  await readCurrentContract(historyStudio);const quoteDialog=await openMerchantProduct(historyStudio,{code:history.growthCode,action:'计算升级差价'});const nextQuote=await merchantRpcAction(historyStudio,'commercial.upgrade.quote.create',()=>quoteDialog.getByRole('button',{name:'计算剩余期差价',exact:true}).click());expect(nextQuote.target_cycle_price_fen).toBe(600000);expect(nextQuote.amount_fen).toBeGreaterThan(quote.amount_fen);expect(nextQuote.period_end).toBe(history.periodEnd);await closeMerchantCheckout(historyStudio);await recordCash(page,upgrade.amount_fen,[upgrade]);await allocateSingle(page,upgrade);const upgraded=await readCurrentContract(historyStudio);expect(upgraded.current.skuCode).toBe(history.growthCode);expect(upgraded.current.periodEnd).toBe(history.periodEnd);expect(upgraded.current.sourceOrderId).toBe(history.sourceOrderId);const frozenPaid=upgraded.orders.find(row=>(row.id??row.order_id)===upgrade.order_id);expect(frozenPaid).toBeTruthy();expect(frozenPaid.amountFen??frozenPaid.amount_fen).toBe(quote.amount_fen);evidence.steps.push({step:'half-period-upgrade-frozen-quote',historyWorkspace:history.workspaceId,originalEnd:history.periodEnd,oldQuote:quote,changedCatalogPriceFen:600000,newQuote:nextQuote,paidOrder:upgrade.order_id});await historyStudio.screenshot({path:join(out,'04-upgrade-preserves-end.png'),fullPage:true});

  // A genuinely self-activated third merchant has no commercial qualification. Pay only the dependent monthly line, never fabricate its state.
  pendingStudio=await loginCommercialMerchant(browser,{username:required('OPS_E2E_PENDING_MERCHANT_USERNAME'),password:required('OPS_E2E_PENDING_MERCHANT_PASSWORD')});expect((await readCurrentContract(pendingStudio)).onboarding_qualified).toBe(false);
  // Merchant creates a genuine split first checkout. Lose only the browser response,
  // recover the same two lines by original idempotency key, then settle one line.
  const partialCheckout=await prepareMerchantFirstCheckoutWithRecovery(pendingStudio,{code:premium.code});const openingLine=partialCheckout.orders.find(order=>order.purchase_kind==='onboarding_once'),subscriptionLine=partialCheckout.orders.find(order=>order.purchase_kind==='purchase');expect(openingLine).toBeTruthy();expect(subscriptionLine).toBeTruthy();expect(partialCheckout.writeCount).toBe(1);expect(partialCheckout.original.orders.map(order=>order.order_id)).toEqual(partialCheckout.result.orders.map(order=>order.order_id));await confirmMerchantFrozenPayment(pendingStudio,partialCheckout.orders);await closeMerchantCheckout(pendingStudio);
  await chooseCustomer(page,required('OPS_E2E_PENDING_MERCHANT_USERNAME'));await recordCash(page,subscriptionLine.amount_fen,[subscriptionLine]);await allocateSingle(page,subscriptionLine);const awaitingDependency=await readCurrentContract(pendingStudio);expect(awaitingDependency.onboarding_qualified).toBe(false);expect(awaitingDependency.current).toBeNull();expect(awaitingDependency.future).toHaveLength(0);const dependencyNotice=await assertPurchaseNotification(pendingStudio,subscriptionLine.order_id,'awaiting_dependency');
  await reopenMerchantOrderDetails(pendingStudio,openingLine.order_id);const partialDialog=pendingStudio.getByRole('dialog',{name:'确认服务端订单与付款明细',exact:true});await expect(partialDialog).toContainText('待付款');await expect(partialDialog.getByRole('button',{name:`确认待付款分项 ${money(openingLine.amount_fen)}`,exact:true})).toBeEnabled();await confirmMerchantFrozenPayment(pendingStudio,[openingLine]);await expect(partialDialog.locator('.commercial-payment')).toHaveCount(1);await expect(partialDialog).toContainText(money(openingLine.amount_fen));await closeMerchantCheckout(pendingStudio);
  await recordCash(page,openingLine.amount_fen,[openingLine]);await allocateSingle(page,openingLine);const completedPartialCheckout=await readCurrentContract(pendingStudio);expect(completedPartialCheckout.onboarding_qualified).toBe(true);expect(completedPartialCheckout.current?.skuCode).toBe(premium.code);expect(completedPartialCheckout.future).toHaveLength(0);evidence.steps.push({step:'merchant-partial-first-checkout-recovery-and-remaining-line',workspaceId:required('OPS_E2E_PENDING_WORKSPACE_ID'),checkoutId:partialCheckout.result.checkout_id,originalRequestRecovered:true,writeCount:partialCheckout.writeCount,originalOrderIds:partialCheckout.original.orders.map(order=>order.order_id),paidFirstLine:subscriptionLine.order_id,paidFirstLineIntermediateState:'awaiting_dependency',remainingLine:openingLine.order_id,remainingLineIntermediateState:'pending',remainingAmountFen:openingLine.amount_fen,onlyRemainingLineReconfirmed:true,remainingPaymentCards:1,dependencyNotificationId:dependencyNotice.id,finalCurrentSku:completedPartialCheckout.current.skuCode});
  // Actual elapsed wall time crosses a separately approved short purchase window; capture real late cash through Ops, without modifying dates or bypassing UI.
  await chooseCustomer(page,required('OPS_E2E_MERCHANT_USERNAME'));const latePack={code:`qa_late_${suffix}`,name:`QA迟到款-${suffix}`,kind:'point_pack',price:10,windowSeconds:2};await createProduct(page,latePack);await publishDraft(page,latePack.code,'权益包管理');const latePurchase=await assistedPurchase(page,'购买点数权益包',latePack.name),lateOrder=latePurchase.order;expect(Number.isFinite(Date.parse(lateOrder.expires_at))).toBe(true);await expect.poll(()=>Date.now(),{timeout:10000}).toBeGreaterThan(Date.parse(lateOrder.expires_at));await recordCash(page,lateOrder.amount_fen,[lateOrder]);await allocateSingle(page,lateOrder);const afterLate=await readCurrentContract(studio);expect(afterLate.packs.some(pack=>pack.orderId===lateOrder.order_id)).toBe(false);const lateLedger=await readMerchantPointStatement(studio);expect(lateLedger.some(row=>row.commercial_origin?.source_order_id===lateOrder.order_id&&Number(row.pointsDelta)>0)).toBe(false);
  const activeNotice=await assertPurchaseNotification(studio,firstPlanOrder.order_id,'active'),scheduledNotice=await assertPurchaseNotification(studio,renew1.order.order_id,'scheduled'),reconciliationNotice=await assertPurchaseNotification(studio,lateOrder.order_id,'reconciliation_required');await assertPurchaseNotification(historyStudio,upgrade.order_id,'active');const readRecovery=await assertNotificationReadRecovery(studio,renew1.order.order_id,'scheduled');evidence.steps.push({step:'real-four-state-result-notifications-and-read-recovery',active:activeNotice.id,scheduled:scheduledNotice.id,awaitingDependency:dependencyNotice.id,reconciliationRequired:reconciliationNotice.id,lateOrder:lateOrder.order_id,lateExpiry:lateOrder.expires_at,readRecovery});await studio.screenshot({path:join(out,'08-result-notifications-persisted-read.png'),fullPage:true});await pendingStudio.screenshot({path:join(out,'09-real-awaiting-opening.png'),fullPage:true});
  evidence.status='passed-owned-isolated-only';await writeFile(join(out,'evidence.json'),JSON.stringify(evidence,null,2),{mode:0o600});
 }catch(error){evidence.status='failed';evidence.failure=error instanceof Error?error.message:'unknown';await writeFile(join(out,'evidence.json'),JSON.stringify(evidence,null,2),{mode:0o600});throw error}finally{await studio?.context().close();await historyStudio?.context().close();await pendingStudio?.context().close()}
})
