import { expect, test, chromium } from '@playwright/test'
import { mkdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

test.setTimeout(90_000)
const baseUrl = process.env.OPS_BASE_URL ?? 'http://127.0.0.1:18082/'

test('operates the platform user directory without destructive confirmation', async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true })
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } })
  await context.addInitScript(() => {
    localStorage.setItem('ops_workspace_id', 'ws_demo')
    localStorage.setItem('ops_actor_id', 'actor_demo')
    localStorage.setItem('ops_api_token', 'pilot-local-token')
  })
  const page = await context.newPage()
  const errors = []
  const badResponses = []
  const routeRequests = []
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  page.on('pageerror', error => errors.push(error.message))
  page.on('response', response => { if (response.status() >= 400) badResponses.push({ status: response.status(), url: response.url() }) })
  page.on('request', request => { if (/UsersPage|UserDirectory/u.test(request.url())) routeRequests.push({ event: 'request', url: request.url() }) })
  page.on('requestfinished', request => { if (/UsersPage|UserDirectory/u.test(request.url())) routeRequests.push({ event: 'finished', url: request.url() }) })
  await page.goto(baseUrl, { waitUntil: 'domcontentloaded' })
  await page.waitForTimeout(5_000)
  await page.locator('button').filter({ hasText: /^用户与租户$/u }).click()
  await expect(page).toHaveURL(/\/ops\/users$/u)
  await page.waitForTimeout(2_000)
  if (await page.getByRole('heading', { name: '用户与租户' }).count() === 0) throw new Error(JSON.stringify({ errors, badResponses, routeRequests }))
  await expect(page.getByRole('heading', { name: '用户与租户' })).toBeVisible()
  await expect(page.getByText('本地演示平台运营').first()).toBeVisible()
  await expect(page.getByText('当前租户成员')).toBeVisible()

  const supportRow = page.getByRole('row').filter({ hasText: 'support_demo' }).first()
  const detailButton = supportRow.getByRole('button', { name: /详\s*情/u })
  await detailButton.focus()
  await page.keyboard.press('Enter')
  const detailDrawer = page.getByRole('dialog', { name: /用户详情.*support_demo/u })
  await expect(detailDrawer).toBeVisible()
  await expect(detailDrawer.getByText('认证会话（已脱敏）')).toBeVisible()
  await expect(detailDrawer.getByText('平台身份生命周期')).toBeVisible()
  await expect(detailDrawer.getByText('所属租户与角色')).toBeVisible()
  await expect(detailDrawer.getByText('暂无成员操作记录')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(detailDrawer).toBeHidden()
  await expect(detailButton).toBeFocused()

  const keyword = page.getByPlaceholder('身份、姓名、角色或工作区')
  await keyword.fill('不存在的用户')
  await page.getByRole('button', { name: /查\s*询/u }).click()
  await expect(page.getByText('没有符合条件的用户成员关系')).toBeVisible()
  await page.getByRole('button', { name: /清\s*空/u }).click()
  await expect(page.getByText('本地演示平台运营').first()).toBeVisible()

  await page.locator('button:not([disabled])').filter({ hasText: /^停\s*用$/u }).click()
  const dialog = page.getByRole('dialog', { name: '停用用户访问' })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('button', { name: /确认停用/u })).toBeDisabled()
  await dialog.getByLabel('操作原因（至少 4 个字符）').fill('浏览器验收测试，不提交')
  await expect(dialog.getByRole('button', { name: /确认停用/u })).toBeEnabled()
  await dialog.getByRole('button', { name: /Cancel|取\s*消/u }).click()
  await expect(dialog).toBeHidden()

  const shots = resolve('screenshots', 'ops-users')
  await mkdir(shots, { recursive: true })
  await page.screenshot({ path: resolve(shots, 'user-directory.png'), fullPage: true })
  await writeFile('ops-users-result.json', JSON.stringify({ errors, url: page.url(), rows: await page.locator('tbody tr').count() }, null, 2))
  expect(errors).toEqual([])
  await context.close()
  await browser.close()
})

test('keeps the user directory usable at 390px', async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true })
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true })
  await context.addInitScript(() => {
    localStorage.setItem('ops_workspace_id', 'ws_demo')
    localStorage.setItem('ops_actor_id', 'actor_demo')
    localStorage.setItem('ops_api_token', 'pilot-local-token')
  })
  const page = await context.newPage()
  await page.goto(new URL('/ops/users', baseUrl).toString(), { waitUntil: 'domcontentloaded' })
  await expect(page.getByRole('heading', { name: '用户与租户' })).toBeVisible({ timeout: 15_000 })
  await expect(page.getByText('本地演示支持专员').first()).toBeVisible({ timeout: 15_000 })
  const viewportOverflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)
  const overflowing = await page.evaluate(() => [...document.querySelectorAll('body *')].flatMap(element => {
    const rect = element.getBoundingClientRect()
    return rect.right > window.innerWidth + 1 ? [{ tag: element.tagName, className: element.className, right: Math.round(rect.right), width: Math.round(rect.width) }] : []
  }).slice(0, 12))
  if (viewportOverflow > 1) throw new Error(JSON.stringify({ viewportOverflow, overflowing }))
  await expect(page.locator('.ant-table-body, .ant-table-content').first()).toBeVisible()
  const shots = resolve('screenshots', 'ops-users')
  await mkdir(shots, { recursive: true })
  await page.screenshot({ path: resolve(shots, 'user-directory-mobile-390.png'), fullPage: true })
  await context.close()
  await browser.close()
})

test('keeps the user directory usable at 375px portrait and phone landscape', async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true })
  const context = await browser.newContext({ viewport: { width: 375, height: 812 }, isMobile: true })
  await context.addInitScript(() => {
    localStorage.setItem('ops_workspace_id', 'ws_demo')
    localStorage.setItem('ops_actor_id', 'actor_demo')
    localStorage.setItem('ops_api_token', 'pilot-local-token')
  })
  const page = await context.newPage()
  await page.goto(new URL('/ops/users', baseUrl).toString(), { waitUntil: 'domcontentloaded' })
  await expect(page.getByText('本地演示支持专员').first()).toBeVisible({ timeout: 15_000 })
  const menuTrigger = page.getByRole('button', { name: '打开运营导航' })
  await expect(menuTrigger).toBeVisible()
  await menuTrigger.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: '总览' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(menuTrigger).toBeFocused()
  await page.getByRole('button', { name: '保存成员' }).click()
  await expect(page.getByRole('textbox', { name: /用户 ID/u })).toBeFocused()
  for (const viewport of [{ width: 375, height: 812, name: '375-portrait' }, { width: 844, height: 390, name: '844-landscape' }]) {
    await page.setViewportSize({ width: viewport.width, height: viewport.height })
    expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
    await expect(page.locator('.ant-table-content').first()).toBeVisible()
    const shots = resolve('screenshots', 'ops-users')
    await mkdir(shots, { recursive: true })
    await page.screenshot({ path: resolve(shots, `user-directory-${viewport.name}.png`), fullPage: true })
  }
  await context.close()
  await browser.close()
})
