import { Alert, Button, Card, Descriptions, Input, Select, Space, Table, Tag, Timeline, Typography } from "antd";
import { useEffect, useRef, useState } from "react";
import type { CommentOnSupportTicketCommand, SupportTicketContract, SupportTicketPageCursor } from "../../../../../packages/contracts/src/ops/support.js";
import type { OpsConsoleModel } from "../../hooks/useOpsConsoleModel.js";
import type { SupportTicketDetail } from "../../hooks/useSupportDomain.js";
import { describeOpsError } from "../../api/opsClient.js";
import { matchesPlatformReply, platformSupportClient, supportBodyHash, type PlatformReplyIntent, type PlatformSupportClient } from "../../api/platformSupportClient.js";

export type PlatformSupportModel=Pick<OpsConsoleModel,"authorization"|"opsSession"|"workspaceDirectory"|"workspaceDirectoryLoading"|"workspaceDirectoryError"|"loadWorkspaceDirectory">;
const storageKey=(workspace:string)=>`platform-support-reply:${workspace}`;
export function PlatformSupportWorkspace({model,client=platformSupportClient}:{model:PlatformSupportModel;client?:PlatformSupportClient}) {
  const canRead=model.authorization.can("support.ticket.read");
  const canReply=model.authorization.can("support.ticket.update");
  const canDirectory=model.authorization.can("workspace.directory.read");
  const [search,setSearch]=useState("");
  const [workspace,setWorkspace]=useState("");
  const [rows,setRows]=useState<SupportTicketContract[]>([]);
  const [cursor,setCursor]=useState<SupportTicketPageCursor>();
  const [loaded,setLoaded]=useState(false);
  const [detail,setDetail]=useState<SupportTicketDetail>();
  const [body,setBody]=useState("");
  const [visibility,setVisibility]=useState<"internal"|"customer">("internal");
  const [pending,setPending]=useState<CommentOnSupportTicketCommand>();
  const [intent,setIntent]=useState<PlatformReplyIntent>();
  const [unknown,setUnknown]=useState(false);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState("");
  const [success,setSuccess]=useState("");
  const generation=useRef(0);
  const mounted=useRef(true);
  useEffect(()=>{mounted.current=true;return ()=>{mounted.current=false;generation.current++;};},[]);
  useEffect(()=>{generation.current++;setRows([]);setCursor(undefined);setDetail(undefined);setLoaded(false);setPending(undefined);setIntent(undefined);setUnknown(false);setError("");setSuccess("");setBody("");setBusy(false);try{const saved=sessionStorage.getItem(storageKey(workspace));if(saved){const item=JSON.parse(saved) as PlatformReplyIntent;if(item.workspaceId===workspace && item.actorId===model.opsSession?.actor_id && typeof item.idempotencyKey==="string" && typeof item.ticketId==="string" && /^[a-f0-9]{64}$/.test(item.bodyHash)){setIntent(item);setUnknown(true);}}}catch{/* old intent cannot authorize replay */}},[workspace,model.opsSession?.actor_id]);
  const current=(request:number)=>mounted.current && generation.current===request;
  const load=async(next?:SupportTicketPageCursor)=>{if(!workspace||!canRead)return;const request=++generation.current;setBusy(true);setError("");setDetail(undefined);setLoaded(false);try{const page=await client.list(workspace,next);if(!current(request))return;setRows(page.items);setCursor(page.nextCursor);setLoaded(true);}catch(value){if(current(request))setError(describeOpsError(value));}finally{if(current(request))setBusy(false);}};
  const select=async(ticketId:string)=>{const request=++generation.current;setBusy(true);setError("");setDetail(undefined);setBody("");try{const result=await client.get(workspace,ticketId);if(!current(request))return;if(!result)throw new Error("原工单未找到或无权查看，请核对企业后重读。");setDetail(result);}catch(value){if(current(request))setError(describeOpsError(value));}finally{if(current(request))setBusy(false);}};
  const preview=async()=>{if(!detail || !model.opsSession?.actor_id || !body.trim() || busy || unknown)return;const request=generation.current;setBusy(true);setError("");try{const command:CommentOnSupportTicketCommand={workspaceId:workspace,ticketId:detail.ticket.id,body:body.trim(),visibility,expectedRevision:detail.ticket.revision,idempotencyKey:`support_reply_${crypto.randomUUID()}`};const hash=await supportBodyHash(command.body);if(!current(request))return;setPending(command);setIntent({workspaceId:workspace,ticketId:command.ticketId,actorId:model.opsSession.actor_id,idempotencyKey:command.idempotencyKey,visibility,expectedRevision:command.expectedRevision,bodyHash:hash});}catch(value){if(current(request))setError(describeOpsError(value));}finally{if(current(request))setBusy(false);}};
  const clear=()=>{try{sessionStorage.removeItem(storageKey(workspace));}catch{/* stale marker must be reverified after reload */}setIntent(undefined);setPending(undefined);setUnknown(false);};
  const submit=async()=>{if(!pending || !intent || !canReply || busy)return;const request=++generation.current;setBusy(true);setError("");try{try{sessionStorage.setItem(storageKey(workspace),JSON.stringify(intent));}catch{/* the exact original command remains frozen in memory */}const result=await client.comment(pending);if(!current(request))return;if(!await matchesPlatformReply(result.event,intent))throw new Error("原回复事件与提交意图不一致或正文被服务端脱敏，请先查询原结果。");if(!current(request))return;clear();setBody("");setDetail({ticket:result.ticket,events:[...(detail?.events??[]).filter(event=>event.id!==result.event.id),result.event].sort((a,b)=>a.sequence-b.sequence)});setRows(value=>value.map(row=>row.id===result.ticket.id?result.ticket:row));setSuccess("真实工单回复已记录；可见范围以事件中的客户可见/内部标记为准。");}catch(value){if(!current(request))return;const status=(value as {httpStatus?:number}).httpStatus;const uncertain=!status||status>=500;setUnknown(uncertain);setError(`${describeOpsError(value)}${uncertain?" 保留原企业、工单和回复键；先查询原事件，禁止新建另一条回复。":" 刷新工单版本后重新预览。"}`);if(!uncertain)clear();}finally{if(current(request))setBusy(false);}};
  const recover=async()=>{if(!intent||!canRead)return;const request=++generation.current;setBusy(true);setError("");try{const result=await client.get(intent.workspaceId,intent.ticketId);if(!current(request))return;const match=result && (await Promise.all(result.events.map(event=>matchesPlatformReply(event,intent)))).some(Boolean);if(!current(request))return;if(!result||!match){setError("未找到与原回复键、运营身份、正文摘要及可见范围一致的事件；保持原意图。仅可在本会话按原键重试同一条回复。");return;}clear();setDetail(result);setBody("");setSuccess("已查询并核实原回复事件，没有发送第二条回复。");}catch(value){if(current(request))setError(describeOpsError(value));}finally{if(current(request))setBusy(false);}};
  const frozen=busy||Boolean(pending)||unknown;
  return <Space orientation="vertical" size="middle" className="full-width" aria-label="平台支持工单工作台">
    <Alert type="info" showIcon title="首单前也可处理支持交接" description="无需订单或任务。核对授权企业和真实客户后查看工单；回复显式区分客户可见与内部，不发送密码、Token 或完整银行凭证。"/>
    {error?<Alert role="alert" type="error" showIcon title={unknown?"原回复结果待确认":"支持操作未完成"} description={error}/>:null}{success?<Alert role="status" type="success" showIcon title={success}/>:null}
    {!canRead?<Alert type="warning" showIcon title="缺少真实平台工单读取权限"/>:null}
    <Card title="1. 明确选择授权企业">
      {model.workspaceDirectoryError?<Alert role="alert" type="error" title="企业目录读取失败" description={model.workspaceDirectoryError}/>:null}
      <Space wrap><Input aria-label="搜索支持企业" placeholder="企业名称或 Workspace" value={search} disabled={frozen} onChange={event=>setSearch(event.target.value)}/><Button disabled={!canDirectory||frozen} loading={model.workspaceDirectoryLoading} onClick={()=>void model.loadWorkspaceDirectory({query:search,merchantOnly:true,page:1,pageSize:20})}>读取授权企业目录</Button><Button disabled={!canDirectory||frozen||!model.workspaceDirectory.hasMore} onClick={()=>void model.loadWorkspaceDirectory({query:search,merchantOnly:true,page:Math.floor(model.workspaceDirectory.offset/model.workspaceDirectory.limit)+2,pageSize:20})}>下一页企业</Button><Select aria-label="选择支持目标企业" style={{minWidth:320}} placeholder="从真实授权目录选择企业" value={workspace||undefined} disabled={busy||Boolean(pending)||model.workspaceDirectoryLoading} options={model.workspaceDirectory.items.map(row=>({value:row.workspaceId,label:`${row.enterpriseName??row.workspaceId} · ${row.workspaceId} · ${row.status}`}))} onChange={setWorkspace}/></Space>
      {!canDirectory?<Alert type="warning" title="缺少授权企业目录读取能力，不能手填或猜测企业"/>:null}
    </Card>
    <Card title="2. 真实工单列表" aria-busy={busy}>
      <Space wrap><Typography.Text>目标企业：{workspace||"尚未选择"}</Typography.Text><Button disabled={!workspace||!canRead||busy||Boolean(pending)&&!unknown} onClick={()=>void load()}>读取企业工单</Button><Button disabled={!workspace||!canRead||!cursor||busy||Boolean(pending)&&!unknown} onClick={()=>void load(cursor)}>下一页工单</Button></Space>
      {loaded?<Table size="small" pagination={false} rowKey="id" dataSource={rows} columns={[{title:"工单",dataIndex:"ticketNumber"},{title:"主题",dataIndex:"subject"},{title:"真实客户",dataIndex:"customerName"},{title:"客户ID",dataIndex:"customerId"},{title:"状态",dataIndex:"status"},{title:"详情",render:(_:unknown,row:SupportTicketContract)=><Button disabled={busy||Boolean(pending)||unknown} onClick={()=>void select(row.id)}>查看 {row.ticketNumber}</Button>}]} locale={{emptyText:"所选企业本页无工单（真实查询结果）"}}/>:<Typography.Paragraph>尚未读取所选企业真实工单，不表示没有问题。</Typography.Paragraph>}
    </Card>
    {detail?<Card title={`${detail.ticket.ticketNumber} · ${detail.ticket.subject}`}><Descriptions bordered column={2} size="small"><Descriptions.Item label="目标企业">{detail.ticket.workspaceId}</Descriptions.Item><Descriptions.Item label="客户">{detail.ticket.customerName} / {detail.ticket.customerId}</Descriptions.Item><Descriptions.Item label="状态/版本">{detail.ticket.status} / {detail.ticket.revision}</Descriptions.Item><Descriptions.Item label="订单/任务">{detail.ticket.relatedOrderId??"无订单"} / {detail.ticket.relatedTaskId??"无任务"}</Descriptions.Item></Descriptions><Typography.Paragraph style={{whiteSpace:"pre-wrap"}}>{detail.ticket.description}</Typography.Paragraph><Timeline items={detail.events.map(event=>({key:event.id,content:<Space orientation="vertical"><Space><Tag>{event.eventType==="commented"?(event.payload.visibility==="customer"?"客户可见回复":event.payload.visibility==="internal"?"内部备注":"可见范围未核实"):event.eventType}</Tag><Typography.Text>{event.actorId} · {new Date(event.createdAt).toLocaleString()}</Typography.Text></Space><Typography.Text style={{whiteSpace:"pre-wrap"}}>{typeof event.payload.body==="string"?event.payload.body:event.eventType==="created"?"已登记客户问题，正文见工单详情。":"真实事件已记录。"}</Typography.Text></Space>}))}/><Select aria-label="平台回复可见范围" value={visibility} disabled={!canReply||frozen} options={[{value:"internal",label:"仅内部备注"},{value:"customer",label:"客户可见回复"}]} onChange={setVisibility}/><Input.TextArea aria-label="平台支持回复正文" rows={5} maxLength={10000} showCount value={body} disabled={!canReply||frozen} placeholder="填写回复，不包含密码、Token 或完整银行凭证" onChange={event=>setBody(event.target.value)}/><Button type="primary" disabled={!canReply||!model.opsSession?.actor_id||!body.trim()||frozen} onClick={()=>void preview()}>预览真实工单回复</Button></Card>:null}
    {pending&&!unknown?<Card title="核对回复后确认"><Typography.Paragraph>企业 {pending.workspaceId}；原工单 {pending.ticketId}；版本 {pending.expectedRevision}；{pending.visibility==="customer"?"客户可见回复":"仅内部备注"}</Typography.Paragraph><Typography.Paragraph style={{whiteSpace:"pre-wrap"}}>{pending.body}</Typography.Paragraph><Space><Button disabled={busy} onClick={()=>{setPending(undefined);setIntent(undefined);}}>返回修改</Button><Button type="primary" disabled={!canReply||busy} loading={busy} onClick={()=>void submit()}>确认记录{pending.visibility==="customer"?"客户可见回复":"内部备注"}</Button></Space></Card>:null}
    {unknown&&intent?<Alert type="warning" showIcon title="保留原回复意图" description={`原企业 ${intent.workspaceId}；原工单 ${intent.ticketId}；原键 ${intent.idempotencyKey}。刷新只保留标识和正文摘要，不保存客服正文。`} action={<Space><Button disabled={!canRead||busy} onClick={()=>void recover()}>查询并核实原回复</Button>{pending?<Button disabled={!canReply||busy} onClick={()=>void submit()}>按原键重试同一回复</Button>:null}</Space>}/>:null}
  </Space>;
}
