#!/bin/sh
set -eu

# Local-only bootstrap for the real ClamAV scanner. Production and Kubernetes
# receive this key from the secret provider; this script must never be used
# there. It writes only to the ignored repository .env file and never prints
# key material.
if [ "${NODE_ENV:-}" = "production" ] || [ "${DEPLOYMENT_PROFILE:-}" = "production" ]; then
  echo "refusing to generate a scanner key for a production environment" >&2
  exit 1
fi

env_file=${LOCAL_ENV_FILE:-.env}
key_id=${ASSET_SCAN_RECEIPT_KEY_ID:-local-scanner-key}

has_private=false
has_public=false
if [ -f "$env_file" ] && grep -Eq '^ASSET_SCAN_RECEIPT_PRIVATE_KEY_PEM(_B64)?=[^[:space:]]' "$env_file"; then
  has_private=true
fi
if [ -f "$env_file" ] && grep -Eq '^ASSET_SCAN_TRUSTED_PUBLIC_KEYS=[^[:space:]]' "$env_file"; then
  has_public=true
fi
if $has_private && $has_public; then
  exit 0
fi

command -v openssl >/dev/null 2>&1 || { echo "openssl is required to bootstrap the local scanner key" >&2; exit 1; }

work_dir=$(mktemp -d "${TMPDIR:-/tmp}/merchant-scanner-key.XXXXXX")
cleanup() { rm -rf "$work_dir"; }
trap cleanup EXIT INT TERM

if $has_private; then
  encoded=$(awk -F= '/^ASSET_SCAN_RECEIPT_PRIVATE_KEY_PEM_B64=/{sub(/^[^=]*=/, ""); print; exit}' "$env_file")
  if [ -z "$encoded" ]; then
    echo "local scanner private key is present but unreadable" >&2
    exit 1
  fi
  if ! printf '%s' "$encoded" | base64 --decode > "$work_dir/private.pem" 2>/dev/null; then
    printf '%s' "$encoded" | base64 -D > "$work_dir/private.pem"
  fi
else
  openssl genpkey -algorithm ED25519 -out "$work_dir/private.pem" >/dev/null 2>&1
fi
openssl pkey -in "$work_dir/private.pem" -pubout -out "$work_dir/public.pem" >/dev/null 2>&1

private_b64=$(base64 < "$work_dir/private.pem" | tr -d '\n')
public_json=$(awk '{printf "%s\\n", $0}' "$work_dir/public.pem")

if [ ! -f "$env_file" ]; then
  umask 077
  : > "$env_file"
fi
chmod 600 "$env_file"
{
  if ! $has_private; then
    printf '\n# Local-only scanner receipt key; generated by scripts/ensure-local-scanner-key.sh\n'
    printf 'ASSET_SCAN_RECEIPT_KEY_ID=%s\n' "$key_id"
    printf 'ASSET_SCAN_RECEIPT_PRIVATE_KEY_PEM_B64=%s\n' "$private_b64"
  fi
  if ! $has_public; then
    printf 'ASSET_SCAN_TRUSTED_PUBLIC_KEYS={"%s":"%s"}\n' "$key_id" "$public_json"
  fi
} >> "$env_file"

echo "local scanner receipt key initialized in $env_file"
