apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
replicas:
  - name: merchant-api
    count: 3
  - name: merchant-worker-sync
    count: 2
  - name: merchant-worker-generation
    count: 2
  - name: merchant-worker-publish
    count: 3
  - name: merchant-worker-reconcile
    count: 2
  - name: merchant-worker-automation
    count: 1
images:
  - name: merchant-api
    newName: REPLACE_ME/merchant-api
    digest: SET_API_IMAGE_DIGEST
  - name: merchant-worker
    newName: REPLACE_ME/merchant-worker
    digest: SET_WORKER_IMAGE_DIGEST
  - name: merchant-ui
    newName: REPLACE_ME/merchant-ui
    digest: SET_UI_IMAGE_DIGEST
  - name: merchant-ops-ui
    newName: REPLACE_ME/merchant-ops-ui
    digest: SET_OPS_UI_IMAGE_DIGEST
