import { randomUUID } from 'node:crypto'
import { requireWorkspaceScope, type SqlPool, withWorkspaceTransaction } from './repository.js'
import type { CanonicalBackfillConflict } from './canonical-product-backfill.js'
export type CanonicalBackfillConflictStatus = 'open' | 'claimed' | 'resolved' | 'dismissed'
export interface ConflictVerificationEvidence { schemaVersion: 'canonical-backfill-conflict-recheck/1' | 'canonical-backfill-conflict-remediation/1'; observedCode: string; observedCanonicalIds: string[]; source: string; checkedAt: string; reference?: string; remediationType?: 'set_legacy_brand'; actorId?: string; legacyBrandBefore?: string | null; legacyBrandAfter?: string; canonicalBrandId?: string; productVersionBefore?: number; productVersionAfter?: number; migration106Equivalent?: boolean }
export interface CanonicalBackfillConflictRow { id: string; workspaceId: string; runId: string; legacyProductId: string; code: string; canonicalIds: string[]; status: CanonicalBackfillConflictStatus; assigneeId?: string; resolutionNote?: string; verificationEvidence?: ConflictVerificationEvidence; sourceProductVersion?: number; revision: number; createdAt: string; updatedAt: string }
export interface CanonicalBackfillConflictRepository { enqueue(input: { workspaceId: string; runId: string; conflicts: readonly CanonicalBackfillConflict[] }): Promise<CanonicalBackfillConflictRow[]>; list(input: { workspaceId: string; runId?: string; status?: CanonicalBackfillConflictStatus; limit?: number }): Promise<CanonicalBackfillConflictRow[]>; claim(input: { workspaceId: string; id: string; expectedRevision: number; assigneeId: string }): Promise<CanonicalBackfillConflictRow>; recheck(input: { workspaceId: string; id: string; expectedRevision: number; observed: Pick<CanonicalBackfillConflict, 'code' | 'canonicalIds'>; evidence: { source: string; reference?: string } }): Promise<CanonicalBackfillConflictRow>; resolve(input: { workspaceId: string; id: string; expectedRevision: number; status: 'resolved' | 'dismissed'; assigneeId: string; resolutionNote: string }): Promise<CanonicalBackfillConflictRow> }
const clone = <T>(value: T): T => structuredClone(value)
const required = (value: string, code: string) => { if (!value.trim()) throw new Error(code); return value.trim() }
const limitOf = (value = 100) => { if (!Number.isSafeInteger(value) || value < 1 || value > 500) throw new Error('CANONICAL_BACKFILL_CONFLICT_LIMIT_INVALID'); return value }
type Row = { id: string; workspace_id: string; run_id: string; legacy_product_id: string; code: string; canonical_ids: string[]; status: CanonicalBackfillConflictStatus; assignee_id: string | null; resolution_note: string | null; verification_evidence: ConflictVerificationEvidence | null; source_product_version?: number | null; revision: number; created_at: string | Date; updated_at: string | Date }
export const mapCanonicalBackfillConflictRow = (row: Row): CanonicalBackfillConflictRow => ({ id: row.id, workspaceId: row.workspace_id, runId: row.run_id, legacyProductId: row.legacy_product_id, code: row.code, canonicalIds: [...row.canonical_ids], status: row.status, ...(row.assignee_id ? { assigneeId: row.assignee_id } : {}), ...(row.resolution_note ? { resolutionNote: row.resolution_note } : {}), ...(row.verification_evidence && Object.keys(row.verification_evidence).length ? { verificationEvidence: row.verification_evidence } : {}), ...(row.source_product_version === null || row.source_product_version === undefined ? {} : { sourceProductVersion: row.source_product_version }), revision: row.revision, createdAt: row.created_at instanceof Date ? row.created_at.toISOString() : String(row.created_at), updatedAt: row.updated_at instanceof Date ? row.updated_at.toISOString() : String(row.updated_at) })
const map = mapCanonicalBackfillConflictRow
const projection = 'id,workspace_id,run_id,legacy_product_id,code,canonical_ids,status,assignee_id,resolution_note,verification_evidence,revision,created_at,updated_at'
const qualifiedProjection = projection.split(',').map(column => `c.${column}`).join(',')
export class CanonicalBackfillConflictRevisionConflictError extends Error { constructor() { super('CANONICAL_BACKFILL_CONFLICT_REVISION_CONFLICT'); this.name = 'CanonicalBackfillConflictRevisionConflictError' } }
export class CanonicalBackfillConflictIdempotencyConflictError extends Error { constructor() { super('CANONICAL_BACKFILL_CONFLICT_IDEMPOTENCY_CONFLICT'); this.name = 'CanonicalBackfillConflictIdempotencyConflictError' } }
export class CanonicalBackfillConflictRecheckMismatchError extends Error { constructor() { super('CANONICAL_BACKFILL_CONFLICT_RECHECK_MISMATCH'); this.name = 'CanonicalBackfillConflictRecheckMismatchError' } }

// Keep the durable queue vocabulary aligned with the dry-run inventory. A
// dangling canonical -> legacy reference blocks migration validation and must
// be auditable instead of being silently discarded by the scan route.
const conflictCodes: readonly CanonicalBackfillConflict['code'][] = ['MISSING_BRAND', 'CANONICAL_MAPPING_AMBIGUOUS', 'CANONICAL_BRAND_MISMATCH', 'CANONICAL_LEGACY_PRODUCT_MISSING', 'CANONICAL_ID_COLLISION', 'TASK_ACCOUNT_MISMATCH']
const validateConflict = (conflict: CanonicalBackfillConflict) => {
  required(conflict.legacyProductId, 'CANONICAL_BACKFILL_CONFLICT_LEGACY_PRODUCT_ID_REQUIRED')
  if (!conflictCodes.includes(conflict.code)) throw new Error('CANONICAL_BACKFILL_CONFLICT_CODE_INVALID')
  if (!Array.isArray(conflict.canonicalIds) || conflict.canonicalIds.some(id => typeof id !== 'string' || !id.trim())) throw new Error('CANONICAL_BACKFILL_CONFLICT_CANONICAL_IDS_INVALID')
}
const sameCanonicalIds = (left: readonly string[], right: readonly string[]) => left.length === right.length && left.every((id, index) => id === right[index])
const validateRevision = (revision: number) => { if (!Number.isSafeInteger(revision) || revision < 1) throw new Error('CANONICAL_BACKFILL_CONFLICT_REVISION_INVALID'); return revision }
const validateEvidence = (evidence: { source: string; reference?: string }) => ({ schemaVersion: 'canonical-backfill-conflict-recheck/1' as const, observedCode: '', observedCanonicalIds: [] as string[], source: required(evidence.source, 'CANONICAL_BACKFILL_CONFLICT_EVIDENCE_SOURCE_REQUIRED').slice(0, 200), checkedAt: new Date().toISOString(), ...(evidence.reference ? { reference: required(evidence.reference, 'CANONICAL_BACKFILL_CONFLICT_EVIDENCE_REFERENCE_INVALID').slice(0, 500) } : {}) })

export class MemoryCanonicalBackfillConflictRepository implements CanonicalBackfillConflictRepository {
  private readonly rows = new Map<string, CanonicalBackfillConflictRow>()
  async enqueue(input: { workspaceId: string; runId: string; conflicts: readonly CanonicalBackfillConflict[] }) { const workspaceId = requireWorkspaceScope(input.workspaceId); required(input.runId, 'CANONICAL_BACKFILL_CONFLICT_RUN_ID_REQUIRED'); for (const conflict of input.conflicts) validateConflict(conflict); const pending = new Map<string, CanonicalBackfillConflict>(); for (const conflict of input.conflicts) { const key = `${workspaceId}:${input.runId}:${conflict.legacyProductId}:${conflict.code}`; const existing = this.rows.get(key); const staged = pending.get(key); if ((existing && !sameCanonicalIds(existing.canonicalIds, conflict.canonicalIds)) || (staged && !sameCanonicalIds(staged.canonicalIds, conflict.canonicalIds))) throw new CanonicalBackfillConflictIdempotencyConflictError(); if (!existing) pending.set(key, conflict) } const now = new Date().toISOString(); for (const [key, conflict] of pending) { const row: CanonicalBackfillConflictRow = { id: `backfill_conflict_${randomUUID()}`, workspaceId, runId: input.runId, legacyProductId: conflict.legacyProductId, code: conflict.code, canonicalIds: [...conflict.canonicalIds], status: 'open', revision: 1, createdAt: now, updatedAt: now }; this.rows.set(key, row) } return [...this.rows.values()].filter(row => row.workspaceId === workspaceId && row.runId === input.runId).map(clone) }
  async list(input: { workspaceId: string; runId?: string; status?: CanonicalBackfillConflictStatus; limit?: number }) { const workspaceId = requireWorkspaceScope(input.workspaceId); return [...this.rows.values()].filter(row => row.workspaceId === workspaceId && (!input.runId || row.runId === input.runId) && (!input.status || row.status === input.status)).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt) || a.id.localeCompare(b.id)).slice(0, limitOf(input.limit)).map(clone) }
  private mutate(input: { workspaceId: string; id: string; expectedRevision: number; patch: Partial<CanonicalBackfillConflictRow> }) { const workspaceId = requireWorkspaceScope(input.workspaceId); const id = required(input.id, 'CANONICAL_BACKFILL_CONFLICT_ID_REQUIRED'); const expectedRevision = validateRevision(input.expectedRevision); const row = [...this.rows.values()].find(item => item.workspaceId === workspaceId && item.id === id); if (!row) throw new Error('CANONICAL_BACKFILL_CONFLICT_NOT_FOUND'); if (row.revision !== expectedRevision) throw new CanonicalBackfillConflictRevisionConflictError(); if (input.patch.status === 'claimed' && row.status !== 'open') throw new Error('CANONICAL_BACKFILL_CONFLICT_STATE_INVALID'); if ((input.patch.status === 'resolved' || input.patch.status === 'dismissed') && row.status !== 'claimed') throw new Error('CANONICAL_BACKFILL_CONFLICT_STATE_INVALID'); const next = { ...row, ...input.patch, revision: row.revision + 1, updatedAt: new Date().toISOString() }; this.rows.set(`${workspaceId}:${row.runId}:${row.legacyProductId}:${row.code}`, next); return clone(next) }
  async claim(input: { workspaceId: string; id: string; expectedRevision: number; assigneeId: string }) { const assigneeId = required(input.assigneeId, 'CANONICAL_BACKFILL_ASSIGNEE_REQUIRED'); return this.mutate({ workspaceId: input.workspaceId, id: input.id, expectedRevision: input.expectedRevision, patch: { status: 'claimed', assigneeId } }) }
  async recheck(input: { workspaceId: string; id: string; expectedRevision: number; observed: Pick<CanonicalBackfillConflict, 'code' | 'canonicalIds'>; evidence: { source: string; reference?: string } }) { validateConflict({ legacyProductId: 'recheck', ...input.observed }); const workspaceId = requireWorkspaceScope(input.workspaceId); const id = required(input.id, 'CANONICAL_BACKFILL_CONFLICT_ID_REQUIRED'); const expectedRevision = validateRevision(input.expectedRevision); const row = [...this.rows.values()].find(item => item.workspaceId === workspaceId && item.id === id); if (!row) throw new Error('CANONICAL_BACKFILL_CONFLICT_NOT_FOUND'); if (row.revision !== expectedRevision) throw new CanonicalBackfillConflictRevisionConflictError(); if (row.status !== 'open' && row.status !== 'claimed') throw new Error('CANONICAL_BACKFILL_CONFLICT_STATE_INVALID'); if (row.code !== input.observed.code || !sameCanonicalIds(row.canonicalIds, input.observed.canonicalIds)) throw new CanonicalBackfillConflictRecheckMismatchError(); const evidence = validateEvidence(input.evidence); const next = { ...row, verificationEvidence: { ...evidence, observedCode: input.observed.code, observedCanonicalIds: [...input.observed.canonicalIds] }, revision: row.revision + 1, updatedAt: evidence.checkedAt }; this.rows.set(`${workspaceId}:${row.runId}:${row.legacyProductId}:${row.code}`, next); return clone(next) }
  async resolve(input: { workspaceId: string; id: string; expectedRevision: number; status: 'resolved' | 'dismissed'; assigneeId: string; resolutionNote: string }) { if (input.status !== 'resolved' && input.status !== 'dismissed') throw new Error('CANONICAL_BACKFILL_CONFLICT_STATUS_INVALID'); return this.mutate({ ...input, patch: { status: input.status, assigneeId: required(input.assigneeId, 'CANONICAL_BACKFILL_ASSIGNEE_REQUIRED'), resolutionNote: required(input.resolutionNote, 'CANONICAL_BACKFILL_RESOLUTION_REQUIRED') } }) }
}
export class PostgresCanonicalBackfillConflictRepository implements CanonicalBackfillConflictRepository {
  constructor(private readonly pool: SqlPool) {}
  async enqueue(input: { workspaceId: string; runId: string; conflicts: readonly CanonicalBackfillConflict[] }) { const workspaceId = requireWorkspaceScope(input.workspaceId); required(input.runId, 'CANONICAL_BACKFILL_CONFLICT_RUN_ID_REQUIRED'); for (const conflict of input.conflicts) validateConflict(conflict); return withWorkspaceTransaction(this.pool, workspaceId, async client => { for (const conflict of input.conflicts) await client.query(`INSERT INTO canonical_backfill_conflicts (id,workspace_id,run_id,legacy_product_id,code,canonical_ids) VALUES ($1,$2,$3,$4,$5,$6::jsonb) ON CONFLICT (workspace_id,run_id,legacy_product_id,code) DO NOTHING`, [`backfill_conflict_${randomUUID()}`, workspaceId, input.runId, conflict.legacyProductId, conflict.code, JSON.stringify(conflict.canonicalIds)]); const result = await client.query<Row>(`SELECT ${projection} FROM canonical_backfill_conflicts WHERE workspace_id=$1 AND run_id=$2 ORDER BY updated_at DESC,id ASC`, [workspaceId, input.runId]); const rows = result.rows.map(map); for (const conflict of input.conflicts) { const existing = rows.find(row => row.legacyProductId === conflict.legacyProductId && row.code === conflict.code); if (existing && !sameCanonicalIds(existing.canonicalIds, conflict.canonicalIds)) throw new CanonicalBackfillConflictIdempotencyConflictError() } return rows }) }
  async list(input: { workspaceId: string; runId?: string; status?: CanonicalBackfillConflictStatus; limit?: number }) { const workspaceId = requireWorkspaceScope(input.workspaceId); return withWorkspaceTransaction(this.pool, workspaceId, async client => { const result = await client.query<Row>(`SELECT ${qualifiedProjection},p.version AS source_product_version FROM canonical_backfill_conflicts c LEFT JOIN products p ON p.workspace_id=c.workspace_id AND p.id=c.legacy_product_id WHERE c.workspace_id=$1 AND ($2::text IS NULL OR c.run_id=$2) AND ($3::text IS NULL OR c.status=$3) ORDER BY c.updated_at DESC,c.id ASC LIMIT $4`, [workspaceId, input.runId ?? null, input.status ?? null, limitOf(input.limit)]); return result.rows.map(map) }) }
  private async mutate(input: { workspaceId: string; id: string; expectedRevision: number; status: CanonicalBackfillConflictStatus; assigneeId: string; resolutionNote?: string }) { const workspaceId = requireWorkspaceScope(input.workspaceId); const expectedRevision = validateRevision(input.expectedRevision); return withWorkspaceTransaction(this.pool, workspaceId, async client => { const result = await client.query<Row>(`UPDATE canonical_backfill_conflicts SET status=$3,assignee_id=$4,resolution_note=COALESCE($5,resolution_note),revision=revision+1,updated_at=now() WHERE workspace_id=$1 AND id=$2 AND revision=$6 AND status=$7 RETURNING ${projection}`, [workspaceId, required(input.id, 'CANONICAL_BACKFILL_CONFLICT_ID_REQUIRED'), input.status, required(input.assigneeId, 'CANONICAL_BACKFILL_ASSIGNEE_REQUIRED'), input.resolutionNote ?? null, expectedRevision, input.status === 'claimed' ? 'open' : 'claimed']); if (!result.rows[0]) throw new CanonicalBackfillConflictRevisionConflictError(); return map(result.rows[0]) }) }
  async claim(input: { workspaceId: string; id: string; expectedRevision: number; assigneeId: string }) { return this.mutate({ ...input, status: 'claimed' }) }
  async recheck(input: { workspaceId: string; id: string; expectedRevision: number; observed: Pick<CanonicalBackfillConflict, 'code' | 'canonicalIds'>; evidence: { source: string; reference?: string } }) { validateConflict({ legacyProductId: 'recheck', ...input.observed }); const evidence = validateEvidence(input.evidence); const workspaceId = requireWorkspaceScope(input.workspaceId); const expectedRevision = validateRevision(input.expectedRevision); return withWorkspaceTransaction(this.pool, workspaceId, async client => { const id = required(input.id, 'CANONICAL_BACKFILL_CONFLICT_ID_REQUIRED'); const current = (await client.query<Row>(`SELECT ${projection} FROM canonical_backfill_conflicts WHERE workspace_id=$1 AND id=$2 FOR UPDATE`, [workspaceId, id])).rows[0]; if (!current) throw new CanonicalBackfillConflictRevisionConflictError(); const row = map(current); if (row.revision !== expectedRevision) throw new CanonicalBackfillConflictRevisionConflictError(); if (row.status !== 'open' && row.status !== 'claimed') throw new Error('CANONICAL_BACKFILL_CONFLICT_STATE_INVALID'); if (row.code !== input.observed.code || !sameCanonicalIds(row.canonicalIds, input.observed.canonicalIds)) throw new CanonicalBackfillConflictRecheckMismatchError(); const result = await client.query<Row>(`UPDATE canonical_backfill_conflicts SET verification_evidence=$4::jsonb,revision=revision+1,updated_at=now() WHERE workspace_id=$1 AND id=$2 AND revision=$3 AND status IN ('open','claimed') RETURNING ${projection}`, [workspaceId, id, expectedRevision, JSON.stringify({ ...evidence, observedCode: input.observed.code, observedCanonicalIds: [...input.observed.canonicalIds] })]); if (!result.rows[0]) throw new CanonicalBackfillConflictRevisionConflictError(); return map(result.rows[0]) }) }
  async resolve(input: { workspaceId: string; id: string; expectedRevision: number; status: 'resolved' | 'dismissed'; assigneeId: string; resolutionNote: string }) { if (input.status !== 'resolved' && input.status !== 'dismissed') throw new Error('CANONICAL_BACKFILL_CONFLICT_STATUS_INVALID'); return this.mutate({ ...input, resolutionNote: required(input.resolutionNote, 'CANONICAL_BACKFILL_RESOLUTION_REQUIRED') }) }
}
