import { randomUUID } from 'node:crypto'
import { requireWorkspaceScope, type SqlPool, withWorkspaceTransaction } from './repository.js'

export type CommercialBillingCycle = 'monthly' | 'annual'
export type CommercialAddonKind = 'platform' | 'image_generation' | 'bulk_sync'
export type CouponDiscountType = 'fixed_cny' | 'percent'
export type SubscriptionChangeStatus = 'scheduled' | 'applied' | 'cancelled'

export interface CommercialOffer { id: string; code: string; name: string; billingCycle: CommercialBillingCycle; priceCny: number; includedStores: number; includedTasks: number; active: boolean; validFrom: string; validTo?: string; revision: number; updatedBy: string; updatedAt: string }
export interface CommercialAddon { id: string; code: string; name: string; kind: CommercialAddonKind; priceCny: number; units: number; active: boolean; revision: number; updatedBy: string; updatedAt: string }
export interface CommercialCoupon { id: string; code: string; discountType: CouponDiscountType; discountValue: number; maxRedemptions: number; redeemedCount: number; active: boolean; validFrom: string; validTo?: string; revision: number; updatedBy: string; updatedAt: string }
export interface CommercialRollout { id: string; offerCode: string; workspaceId?: string; percentage: number; enabled: boolean; reason: string; revision: number; updatedBy: string; updatedAt: string }
export interface ModelMarkupPolicy { multiplier: number; reason: string; revision: number; updatedBy: string; updatedAt: string }
export interface SubscriptionChange { id: string; workspaceId: string; fromPlanCode: string; toPlanCode: string; fromPriceCny: number; toPriceCny: number; billingCycle: CommercialBillingCycle; priceDifferenceCny: number; effectiveAt: string; status: SubscriptionChangeStatus; reason: string; createdBy: string; createdAt: string }

export interface CommercialExtensionsRepository {
  listOffers(): Promise<CommercialOffer[]>
  upsertOffer(input: Omit<CommercialOffer, 'id' | 'revision' | 'updatedAt'> & { id?: string; expectedRevision?: number }): Promise<CommercialOffer>
  listAddons(): Promise<CommercialAddon[]>
  upsertAddon(input: Omit<CommercialAddon, 'id' | 'revision' | 'updatedAt'> & { id?: string; expectedRevision?: number }): Promise<CommercialAddon>
  listCoupons(): Promise<CommercialCoupon[]>
  redeemCoupon(code: string, at?: string): Promise<CommercialCoupon>
  restoreCoupon(code: string): Promise<CommercialCoupon | undefined>
  upsertCoupon(input: Omit<CommercialCoupon, 'id' | 'revision' | 'updatedAt' | 'redeemedCount'> & { id?: string; redeemedCount?: number; expectedRevision?: number }): Promise<CommercialCoupon>
  listRollouts(): Promise<CommercialRollout[]>
  upsertRollout(input: Omit<CommercialRollout, 'id' | 'revision' | 'updatedAt'> & { id?: string; expectedRevision?: number }): Promise<CommercialRollout>
  getModelMarkupPolicy(): Promise<ModelMarkupPolicy>
  updateModelMarkupPolicy(input: { multiplier: number; reason: string; updatedBy: string; expectedRevision: number }): Promise<ModelMarkupPolicy>
  scheduleChange(input: Omit<SubscriptionChange, 'id' | 'createdAt' | 'status'>): Promise<SubscriptionChange>
  getPendingChange(workspaceId: string): Promise<SubscriptionChange | undefined>
}

const now = () => new Date().toISOString()
const nextRevision = (revision: number | undefined) => (revision ?? 0) + 1

export class MemoryCommercialExtensionsRepository implements CommercialExtensionsRepository {
  private readonly offers = new Map<string, CommercialOffer>()
  private readonly addons = new Map<string, CommercialAddon>()
  private readonly coupons = new Map<string, CommercialCoupon>()
  private readonly rollouts = new Map<string, CommercialRollout>()
  private readonly changes = new Map<string, SubscriptionChange>()
  private modelMarkupPolicy: ModelMarkupPolicy = { multiplier: 2.5, reason: '系统默认倍率', revision: 1, updatedBy: 'system', updatedAt: now() }
  async listOffers() { return [...this.offers.values()].sort((a, b) => a.code.localeCompare(b.code)) }
  async upsertOffer(input: Omit<CommercialOffer, 'id' | 'revision' | 'updatedAt'> & { id?: string; expectedRevision?: number }) { const existing = this.offers.get(input.code); if (existing && input.expectedRevision !== undefined && existing.revision !== input.expectedRevision) throw new Error('commercial offer revision conflict'); const item: CommercialOffer = { ...input, id: existing?.id ?? input.id ?? `offer_${randomUUID()}`, revision: nextRevision(existing?.revision), updatedAt: now() }; this.offers.set(item.code, item); return item }
  async listAddons() { return [...this.addons.values()].sort((a, b) => a.code.localeCompare(b.code)) }
  async upsertAddon(input: Omit<CommercialAddon, 'id' | 'revision' | 'updatedAt'> & { id?: string; expectedRevision?: number }) { const existing = this.addons.get(input.code); if (existing && input.expectedRevision !== undefined && existing.revision !== input.expectedRevision) throw new Error('commercial addon revision conflict'); const item: CommercialAddon = { ...input, id: existing?.id ?? input.id ?? `addon_${randomUUID()}`, revision: nextRevision(existing?.revision), updatedAt: now() }; this.addons.set(item.code, item); return item }
  async listCoupons() { return [...this.coupons.values()].sort((a, b) => a.code.localeCompare(b.code)) }
  async redeemCoupon(code: string, at = now()) { const item = this.coupons.get(code); if (!item || !item.active || item.redeemedCount >= item.maxRedemptions || new Date(at) < new Date(item.validFrom) || (item.validTo && new Date(at) > new Date(item.validTo))) throw new Error('COUPON_NOT_REDEEMABLE'); item.redeemedCount += 1; item.updatedAt = at; return item }
  async restoreCoupon(code: string) { const item = this.coupons.get(code); if (!item || item.redeemedCount <= 0) return item; item.redeemedCount -= 1; item.revision += 1; item.updatedAt = now(); return item }
  async upsertCoupon(input: Omit<CommercialCoupon, 'id' | 'revision' | 'updatedAt' | 'redeemedCount'> & { id?: string; redeemedCount?: number; expectedRevision?: number }) { const existing = this.coupons.get(input.code); if (existing && input.expectedRevision !== undefined && existing.revision !== input.expectedRevision) throw new Error('commercial coupon revision conflict'); const item: CommercialCoupon = { ...input, id: existing?.id ?? input.id ?? `coupon_${randomUUID()}`, redeemedCount: existing?.redeemedCount ?? input.redeemedCount ?? 0, revision: nextRevision(existing?.revision), updatedAt: now() }; this.coupons.set(item.code, item); return item }
  async listRollouts() { return [...this.rollouts.values()].sort((a, b) => a.offerCode.localeCompare(b.offerCode)) }
  async upsertRollout(input: Omit<CommercialRollout, 'id' | 'revision' | 'updatedAt'> & { id?: string; expectedRevision?: number }) { const key = `${input.offerCode}:${input.workspaceId ?? '*'}`; const existing = this.rollouts.get(key); if (existing && input.expectedRevision !== undefined && existing.revision !== input.expectedRevision) throw new Error('commercial rollout revision conflict'); const item: CommercialRollout = { ...input, id: existing?.id ?? input.id ?? `rollout_${randomUUID()}`, revision: nextRevision(existing?.revision), updatedAt: now() }; this.rollouts.set(key, item); return item }
  async getModelMarkupPolicy() { return { ...this.modelMarkupPolicy } }
  async updateModelMarkupPolicy(input: { multiplier: number; reason: string; updatedBy: string; expectedRevision: number }) { if (input.expectedRevision !== this.modelMarkupPolicy.revision) throw new Error('model markup policy revision conflict'); this.modelMarkupPolicy = { multiplier: input.multiplier, reason: input.reason, updatedBy: input.updatedBy, revision: this.modelMarkupPolicy.revision + 1, updatedAt: now() }; return { ...this.modelMarkupPolicy } }
  async scheduleChange(input: Omit<SubscriptionChange, 'id' | 'createdAt' | 'status'>) { const existing = await this.getPendingChange(input.workspaceId); if (existing) this.changes.delete(existing.id); const item: SubscriptionChange = { ...input, id: `sub_change_${randomUUID()}`, status: 'scheduled', createdAt: now() }; this.changes.set(item.id, item); return item }
  async getPendingChange(workspaceId: string) { return [...this.changes.values()].find(item => item.workspaceId === workspaceId && item.status === 'scheduled') }
}

export class PostgresCommercialExtensionsRepository implements CommercialExtensionsRepository {
  constructor(private readonly pool: SqlPool) {}
  async listOffers() { const result = await this.pool.connect().then(async client => { try { return await client.query<CommercialOffer>('SELECT id, code, name, billing_cycle AS "billingCycle", price_cny::float8 AS "priceCny", included_stores AS "includedStores", included_tasks AS "includedTasks", active, valid_from AS "validFrom", valid_to AS "validTo", revision, updated_by AS "updatedBy", updated_at AS "updatedAt" FROM commercial_offers ORDER BY code') } finally { client.release?.() } }); return result.rows }
  async upsertOffer(input: Omit<CommercialOffer, 'id' | 'revision' | 'updatedAt'> & { id?: string; expectedRevision?: number }) { const client = await this.pool.connect(); try { const result = await client.query<CommercialOffer>(`INSERT INTO commercial_offers (id, code, name, billing_cycle, price_cny, included_stores, included_tasks, active, valid_from, valid_to, updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT (code) DO UPDATE SET name=$3, billing_cycle=$4, price_cny=$5, included_stores=$6, included_tasks=$7, active=$8, valid_from=$9, valid_to=$10, revision=commercial_offers.revision+1, updated_by=$11, updated_at=now() WHERE ($12::int IS NULL OR commercial_offers.revision=$12) RETURNING id, code, name, billing_cycle AS "billingCycle", price_cny::float8 AS "priceCny", included_stores AS "includedStores", included_tasks AS "includedTasks", active, valid_from AS "validFrom", valid_to AS "validTo", revision, updated_by AS "updatedBy", updated_at AS "updatedAt"`, [input.id ?? randomUUID(), input.code, input.name, input.billingCycle, input.priceCny, input.includedStores, input.includedTasks, input.active, input.validFrom, input.validTo ?? null, input.updatedBy, input.expectedRevision ?? null]); if (!result.rows[0]) throw new Error('commercial offer revision conflict'); return result.rows[0] } finally { client.release?.() } }
  async listAddons() { const client = await this.pool.connect(); try { const result = await client.query<CommercialAddon>('SELECT id, code, name, kind, price_cny::float8 AS "priceCny", units, active, revision, updated_by AS "updatedBy", updated_at AS "updatedAt" FROM commercial_addons ORDER BY code'); return result.rows } finally { client.release?.() } }
  async upsertAddon(input: Omit<CommercialAddon, 'id' | 'revision' | 'updatedAt'> & { id?: string; expectedRevision?: number }) { const client = await this.pool.connect(); try { const result = await client.query<CommercialAddon>(`INSERT INTO commercial_addons (id, code, name, kind, price_cny, units, active, updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT (code) DO UPDATE SET name=$3, kind=$4, price_cny=$5, units=$6, active=$7, revision=commercial_addons.revision+1, updated_by=$8, updated_at=now() WHERE ($9::int IS NULL OR commercial_addons.revision=$9) RETURNING id, code, name, kind, price_cny::float8 AS "priceCny", units, active, revision, updated_by AS "updatedBy", updated_at AS "updatedAt"`, [input.id ?? randomUUID(), input.code, input.name, input.kind, input.priceCny, input.units, input.active, input.updatedBy, input.expectedRevision ?? null]); if (!result.rows[0]) throw new Error('commercial addon revision conflict'); return result.rows[0] } finally { client.release?.() } }
  async listCoupons() { const client = await this.pool.connect(); try { const result = await client.query<CommercialCoupon>('SELECT id, code, discount_type AS "discountType", discount_value::float8 AS "discountValue", max_redemptions AS "maxRedemptions", redeemed_count AS "redeemedCount", active, valid_from AS "validFrom", valid_to AS "validTo", revision, updated_by AS "updatedBy", updated_at AS "updatedAt" FROM commercial_coupons ORDER BY code'); return result.rows } finally { client.release?.() } }
  async redeemCoupon(code: string, at = new Date().toISOString()) { const client = await this.pool.connect(); try { await client.query('BEGIN'); const found = await client.query<CommercialCoupon>('SELECT id, code, discount_type AS "discountType", discount_value::float8 AS "discountValue", max_redemptions AS "maxRedemptions", redeemed_count AS "redeemedCount", active, valid_from AS "validFrom", valid_to AS "validTo", revision, updated_by AS "updatedBy", updated_at AS "updatedAt" FROM commercial_coupons WHERE code=$1 FOR UPDATE', [code]); const item = found.rows[0]; if (!item || !item.active || item.redeemedCount >= item.maxRedemptions || new Date(at) < new Date(item.validFrom) || (item.validTo && new Date(at) > new Date(item.validTo))) throw new Error('COUPON_NOT_REDEEMABLE'); const result = await client.query<CommercialCoupon>('UPDATE commercial_coupons SET redeemed_count=redeemed_count+1, revision=revision+1, updated_at=$2 WHERE code=$1 RETURNING id, code, discount_type AS "discountType", discount_value::float8 AS "discountValue", max_redemptions AS "maxRedemptions", redeemed_count AS "redeemedCount", active, valid_from AS "validFrom", valid_to AS "validTo", revision, updated_by AS "updatedBy", updated_at AS "updatedAt"', [code, at]); await client.query('COMMIT'); return result.rows[0]! } catch (error) { try { await client.query('ROLLBACK') } catch { /* preserve original error */ } throw error } finally { client.release?.() } }
  async restoreCoupon(code: string) { const client = await this.pool.connect(); try { const result = await client.query<CommercialCoupon>('UPDATE commercial_coupons SET redeemed_count=redeemed_count-1, revision=revision+1, updated_at=now() WHERE code=$1 AND redeemed_count>0 RETURNING id, code, discount_type AS "discountType", discount_value::float8 AS "discountValue", max_redemptions AS "maxRedemptions", redeemed_count AS "redeemedCount", active, valid_from AS "validFrom", valid_to AS "validTo", revision, updated_by AS "updatedBy", updated_at AS "updatedAt"', [code]); return result.rows[0] } finally { client.release?.() } }
  async upsertCoupon(input: Omit<CommercialCoupon, 'id' | 'revision' | 'updatedAt' | 'redeemedCount'> & { id?: string; redeemedCount?: number; expectedRevision?: number }) { const client = await this.pool.connect(); try { const result = await client.query<CommercialCoupon>(`INSERT INTO commercial_coupons (id, code, discount_type, discount_value, max_redemptions, redeemed_count, active, valid_from, valid_to, updated_by) VALUES ($1,$2,$3,$4,$5,COALESCE($6,0),$7,$8,$9,$10) ON CONFLICT (code) DO UPDATE SET discount_type=$3, discount_value=$4, max_redemptions=$5, active=$7, valid_from=$8, valid_to=$9, revision=commercial_coupons.revision+1, updated_by=$10, updated_at=now() WHERE ($11::int IS NULL OR commercial_coupons.revision=$11) RETURNING id, code, discount_type AS "discountType", discount_value::float8 AS "discountValue", max_redemptions AS "maxRedemptions", redeemed_count AS "redeemedCount", active, valid_from AS "validFrom", valid_to AS "validTo", revision, updated_by AS "updatedBy", updated_at AS "updatedAt"`, [input.id ?? randomUUID(), input.code, input.discountType, input.discountValue, input.maxRedemptions, input.redeemedCount ?? 0, input.active, input.validFrom, input.validTo ?? null, input.updatedBy, input.expectedRevision ?? null]); if (!result.rows[0]) throw new Error('commercial coupon revision conflict'); return result.rows[0] } finally { client.release?.() } }
  async listRollouts() { const client = await this.pool.connect(); try { const result = await client.query<CommercialRollout>('SELECT id, offer_code AS "offerCode", workspace_id AS "workspaceId", percentage, enabled, reason, revision, updated_by AS "updatedBy", updated_at AS "updatedAt" FROM commercial_rollouts ORDER BY offer_code, workspace_id NULLS FIRST'); return result.rows } finally { client.release?.() } }
  async upsertRollout(input: Omit<CommercialRollout, 'id' | 'revision' | 'updatedAt'> & { id?: string; expectedRevision?: number }) { const client = await this.pool.connect(); try { const result = await client.query<CommercialRollout>(`INSERT INTO commercial_rollouts (id, offer_code, workspace_id, percentage, enabled, reason, updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (offer_code, workspace_id) DO UPDATE SET percentage=$4, enabled=$5, reason=$6, revision=commercial_rollouts.revision+1, updated_by=$7, updated_at=now() WHERE ($8::int IS NULL OR commercial_rollouts.revision=$8) RETURNING id, offer_code AS "offerCode", NULLIF(workspace_id, '') AS "workspaceId", percentage, enabled, reason, revision, updated_by AS "updatedBy", updated_at AS "updatedAt"`, [input.id ?? randomUUID(), input.offerCode, input.workspaceId ?? '', input.percentage, input.enabled, input.reason, input.updatedBy, input.expectedRevision ?? null]); if (!result.rows[0]) throw new Error('commercial rollout revision conflict'); return result.rows[0] } finally { client.release?.() } }
  async getModelMarkupPolicy() { const client = await this.pool.connect(); try { const result = await client.query<ModelMarkupPolicy>('SELECT multiplier::float8 AS multiplier, reason, revision, updated_by AS "updatedBy", updated_at AS "updatedAt" FROM model_markup_policy WHERE singleton_key=true'); return result.rows[0] ?? { multiplier: 2.5, reason: '系统默认倍率', revision: 1, updatedBy: 'system', updatedAt: new Date(0).toISOString() } } finally { client.release?.() } }
  async updateModelMarkupPolicy(input: { multiplier: number; reason: string; updatedBy: string; expectedRevision: number }) { const client = await this.pool.connect(); try { const result = await client.query<ModelMarkupPolicy>('UPDATE model_markup_policy SET multiplier=$1, reason=$2, updated_by=$3, revision=revision+1, updated_at=now() WHERE singleton_key=true AND revision=$4 RETURNING multiplier::float8 AS multiplier, reason, revision, updated_by AS "updatedBy", updated_at AS "updatedAt"', [input.multiplier, input.reason, input.updatedBy, input.expectedRevision]); if (!result.rows[0]) throw new Error('model markup policy revision conflict'); return result.rows[0] } finally { client.release?.() } }
  async scheduleChange(input: Omit<SubscriptionChange, 'id' | 'createdAt' | 'status'>) { requireWorkspaceScope(input.workspaceId); return withWorkspaceTransaction(this.pool, input.workspaceId, async client => { await client.query("UPDATE workspace_subscription_changes SET status='cancelled' WHERE workspace_id=$1 AND status='scheduled'", [input.workspaceId]); const result = await client.query<SubscriptionChange>(`INSERT INTO workspace_subscription_changes (id, workspace_id, from_plan_code, to_plan_code, from_price_cny, to_price_cny, billing_cycle, price_difference_cny, effective_at, status, reason, created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'scheduled',$10,$11) RETURNING id, workspace_id AS "workspaceId", from_plan_code AS "fromPlanCode", to_plan_code AS "toPlanCode", from_price_cny::float8 AS "fromPriceCny", to_price_cny::float8 AS "toPriceCny", billing_cycle AS "billingCycle", price_difference_cny::float8 AS "priceDifferenceCny", effective_at AS "effectiveAt", status, reason, created_by AS "createdBy", created_at AS "createdAt"`, [randomUUID(), input.workspaceId, input.fromPlanCode, input.toPlanCode, input.fromPriceCny, input.toPriceCny, input.billingCycle, input.priceDifferenceCny, input.effectiveAt, input.reason, input.createdBy]); return result.rows[0]! }) }
  async getPendingChange(workspaceId: string) { requireWorkspaceScope(workspaceId); return withWorkspaceTransaction(this.pool, workspaceId, async client => { const result = await client.query<SubscriptionChange>(`SELECT id, workspace_id AS "workspaceId", from_plan_code AS "fromPlanCode", to_plan_code AS "toPlanCode", from_price_cny::float8 AS "fromPriceCny", to_price_cny::float8 AS "toPriceCny", billing_cycle AS "billingCycle", price_difference_cny::float8 AS "priceDifferenceCny", effective_at AS "effectiveAt", status, reason, created_by AS "createdBy", created_at AS "createdAt" FROM workspace_subscription_changes WHERE workspace_id=$1 AND status='scheduled' ORDER BY created_at DESC LIMIT 1`, [workspaceId]); return result.rows[0] }) }
}
