import { requireWorkspaceScope, type SqlPool, withWorkspaceTransaction } from './repository.js'

export const COMMERCIAL_PLATFORMS = ['jd', 'taobao', 'tmall', 'pinduoduo', 'xiaohongshu', 'douyin'] as const
export type CommercialPlatform = (typeof COMMERCIAL_PLATFORMS)[number]
export interface CommercialSettings { workspaceId: string; planCode: string; planName: string; monthlyPriceCny: number; annualPriceCny: number; includedStores: number; includedTasks: number; revision: number; updatedBy: string; updatedAt: string }
export interface PlatformSetting { workspaceId: string; platform: CommercialPlatform; enabled: boolean; displayName: string; storeAlias: string; revision: number; updatedBy: string; updatedAt: string }
export interface CommercialRepository {
  getSettings(workspaceId: string): Promise<CommercialSettings>
  updateSettings(input: Omit<CommercialSettings, 'revision' | 'updatedAt'> & { expectedRevision?: number }): Promise<CommercialSettings>
  listPlatformSettings(workspaceId: string): Promise<PlatformSetting[]>
  updatePlatform(input: Omit<PlatformSetting, 'revision' | 'updatedAt'> & { expectedRevision?: number }): Promise<PlatformSetting>
}

const settingsDefaults = (workspaceId: string): CommercialSettings => ({ workspaceId, planCode: 'starter', planName: 'Starter', monthlyPriceCny: 199.00, annualPriceCny: 1990.00, includedStores: 1, includedTasks: 30, revision: 1, updatedBy: 'system', updatedAt: new Date().toISOString() })
const platformDefaults = (workspaceId: string, platform: CommercialPlatform): PlatformSetting => ({ workspaceId, platform, enabled: true, displayName: platform, storeAlias: '', revision: 1, updatedBy: 'system', updatedAt: new Date().toISOString() })

export class MemoryCommercialRepository implements CommercialRepository {
  private readonly settings = new Map<string, CommercialSettings>()
  private readonly platforms = new Map<string, PlatformSetting>()
  async getSettings(workspaceId: string) { const value = this.settings.get(workspaceId) ?? settingsDefaults(workspaceId); this.settings.set(workspaceId, value); return value }
  async updateSettings(input: Omit<CommercialSettings, 'revision' | 'updatedAt'> & { expectedRevision?: number }) { const current = await this.getSettings(input.workspaceId); if (input.expectedRevision !== undefined && input.expectedRevision !== current.revision) throw new Error('commercial settings revision conflict'); const value = { ...input, revision: current.revision + 1, updatedAt: new Date().toISOString() }; this.settings.set(input.workspaceId, value); return value }
  async listPlatformSettings(workspaceId: string) { return COMMERCIAL_PLATFORMS.map(platform => { const key = `${workspaceId}:${platform}`; const value = this.platforms.get(key) ?? platformDefaults(workspaceId, platform); this.platforms.set(key, value); return value }) }
  async updatePlatform(input: Omit<PlatformSetting, 'revision' | 'updatedAt'> & { expectedRevision?: number }) { const current = (await this.listPlatformSettings(input.workspaceId)).find(item => item.platform === input.platform)!; if (input.expectedRevision !== undefined && input.expectedRevision !== current.revision) throw new Error('platform settings revision conflict'); const value = { ...input, revision: current.revision + 1, updatedAt: new Date().toISOString() }; this.platforms.set(`${input.workspaceId}:${input.platform}`, value); return value }
}

export class PostgresCommercialRepository implements CommercialRepository {
  constructor(private readonly pool: SqlPool) {}
  async getSettings(workspaceId: string) { requireWorkspaceScope(workspaceId); return withWorkspaceTransaction(this.pool, workspaceId, async client => { await client.query(`INSERT INTO workspace_commercial_settings (workspace_id) VALUES ($1) ON CONFLICT DO NOTHING`, [workspaceId]); const result = await client.query<CommercialSettings>(`SELECT workspace_id AS "workspaceId", plan_code AS "planCode", plan_name AS "planName", monthly_price_cny::float8 AS "monthlyPriceCny", annual_price_cny::float8 AS "annualPriceCny", included_stores AS "includedStores", included_tasks AS "includedTasks", revision, updated_by AS "updatedBy", updated_at AS "updatedAt" FROM workspace_commercial_settings WHERE workspace_id=$1`, [workspaceId]); return result.rows[0]! }) }
  async updateSettings(input: Omit<CommercialSettings, 'revision' | 'updatedAt'> & { expectedRevision?: number }) { requireWorkspaceScope(input.workspaceId); return withWorkspaceTransaction(this.pool, input.workspaceId, async client => { const result = await client.query<CommercialSettings>(`UPDATE workspace_commercial_settings SET plan_code=$2, plan_name=$3, monthly_price_cny=$4, annual_price_cny=$5, included_stores=$6, included_tasks=$7, revision=revision+1, updated_by=$8, updated_at=now() WHERE workspace_id=$1 AND ($9::int IS NULL OR revision=$9) RETURNING workspace_id AS "workspaceId", plan_code AS "planCode", plan_name AS "planName", monthly_price_cny::float8 AS "monthlyPriceCny", annual_price_cny::float8 AS "annualPriceCny", included_stores AS "includedStores", included_tasks AS "includedTasks", revision, updated_by AS "updatedBy", updated_at AS "updatedAt"`, [input.workspaceId, input.planCode, input.planName, input.monthlyPriceCny, input.annualPriceCny, input.includedStores, input.includedTasks, input.updatedBy, input.expectedRevision ?? null]); if (!result.rows[0]) throw new Error('commercial settings revision conflict'); return result.rows[0] }) }
  async listPlatformSettings(workspaceId: string) { requireWorkspaceScope(workspaceId); return withWorkspaceTransaction(this.pool, workspaceId, async client => { for (const platform of COMMERCIAL_PLATFORMS) await client.query(`INSERT INTO workspace_platform_settings (workspace_id, platform) VALUES ($1,$2) ON CONFLICT DO NOTHING`, [workspaceId, platform]); const result = await client.query<PlatformSetting>(`SELECT workspace_id AS "workspaceId", platform, enabled, display_name AS "displayName", store_alias AS "storeAlias", revision, updated_by AS "updatedBy", updated_at AS "updatedAt" FROM workspace_platform_settings WHERE workspace_id=$1 ORDER BY platform`, [workspaceId]); return result.rows }) }
  async updatePlatform(input: Omit<PlatformSetting, 'revision' | 'updatedAt'> & { expectedRevision?: number }) { requireWorkspaceScope(input.workspaceId); return withWorkspaceTransaction(this.pool, input.workspaceId, async client => { const result = await client.query<PlatformSetting>(`UPDATE workspace_platform_settings SET enabled=$3, display_name=$4, store_alias=$5, revision=revision+1, updated_by=$6, updated_at=now() WHERE workspace_id=$1 AND platform=$2 AND ($7::int IS NULL OR revision=$7) RETURNING workspace_id AS "workspaceId", platform, enabled, display_name AS "displayName", store_alias AS "storeAlias", revision, updated_by AS "updatedBy", updated_at AS "updatedAt"`, [input.workspaceId, input.platform, input.enabled, input.displayName, input.storeAlias, input.updatedBy, input.expectedRevision ?? null]); if (!result.rows[0]) throw new Error('platform settings revision conflict'); return result.rows[0] }) }
}
