import {describe,expect,it} from 'vitest'
import {PostgresCommercialCatalogRepository} from './commercial-catalog-repository.js'
import type {SqlClient,SqlPool} from './repository.js'
function fixturePool(){const queries:string[]=[];const client:SqlClient={query:async<Row>(text:string)=>{queries.push(text);const rows=text.includes('FROM commercial_catalog_skus s')?[{id:'sku-owned',code:'owned',kind:'monthly',visibility:'public',requiredCapability:null,versionId:'v-approved',version:1,lifecycle:'approved',executable:false,priceFen:200000,currency:'CNY',priceMode:'fixed',durationDays:null,payload:{blockers:[],planFamily:'owned-clock',tierRank:1,cycle:{unit:'month',count:1},purchasePolicy:{approved:true,version:'owned-test',expiresInSeconds:3600}},checksum:'snapshot',effectiveAt:null,benefits:[{code:'monthly_creative_points',quantity:5000,rawValue:null,rawUnit:null,normalizedValue:null,policyRef:'owned-test',metadata:{}}]}]:text.includes('SELECT state,revision,current_version_id')?[{state:'unlisted',revision:0,versionId:null}]:text.includes('clock_timestamp()')?[{at:new Date('2026-10-05T00:00:00Z')}]:[];return {rows:rows as Row[]}},release(){}};return {pool:{connect:async()=>client} as SqlPool,queries}}
const input={action:'publish' as const,code:'owned',versionId:'v-approved',expectedRevision:0,idempotencyKey:'publish-owned-test',actorId:'owned-controller',reason:'owned-test publication',evidence:{scope:'owned-test'}}
describe('explicit fixture-only historical catalog clock',()=>{
 it('retains database time by default and permits controlled historical creation without changing existing facts',async()=>{const ordinary=fixturePool();expect((await new PostgresCommercialCatalogRepository(ordinary.pool).mutate(input)).effectiveAt).toBe('2026-10-05T00:00:00.000Z');const historical=fixturePool();expect((await new PostgresCommercialCatalogRepository(historical.pool,()=>new Date('2026-09-20T00:00:00Z')).mutate(input)).effectiveAt).toBe('2026-09-20T00:00:00.000Z');expect(historical.queries.some(sql=>/^UPDATE commercial_catalog_sku_versions/u.test(sql))).toBe(false);});
 it('rolls back an invalid fixture time before publishing or writing a version',async()=>{const fixture=fixturePool();await expect(new PostgresCommercialCatalogRepository(fixture.pool,()=>new Date('invalid')).mutate(input)).rejects.toThrow('fixture mutation clock is invalid');expect(fixture.queries).toContain('ROLLBACK');expect(fixture.queries.some(sql=>sql.includes('INSERT INTO commercial_catalog_sku_versions'))).toBe(false);});
});
