import { randomUUID } from 'node:crypto'
import { requireWorkspaceScope, type SqlPool, withWorkspaceTransaction } from './repository.js'

export type DeliveryStatus = 'draft'|'active'
export type DeliveryChecklistKey = 'customer_profile'|'system_integration'|'functional_acceptance'|'training'
export interface CustomerDeliveryVideo { id:string; workspaceId:string; deliveryId:string; title:string; assetRef:string; sortOrder:number; uploadedByActorId:string; createdAt:string; deletedAt:string|null }
export interface CustomerDelivery { id:string; workspaceId:string; companyName:string; contractNumber:string|null; paymentStatus:'unpaid'|'paid'; contractRef:string|null; projectOwner:string|null; supportOwner:string|null; paymentDate:string|null; plannedGoLiveAt:string|null; customerProfileStatus:'incomplete'|'complete'; systemIntegrationStatus:'incomplete'|'complete'; functionalAcceptanceStatus:'incomplete'|'complete'; trainingCompleted:boolean; effectiveAt:string|null; revision:number; createdByActorId:string; updatedByActorId:string; createdAt:string; updatedAt:string; videos:CustomerDeliveryVideo[] }
export interface CustomerDeliveryAuditEvent { workspaceId:string; actorId:string; action:string; resourceId:string; evidence?:Record<string, unknown> }
export interface CustomerDeliveryRepository { list(workspaceId:string):Promise<CustomerDelivery[]>; get(workspaceId:string,id:string):Promise<CustomerDelivery|null>; create(input:{workspaceId:string;companyName:string;actorId:string}):Promise<CustomerDelivery>; update(input:{workspaceId:string;id:string;actorId:string;expectedRevision:number;patch:Partial<Pick<CustomerDelivery,'companyName'|'contractNumber'|'paymentStatus'|'contractRef'|'projectOwner'|'supportOwner'|'paymentDate'|'plannedGoLiveAt'|'customerProfileStatus'|'systemIntegrationStatus'|'functionalAcceptanceStatus'|'trainingCompleted'>>}):Promise<CustomerDelivery>; addVideo(input:{workspaceId:string;deliveryId:string;actorId:string;title:string;assetRef:string;sortOrder?:number}):Promise<CustomerDeliveryVideo>; removeVideo?(input:{workspaceId:string;deliveryId:string;videoId:string;actorId:string}):Promise<void> }
export class CustomerDeliveryError extends Error { constructor(readonly code:string,message:string){super(message)} }
const clone=<T>(v:T):T=>structuredClone(v)
const complete=(d:CustomerDelivery)=>d.customerProfileStatus==='complete'&&d.systemIntegrationStatus==='complete'&&d.functionalAcceptanceStatus==='complete'&&d.trainingCompleted
export class MemoryCustomerDeliveryRepository implements CustomerDeliveryRepository {
 private rows=new Map<string,CustomerDelivery>()
 constructor(private readonly auditWriter:(event:CustomerDeliveryAuditEvent)=>Promise<void>|void = ()=>{}){}
 async list(workspaceId:string){const s=requireWorkspaceScope(workspaceId);return [...this.rows.values()].filter(x=>x.workspaceId===s).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(clone)}
 async get(workspaceId:string,id:string){const r=this.rows.get(`${requireWorkspaceScope(workspaceId)}:${id}`);return r?clone(r):null}
 async create(input:{workspaceId:string;companyName:string;actorId:string}){const ws=requireWorkspaceScope(input.workspaceId); if(!input.companyName?.trim()) throw new CustomerDeliveryError('INVALID_INPUT','companyName required'); if([...this.rows.values()].some(x=>x.workspaceId===ws&&x.companyName.toLowerCase()===input.companyName.trim().toLowerCase())) throw new CustomerDeliveryError('DUPLICATE_COMPANY','company already exists'); const now=new Date().toISOString(); const d:CustomerDelivery={id:`cd_${randomUUID()}`,workspaceId:ws,companyName:input.companyName.trim(),contractNumber:null,paymentStatus:'unpaid',contractRef:null,projectOwner:null,supportOwner:null,paymentDate:null,plannedGoLiveAt:null,customerProfileStatus:'incomplete',systemIntegrationStatus:'incomplete',functionalAcceptanceStatus:'incomplete',trainingCompleted:false,effectiveAt:null,revision:1,createdByActorId:input.actorId,updatedByActorId:input.actorId,createdAt:now,updatedAt:now,videos:[]};this.rows.set(`${ws}:${d.id}`,d);await this.auditWriter({workspaceId:ws,actorId:input.actorId,action:'customer_delivery.create',resourceId:d.id,evidence:{companyName:d.companyName}});return clone(d)}
 async update(input: {workspaceId:string;id:string;actorId:string;expectedRevision:number;patch: Partial<Pick<CustomerDelivery, 'companyName'|'contractNumber'|'paymentStatus'|'contractRef'|'projectOwner'|'supportOwner'|'paymentDate'|'plannedGoLiveAt'|'customerProfileStatus'|'systemIntegrationStatus'|'functionalAcceptanceStatus'|'trainingCompleted'>>}){const ws=requireWorkspaceScope(input.workspaceId),d=this.rows.get(`${ws}:${input.id}`);if(!d)throw new CustomerDeliveryError('NOT_FOUND','customer delivery not found');if(d.revision!==input.expectedRevision)throw new CustomerDeliveryError('REVISION_CONFLICT','revision changed');if(d.paymentStatus==='unpaid'&&(['systemIntegrationStatus','functionalAcceptanceStatus','trainingCompleted'] as const).some(k=>k in input.patch&&input.patch[k] && input.patch[k] !== d[k]))throw new CustomerDeliveryError('PAYMENT_REQUIRED','customer has not paid');if(input.patch.companyName!==undefined&&!input.patch.companyName.trim())throw new CustomerDeliveryError('INVALID_INPUT','companyName required');const patch={...input.patch};if(patch.functionalAcceptanceStatus==='complete')patch.trainingCompleted=true;if(patch.trainingCompleted===true)patch.functionalAcceptanceStatus='complete';if(patch.functionalAcceptanceStatus==='incomplete')patch.trainingCompleted=false;Object.assign(d,patch);d.updatedByActorId=input.actorId;d.updatedAt=new Date().toISOString();d.revision++;if(complete(d)&&!d.effectiveAt)d.effectiveAt=d.updatedAt;await this.auditWriter({workspaceId:ws,actorId:input.actorId,action:'customer_delivery.update',resourceId:d.id,evidence:{patch,revision:d.revision}});return clone(d)}
 async addVideo(input:{workspaceId:string;deliveryId:string;actorId:string;title:string;assetRef:string;sortOrder?:number}){const d=await this.get(input.workspaceId,input.deliveryId);if(!d)throw new CustomerDeliveryError('NOT_FOUND','customer delivery not found');if(!input.title.trim()||!input.assetRef.trim())throw new CustomerDeliveryError('INVALID_INPUT','video title and assetRef required');const v:CustomerDeliveryVideo={id:`cdv_${randomUUID()}`,workspaceId:d.workspaceId,deliveryId:d.id,title:input.title.trim(),assetRef:input.assetRef.trim(),sortOrder:input.sortOrder??d.videos.length,uploadedByActorId:input.actorId,createdAt:new Date().toISOString(),deletedAt:null};const row=this.rows.get(`${d.workspaceId}:${d.id}`)!;row.videos.push(v);row.updatedAt=new Date().toISOString();row.revision++;await this.auditWriter({workspaceId:d.workspaceId,actorId:input.actorId,action:'customer_delivery.video.add',resourceId:v.id,evidence:{deliveryId:d.id,assetRef:v.assetRef}});return clone(v)}
 async removeVideo(input:{workspaceId:string;deliveryId:string;videoId:string;actorId:string}){const ws=requireWorkspaceScope(input.workspaceId),row=this.rows.get(`${ws}:${input.deliveryId}`),video=row?.videos.find(v=>v.id===input.videoId);if(!row||!video)throw new CustomerDeliveryError('NOT_FOUND','video not found');if(video.deletedAt)return;video.deletedAt=new Date().toISOString();row.updatedAt=video.deletedAt;row.revision++;await this.auditWriter({workspaceId:ws,actorId:input.actorId,action:'customer_delivery.video.remove',resourceId:video.id,evidence:{deliveryId:row.id,softDelete:true}})}
}
export class PostgresCustomerDeliveryRepository implements CustomerDeliveryRepository {
 constructor(private readonly pool:SqlPool){}
 async list(workspaceId:string){return withWorkspaceTransaction(this.pool,requireWorkspaceScope(workspaceId),async c=>(await c.query(`SELECT * FROM workspace_customer_deliveries WHERE workspace_id=$1 ORDER BY updated_at DESC,id DESC`,[workspaceId])).rows.map((r:any)=>({...r,workspaceId:r.workspace_id,companyName:r.company_name,paymentStatus:r.payment_status,contractNumber:r.contract_number,contractRef:r.contract_ref,projectOwner:r.project_owner,supportOwner:r.support_owner,paymentDate:r.payment_date,plannedGoLiveAt:r.planned_go_live_at,customerProfileStatus:r.customer_profile_status,systemIntegrationStatus:r.system_integration_status,functionalAcceptanceStatus:r.functional_acceptance_status,trainingCompleted:r.training_completed,effectiveAt:r.effective_at,createdByActorId:r.created_by_actor_id,updatedByActorId:r.updated_by_actor_id,createdAt:r.created_at,updatedAt:r.updated_at,revision:Number(r.revision),videos:[]})))}
 async get(workspaceId:string,id:string){const rows=await this.list(workspaceId);return rows.find(x=>x.id===id)||null}
 async create(input:any):Promise<never>{throw new CustomerDeliveryError('NOT_IMPLEMENTED','postgres create pending')}
 async update(input:any):Promise<never>{throw new CustomerDeliveryError('NOT_IMPLEMENTED','postgres update pending')}
 async addVideo(input:any):Promise<never>{throw new CustomerDeliveryError('NOT_IMPLEMENTED','postgres videos pending')}
}
