import { randomUUID } from 'node:crypto'
import { requireWorkspaceScope, type SqlPool, withWorkspaceTransaction } from './repository.js'

export interface GrowthEvent { id: string; workspaceId: string; eventType: string; sourceChannel?: string; actorId?: string; planCode?: string; metadata: Record<string, unknown>; occurredAt: string }
export interface GrowthFunnel { workspaceId: string; sourceChannel?: string; from?: string; to?: string; counts: Record<string, number>; totalEvents: number }
export interface GrowthRepository { append(input: Omit<GrowthEvent, 'id' | 'occurredAt'> & { occurredAt?: string }): Promise<GrowthEvent>; funnel(input: { workspaceId: string; sourceChannel?: string; from?: string; to?: string }): Promise<GrowthFunnel> }

export class MemoryGrowthRepository implements GrowthRepository {
  private readonly events: GrowthEvent[] = []
  async append(input: Omit<GrowthEvent, 'id' | 'occurredAt'> & { occurredAt?: string }) { const event: GrowthEvent = { ...input, id: `growth_${randomUUID()}`, occurredAt: input.occurredAt ?? new Date().toISOString() }; this.events.push(event); return event }
  async funnel(input: { workspaceId: string; sourceChannel?: string; from?: string; to?: string }) { const rows = this.events.filter(item => item.workspaceId === input.workspaceId && (!input.sourceChannel || item.sourceChannel === input.sourceChannel) && (!input.from || item.occurredAt >= input.from) && (!input.to || item.occurredAt <= input.to)); const counts = rows.reduce((result, item) => { result[item.eventType] = (result[item.eventType] ?? 0) + 1; return result }, {} as Record<string, number>); return { workspaceId: input.workspaceId, ...(input.sourceChannel ? { sourceChannel: input.sourceChannel } : {}), ...(input.from ? { from: input.from } : {}), ...(input.to ? { to: input.to } : {}), counts, totalEvents: rows.length } }
}

export class PostgresGrowthRepository implements GrowthRepository {
  constructor(private readonly pool: SqlPool) {}
  async append(input: Omit<GrowthEvent, 'id' | 'occurredAt'> & { occurredAt?: string }) { requireWorkspaceScope(input.workspaceId); return withWorkspaceTransaction(this.pool, input.workspaceId, async client => { const result = await client.query<GrowthEvent>('INSERT INTO workspace_growth_events (id, workspace_id, event_type, source_channel, actor_id, plan_code, metadata, occurred_at) VALUES ($1,$2,$3,$4,$5,$6,$7,COALESCE($8,now())) RETURNING id, workspace_id AS "workspaceId", event_type AS "eventType", source_channel AS "sourceChannel", actor_id AS "actorId", plan_code AS "planCode", metadata, occurred_at AS "occurredAt"', [randomUUID(), input.workspaceId, input.eventType, input.sourceChannel ?? null, input.actorId ?? null, input.planCode ?? null, input.metadata, input.occurredAt ?? null]); return result.rows[0]! }) }
  async funnel(input: { workspaceId: string; sourceChannel?: string; from?: string; to?: string }) { requireWorkspaceScope(input.workspaceId); return withWorkspaceTransaction(this.pool, input.workspaceId, async client => { const result = await client.query<{ eventType: string; count: number }>('SELECT event_type AS "eventType", count(*)::int AS count FROM workspace_growth_events WHERE workspace_id=$1 AND ($2::text IS NULL OR source_channel=$2) AND ($3::timestamptz IS NULL OR occurred_at >= $3) AND ($4::timestamptz IS NULL OR occurred_at <= $4) GROUP BY event_type ORDER BY event_type', [input.workspaceId, input.sourceChannel ?? null, input.from ?? null, input.to ?? null]); const counts = Object.fromEntries(result.rows.map(row => [row.eventType, row.count])); return { workspaceId: input.workspaceId, ...(input.sourceChannel ? { sourceChannel: input.sourceChannel } : {}), ...(input.from ? { from: input.from } : {}), ...(input.to ? { to: input.to } : {}), counts, totalEvents: result.rows.reduce((sum, row) => sum + row.count, 0) } }) }
}
