import { randomUUID } from 'node:crypto'
import { requireWorkspaceScope, type SqlPool, withWorkspaceTransaction } from './repository.js'

export interface ObjectStorageOrphan { id: string; workspaceId: string; objectKey: string; reason: string; state: 'pending' | 'cleaned' | 'manual_attention'; attempts: number; lastError?: string; nextAttemptAt: string; createdAt: string; updatedAt: string }
export interface ObjectOrphanRepository { enqueue(input: { workspaceId: string; objectKey: string; reason: string; lastError?: string }): Promise<ObjectStorageOrphan>; listPending(workspaceId: string, limit?: number): Promise<ObjectStorageOrphan[]>; markCleaned(input: { workspaceId: string; id: string }): Promise<void>; markRetry(input: { workspaceId: string; id: string; error: string; nextAttemptAt: string; manualAttention?: boolean }): Promise<void> }

export class MemoryObjectOrphanRepository implements ObjectOrphanRepository {
  private readonly rows = new Map<string, ObjectStorageOrphan>()
  async enqueue(input: { workspaceId: string; objectKey: string; reason: string; lastError?: string }) { const key = `${input.workspaceId}:${input.objectKey}`; const current = this.rows.get(key); const timestamp = new Date().toISOString(); const row: ObjectStorageOrphan = current ? { ...current, reason: input.reason, ...(input.lastError ? { lastError: input.lastError } : {}), attempts: current.attempts + 1, updatedAt: timestamp } : { id: `orphan_${randomUUID()}`, ...input, state: 'pending', attempts: 1, nextAttemptAt: timestamp, createdAt: timestamp, updatedAt: timestamp }; this.rows.set(key, row); return row }
  async listPending(workspaceId: string, limit = 100) { const current = new Date().toISOString(); return [...this.rows.values()].filter(row => row.workspaceId === workspaceId && row.state === 'pending' && row.nextAttemptAt <= current).slice(0, limit) }
  async markCleaned(input: { workspaceId: string; id: string }) { const row = [...this.rows.values()].find(item => item.workspaceId === input.workspaceId && item.id === input.id); if (row?.state === 'pending') { row.state = 'cleaned'; row.updatedAt = new Date().toISOString() } }
  async markRetry(input: { workspaceId: string; id: string; error: string; nextAttemptAt: string; manualAttention?: boolean }) { const row = [...this.rows.values()].find(item => item.workspaceId === input.workspaceId && item.id === input.id); if (row) { row.attempts += 1; row.lastError = input.error; row.nextAttemptAt = input.nextAttemptAt; row.state = input.manualAttention ? 'manual_attention' : 'pending'; row.updatedAt = new Date().toISOString() } }
}

export class PostgresObjectOrphanRepository implements ObjectOrphanRepository {
  constructor(private readonly pool: SqlPool) {}
  async enqueue(input: { workspaceId: string; objectKey: string; reason: string; lastError?: string }) { requireWorkspaceScope(input.workspaceId); return withWorkspaceTransaction(this.pool, input.workspaceId, async client => { const result = await client.query<ObjectStorageOrphan>(`INSERT INTO object_storage_orphans (id, workspace_id, object_key, reason, attempts, last_error) VALUES ($1,$2,$3,$4,1,$5) ON CONFLICT (workspace_id, object_key) DO UPDATE SET reason=EXCLUDED.reason, attempts=object_storage_orphans.attempts+1, last_error=EXCLUDED.last_error, state='pending', updated_at=now() RETURNING id, workspace_id AS "workspaceId", object_key AS "objectKey", reason, state, attempts, last_error AS "lastError", next_attempt_at AS "nextAttemptAt", created_at AS "createdAt", updated_at AS "updatedAt"`, [randomUUID(), input.workspaceId, input.objectKey, input.reason, input.lastError ?? null]); return result.rows[0]! }) }
  async listPending(workspaceId: string, limit = 100) { requireWorkspaceScope(workspaceId); return withWorkspaceTransaction(this.pool, workspaceId, async client => (await client.query<ObjectStorageOrphan>(`SELECT id, workspace_id AS "workspaceId", object_key AS "objectKey", reason, state, attempts, last_error AS "lastError", next_attempt_at AS "nextAttemptAt", created_at AS "createdAt", updated_at AS "updatedAt" FROM object_storage_orphans WHERE workspace_id=$1 AND state='pending' AND next_attempt_at<=now() ORDER BY created_at LIMIT $2`, [workspaceId, limit])).rows) }
  async markCleaned(input: { workspaceId: string; id: string }) { requireWorkspaceScope(input.workspaceId); await withWorkspaceTransaction(this.pool, input.workspaceId, async client => { await client.query(`UPDATE object_storage_orphans SET state='cleaned', updated_at=now() WHERE workspace_id=$1 AND id=$2 AND state='pending'`, [input.workspaceId, input.id]) }) }
  async markRetry(input: { workspaceId: string; id: string; error: string; nextAttemptAt: string; manualAttention?: boolean }) { requireWorkspaceScope(input.workspaceId); await withWorkspaceTransaction(this.pool, input.workspaceId, async client => { await client.query(`UPDATE object_storage_orphans SET state=$3, attempts=attempts+1, last_error=$4, next_attempt_at=$5, updated_at=now() WHERE workspace_id=$1 AND id=$2 AND state='pending'`, [input.workspaceId, input.id, input.manualAttention ? 'manual_attention' : 'pending', input.error, input.nextAttemptAt]) }) }
}
