import { randomUUID } from 'node:crypto'
import { requireWorkspaceScope, type SqlClient, type SqlPool, withWorkspaceTransaction } from './repository.js'

export interface UsageSnapshot { workspaceId: string; periodStart: string; includedTasks: number; usedTasks: number; remainingTasks: number }
export interface UsageRepository { get(workspaceId: string): Promise<UsageSnapshot>; consume(input: { workspaceId: string; taskId: string; idempotencyKey: string; actorId: string }): Promise<{ snapshot: UsageSnapshot; charged: boolean }>; refund(input: { workspaceId: string; taskId: string; idempotencyKey: string; actorId: string; reason: string }): Promise<{ snapshot: UsageSnapshot; refunded: boolean }> }

export class UsageIdempotencyConflictError extends Error {
  readonly code = 'USAGE_IDEMPOTENCY_CONFLICT'
  constructor() { super('usage idempotency key was reused for a different task'); this.name = 'UsageIdempotencyConflictError' }
}

const period = () => new Date().toISOString().slice(0, 7) + '-01'
export class MemoryUsageRepository implements UsageRepository {
  private readonly used = new Map<string, number>()
  private readonly charges = new Map<string, { workspaceId: string; taskId: string; refunded: boolean }>()
  constructor(private readonly quota: (workspaceId: string) => Promise<{ includedTasks: number }>) {}
  async get(workspaceId: string) { const includedTasks = (await this.quota(workspaceId)).includedTasks; const usedTasks = this.used.get(workspaceId) ?? 0; return { workspaceId, periodStart: period(), includedTasks, usedTasks, remainingTasks: Math.max(0, includedTasks - usedTasks) } }
  async consume(input: { workspaceId: string; taskId: string; idempotencyKey: string; actorId: string }) { const key = `${input.workspaceId}:${input.idempotencyKey}`; const existing = this.charges.get(key); if (existing) { if (existing.taskId !== input.taskId) throw new UsageIdempotencyConflictError(); return { snapshot: await this.get(input.workspaceId), charged: !existing.refunded } } const snapshot = await this.get(input.workspaceId); if (snapshot.usedTasks >= snapshot.includedTasks) throw new Error('QUOTA_EXCEEDED'); this.used.set(input.workspaceId, snapshot.usedTasks + 1); this.charges.set(key, { workspaceId: input.workspaceId, taskId: input.taskId, refunded: false }); return { snapshot: await this.get(input.workspaceId), charged: true } }
  async refund(input: { workspaceId: string; taskId: string; idempotencyKey: string; actorId: string; reason: string }) { const key = `${input.workspaceId}:${input.idempotencyKey}`; const existing = this.charges.get(key); if (!existing || existing.refunded) return { snapshot: await this.get(input.workspaceId), refunded: false }; this.used.set(input.workspaceId, Math.max(0, (this.used.get(input.workspaceId) ?? 1) - 1)); existing.refunded = true; return { snapshot: await this.get(input.workspaceId), refunded: true } }
}

export class PostgresUsageRepository implements UsageRepository {
  constructor(private readonly pool: SqlPool) {}
  async get(workspaceId: string) { requireWorkspaceScope(workspaceId); return withWorkspaceTransaction(this.pool, workspaceId, async client => { await client.query(`INSERT INTO workspace_commercial_settings (workspace_id) VALUES ($1) ON CONFLICT DO NOTHING`, [workspaceId]); await this.resetPeriod(client, workspaceId); const result = await client.query<{ periodStart: string; includedTasks: number; usedTasks: number }>(`SELECT to_char(usage_period_start, 'YYYY-MM-DD') AS "periodStart", included_tasks AS "includedTasks", monthly_tasks_used AS "usedTasks" FROM workspace_commercial_settings WHERE workspace_id=$1`, [workspaceId]); const row = result.rows[0] ?? { periodStart: period(), includedTasks: 0, usedTasks: 0 }; return { workspaceId, periodStart: row.periodStart, includedTasks: row.includedTasks, usedTasks: row.usedTasks, remainingTasks: Math.max(0, row.includedTasks - row.usedTasks) } }) }
  async consume(input: { workspaceId: string; taskId: string; idempotencyKey: string; actorId: string }) { requireWorkspaceScope(input.workspaceId); return withWorkspaceTransaction(this.pool, input.workspaceId, async client => { await client.query(`INSERT INTO workspace_commercial_settings (workspace_id) VALUES ($1) ON CONFLICT DO NOTHING`, [input.workspaceId]); const existing = await client.query<{ taskId: string; refunded: boolean }>('SELECT task_id AS "taskId", refunded FROM workspace_usage_ledger WHERE workspace_id=$1 AND idempotency_key=$2', [input.workspaceId, input.idempotencyKey]); if (existing.rows[0]) { if (existing.rows[0].taskId !== input.taskId) throw new UsageIdempotencyConflictError(); return { snapshot: await this.snapshot(client, input.workspaceId), charged: !existing.rows[0].refunded } } await this.resetPeriod(client, input.workspaceId); const updated = await client.query('UPDATE workspace_commercial_settings SET monthly_tasks_used=monthly_tasks_used+1, updated_at=now() WHERE workspace_id=$1 AND monthly_tasks_used < included_tasks', [input.workspaceId]); if (!updated.rowCount) throw new Error('QUOTA_EXCEEDED'); await client.query(`INSERT INTO workspace_usage_ledger (id, workspace_id, task_id, idempotency_key, units, actor_id) VALUES ($1,$2,$3,$4,1,$5)`, [randomUUID(), input.workspaceId, input.taskId, input.idempotencyKey, input.actorId]); return { snapshot: await this.snapshot(client, input.workspaceId), charged: true } }) }
  async refund(input: { workspaceId: string; taskId: string; idempotencyKey: string; actorId: string; reason: string }) { requireWorkspaceScope(input.workspaceId); return withWorkspaceTransaction(this.pool, input.workspaceId, async client => { await this.resetPeriod(client, input.workspaceId); const result = await client.query<{ id: string }>('UPDATE workspace_usage_ledger SET refunded=true, refund_reason=$4, refunded_by=$5, refunded_at=now() WHERE workspace_id=$1 AND idempotency_key=$2 AND task_id=$3 AND refunded=false RETURNING id', [input.workspaceId, input.idempotencyKey, input.taskId, input.reason, input.actorId]); if (result.rowCount) await client.query('UPDATE workspace_commercial_settings SET monthly_tasks_used=GREATEST(0, monthly_tasks_used-1), updated_at=now() WHERE workspace_id=$1', [input.workspaceId]); return { snapshot: await this.snapshot(client, input.workspaceId), refunded: Boolean(result.rowCount) } }) }
  private async resetPeriod(client: SqlClient, workspaceId: string) { await client.query(`UPDATE workspace_commercial_settings SET usage_period_start=date_trunc('month', now())::date, monthly_tasks_used=0 WHERE workspace_id=$1 AND usage_period_start < date_trunc('month', now())::date`, [workspaceId]) }
  private async snapshot(client: SqlClient, workspaceId: string): Promise<UsageSnapshot> { const result = await client.query<{ periodStart: string; includedTasks: number; usedTasks: number }>(`SELECT to_char(usage_period_start, 'YYYY-MM-DD') AS "periodStart", included_tasks AS "includedTasks", monthly_tasks_used AS "usedTasks" FROM workspace_commercial_settings WHERE workspace_id=$1`, [workspaceId]); const row = result.rows[0] ?? { periodStart: period(), includedTasks: 0, usedTasks: 0 }; return { workspaceId, periodStart: row.periodStart, includedTasks: row.includedTasks, usedTasks: row.usedTasks, remainingTasks: Math.max(0, row.includedTasks - row.usedTasks) } }
}
