import { useCallback, useEffect, useRef, useState } from "react";
import { Alert, Button, Descriptions, Drawer, Form, Input, Modal, Select, Space, Table, Tag } from "antd";
import { commercialOperationsClient, type CommercialBenefitBundle, type CommercialCatalogAction } from "../../api/commercialOperationsClient.js";
import type { OpsConsoleModel } from "../../hooks/useOpsConsoleModel.js";
import { approvalLabels, loadAllBenefitBundleReferences } from "./catalogManagementModel.js";
import { encodeBenefits, RegisteredBenefitFields, type BenefitEditorValue } from "./RegisteredBenefitFields.js";

interface Values { code: string; name: string; usage: "included" | "standalone"; reason: string; benefits: BenefitEditorValue[]; }
const key = () => `ops_bundle_${crypto.randomUUID()}`;
export function BenefitBundleManagementPanel({ model, definitions, definitionError, onChange }: { model: OpsConsoleModel; definitions: Record<string, unknown>[]; definitionError?: string; onChange(items: CommercialBenefitBundle[]): void }) {
  const [items, setItems] = useState<CommercialBenefitBundle[]>([]);
  const [loading, setLoading] = useState(true);
  const [cursorStack, setCursorStack] = useState<Array<string | undefined>>([undefined]);
  const [pageIndex, setPageIndex] = useState(0);
  const [nextCursor, setNextCursor] = useState<string | null>(null);
  const [total, setTotal] = useState(0);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [editor, setEditor] = useState<{ source?: CommercialBenefitBundle; key: string }>();
  const [action, setAction] = useState<{ item: CommercialBenefitBundle; action: CommercialCatalogAction; key: string }>();
  const [reason, setReason] = useState("");
  const [selected, setSelected] = useState<CommercialBenefitBundle>();
  const refsSequence = useRef(0);
  const [refs, setRefs] = useState<Record<string, unknown>[]>([]);
  const [refsLoading, setRefsLoading] = useState(false);
  const [refsError, setRefsError] = useState("");
  const [busy, setBusy] = useState(false);
  const [form] = Form.useForm<Values>();
  const load = useCallback(async (cursor: string | undefined = cursorStack[pageIndex]) => { setLoading(true); try { const page = await commercialOperationsClient.benefitBundles({ limit: 20, ...(cursor ? { cursor } : {}) }); setItems(page.items); onChange(page.items); setNextCursor(page.nextCursor ?? null); setTotal(page.total); setError(""); } catch (failure) { setError(failure instanceof Error ? failure.message : "权益包读取失败"); } finally { setLoading(false); } }, [cursorStack, onChange, pageIndex]);
  const navigate = async (cursor: string | undefined, index: number, stack: Array<string | undefined>) => { setLoading(true); try { const page = await commercialOperationsClient.benefitBundles({ limit: 20, ...(cursor ? { cursor } : {}) }); setItems(page.items); onChange(page.items); setNextCursor(page.nextCursor ?? null); setTotal(page.total); setCursorStack(stack); setPageIndex(index); setError(""); } catch (failure) { setError(failure instanceof Error ? failure.message : "权益包读取失败；仍显示上一页，请重试"); } finally { setLoading(false); } };
  useEffect(() => { void load(undefined); }, []);
  const open = (source?: CommercialBenefitBundle) => { form.resetFields(); form.setFieldsValue({ code: source?.code ?? "", name: source?.name ?? "", usage: source?.usage ?? "included", reason: "", benefits: source?.benefits.map(item => ({ code: String(item.code), value: Number(item.code === "cloud_storage" && typeof item.normalizedValue === "number" ? item.normalizedValue : item.quantity ?? 0), unit: item.code === "cloud_storage" && typeof item.normalizedValue === "number" ? "byte" : String(item.rawUnit ?? ""), policyRef: typeof item.policyRef === "string" ? item.policyRef : "" })) ?? [] }); setEditor({ source, key: key() }); setError(""); };
  const canDraft = model.authorization.can("commercial.catalog.draft"), canApprove = model.authorization.can("commercial.catalog.approve"), canPublish = model.authorization.can("commercial.catalog.publish");
  const submit = async () => { if (!editor || busy) return; let values: Values; try { values = await form.validateFields(); } catch { return; } setBusy(true); try { await commercialOperationsClient.mutateBenefitBundle({ action: "create", code: values.code, versionId: editor.source?.versionId, expectedRevision: editor.source?.revision ?? 0, idempotencyKey: editor.key, name: values.name, usage: values.usage, benefits: encodeBenefits(values.benefits, editor.source?.benefits ?? []), payload: editor.source?.payload ?? {}, reason: values.reason }); setEditor(undefined); setNotice("权益包新草稿已保存，旧套餐引用及客户合同不变。"); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : "保存结果未确认，请读取原包后核对"); } finally { setBusy(false); } };
  const execute = async () => { if (!action || busy || !reason.trim()) return; setBusy(true); try { await commercialOperationsClient.mutateBenefitBundle({ action: action.action, code: action.item.code, versionId: action.item.versionId, expectedRevision: action.item.revision, idempotencyKey: action.key, reason }); setAction(undefined); setNotice("权益包状态变更已完成，客户已购权益保持原快照。"); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : "操作结果未确认，请核对原包"); } finally { setBusy(false); } };
  const chooseAction = (item: CommercialBenefitBundle, next: CommercialCatalogAction) => { setReason(""); setError(""); setAction({ item, action: next, key: key() }); };
  const details = async (item: CommercialBenefitBundle) => { const sequence = ++refsSequence.current; setSelected(item); setRefsLoading(true); setRefs([]); setRefsError(""); try { const result = await loadAllBenefitBundleReferences((input) => commercialOperationsClient.benefitBundleReferences(item.code, item.versionId, input)); if (sequence === refsSequence.current) setRefs(result); } catch (failure) { if (sequence === refsSequence.current) setRefsError(failure instanceof Error ? failure.message : "引用读取失败"); } finally { if (sequence === refsSequence.current) setRefsLoading(false); } };
  return <section aria-labelledby="benefit-bundle-heading"><div className="commercial-catalog-heading"><div><h4 id="benefit-bundle-heading">可复用权益包</h4><p>套餐内含包不重复收费。独立销售需关联下方销售商品的价格、周期和当前在售状态。</p></div><Space><Button onClick={() => void load()} disabled={busy}>刷新权益包</Button><Button type="primary" disabled={!canDraft || loading || busy} onClick={() => open()}>新增权益组合草稿</Button></Space></div>{error && <Alert type="error" title={error} role="alert" />}{notice && <Alert type="success" title={notice} role="status" />}
    <Table<CommercialBenefitBundle> rowKey="versionId" loading={loading} dataSource={items} pagination={false} scroll={{ x: 1050 }} locale={{ emptyText: error ? "读取失败，数量不可确认" : "尚无可复用权益包，可创建草稿" }} columns={[{ title: "权益包 / 版本", render: (_, item) => <><strong>{item.name} v{item.version}</strong><div>{item.code}</div></> }, { title: "用途", render: (_, item) => item.usage === "included" ? "套餐内含（不另收费）" : "独立销售（关联SKU定价）" }, { title: "审批 / 可绑定状态", render: (_, item) => <><Tag>{approvalLabels[item.lifecycle] ?? item.lifecycle}</Tag><span>{({ active: item.lifecycle === "approved" ? "可新绑定" : "审批后才可绑定", disabled: "禁止新绑定", archived: "已归档", deleted: "已删除" } as Record<string, string>)[item.state] ?? item.state}</span></> }, { title: "操作", width: 480, render: (_, item) => <Space wrap><Button onClick={() => void details(item)}>详情与引用</Button><Button disabled={!canDraft || busy || Boolean(error) || item.state === "archived" || item.state === "deleted"} onClick={() => open(item)}>编辑新版本</Button>{item.lifecycle === "draft" && <Button disabled={!canDraft || busy || Boolean(error)} onClick={() => chooseAction(item, "submit")}>提交审批</Button>}{item.lifecycle === "pending_business_approval" && <><Button disabled={!canApprove || busy || Boolean(error)} onClick={() => chooseAction(item, "approve")}>审批通过</Button><Button disabled={!canApprove || busy || Boolean(error)} onClick={() => chooseAction(item, "reject")}>拒绝</Button></>}<Button disabled={!canPublish || busy || Boolean(error) || item.state !== "active"} onClick={() => chooseAction(item, "retire")}>停用新绑定</Button><Button danger disabled={!canPublish || busy || Boolean(error) || ["archived", "deleted"].includes(item.state)} onClick={() => chooseAction(item, "archive")}>归档</Button>{item.lifecycle === "draft" && <Button danger disabled={!canDraft || busy || Boolean(error) || items.some(version => version.code === item.code && version.lifecycle === "approved")} onClick={() => chooseAction(item, "delete_draft")}>删除草稿</Button>}</Space> }]} />
    <Space aria-label="权益包分页"><span role="status">共 {total} 个版本；第 {pageIndex + 1} 页，每页 20 个</span><Button disabled={loading || busy || pageIndex === 0} onClick={() => { const previous = pageIndex - 1; void navigate(cursorStack[previous], previous, cursorStack); }}>上一页</Button><Button disabled={loading || busy || !nextCursor} onClick={() => { if (!nextCursor) return; void navigate(nextCursor, pageIndex + 1, [...cursorStack.slice(0, pageIndex + 1), nextCursor]); }}>下一页</Button></Space>
    <Drawer title="权益包详情与引用" open={Boolean(selected)} onClose={() => setSelected(undefined)} size={760} className="commercial-catalog-dialog">{selected && <><Descriptions column={1} bordered items={[{ key: "name", label: "包与版本", children: `${selected.name} v${selected.version}` }, { key: "code", label: "编码", children: selected.code }, { key: "checksum", label: "合同校验和", children: selected.checksum }]} /><h4>权益明细</h4><ul>{selected.benefits.map(item => <li key={String(item.code)}>{String(item.code)}：{String(item.quantity ?? item.rawValue ?? "待配置")} {String(item.rawUnit ?? "")}</li>)}</ul><h4>引用该版本的套餐</h4>{refsLoading ? <p role="status">正在读取该包版本的引用</p> : refsError ? <Alert type="error" title="引用读取失败，不代表没有引用" description={refsError} /> : refs.length ? <ul>{refs.map((item, i) => <li key={i}>{String(item.sku_code ?? item.code ?? "套餐")} · {String(item.sku_version_id ?? "")}</li>)}</ul> : <p>未返回引用记录。</p>}</>}</Drawer>
    <Modal open={Boolean(editor)} title="权益包新版本草稿" onCancel={() => { if (!busy) setEditor(undefined); }} onOk={() => void submit()} confirmLoading={busy} okText="保存草稿" width={800} className="commercial-catalog-dialog"><Form form={form} layout="vertical"><Form.Item name="code" label="权益包编码（创建后固定）" rules={[{ required: true, pattern: /^[a-z0-9_-]+$/u }]}><Input disabled={Boolean(editor?.source)} /></Form.Item><Form.Item name="name" label="权益包名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="usage" label="用途（创建后固定）"><Select disabled={Boolean(editor?.source)} options={[{ value: "included", label: "套餐内含" }, { value: "standalone", label: "独立销售" }]} /></Form.Item><RegisteredBenefitFields definitions={definitions} error={definitionError} /><Form.Item name="reason" label="变更原因" rules={[{ required: true, min: 3 }]}><Input.TextArea /></Form.Item>{error && <Alert type="error" title={error} role="alert" />}</Form></Modal>
    <Modal open={Boolean(action)} title="确认权益包状态变更" onCancel={() => { if (!busy) setAction(undefined); }} footer={<Space><Button autoFocus disabled={busy} onClick={() => setAction(undefined)}>取消</Button><Button type="primary" disabled={busy || !reason.trim()} loading={busy} onClick={() => void execute()}>确认变更</Button></Space>} className="commercial-catalog-dialog"><p>{action?.item.name} v{action?.item.version} · {action?.action}</p><Alert type="info" title="只改变审批或新绑定状态，历史套餐和客户订单不会自动升级包版本。" /><label htmlFor="bundle-action-reason">原因</label><Input.TextArea id="bundle-action-reason" value={reason} onChange={event => setReason(event.target.value)} />{error && <Alert type="error" title={error} role="alert" />}</Modal>
  </section>;
}
